Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-09, with the labels that each got.

#610 EZP-29575: Provide editing interface for User Preferences in AdminUI
  src/bundle/Controller/User/UserSettingsController.php
  src/bundle/DependencyInjection/Compiler/UserSetting/FormMapperPass.php
  src/bundle/DependencyInjection/Compiler/UserSetting/ValueDefinitionPass.php
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/config/services/menu.yml
  src/bundle/Resources/config/services/user_settings.yml
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/translations/user_settings.en.xliff
  src/bundle/Resources/views/user-profile/change_user_password.html.twig
  src/bundle/Resources/views/user-profile/form_fields.html.twig
  src/bundle/Resources/views/user/settings/list.html.twig
  src/bundle/Resources/views/user/settings/update.html.twig
  src/bundle/Templating/Twig/UserPreferencesGlobalExtension.php
  src/lib/Form/Data/User/Setting/UserSettingUpdateData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/User/Setting/UserSettingUpdateType.php
  src/lib/Menu/Event/ConfigureMenuEvent.php
  src/lib/Menu/UserMenuBuilder.php
  src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
  src/lib/Pagination/Pagerfanta/UserSettingsAdapter.php
  src/lib/UserSetting/FormMapperInterface.php
  src/lib/UserSetting/FormMapperRegistry.php
  src/lib/UserSetting/Setting/Timezone.php
  src/lib/UserSetting/UserSetting.php
  src/lib/UserSetting/UserSettingService.php
  src/lib/UserSetting/ValueDefinitionInterface.php
  src/lib/UserSetting/ValueDefinitionRegistry.php
Labels: enhancement, in review, ready for review

#611 EZP-29576: Location Swap and Sort Order panels are using one cell <table> elements
  src/bundle/Resources/views/content/tab/details.html.twig
  src/bundle/Resources/views/content/tab/locations/panel_swap.html.twig
Labels: bug

#617 EZP-29606: As a developer I want to have a generic interface for drag and drop interactions
  src/bundle/Resources/public/js/scripts/core/draggable.js
  src/bundle/Resources/views/layout.html.twig
Labels: enhancement, ready for review

#620 Recovered \EzSystems\EzPlatformAdminUi\Form\Factory\FormFactory::updateUserSetting method
  src/lib/Form/Factory/FormFactory.php
Labels: bug, ready for merge

#614 EZEE-2206: As an editor I want to view the form submissions
  src/bundle/Resources/public/js/scripts/admin.location.change.language.js
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/views/admin/content_type/view.html.twig
  src/bundle/Resources/views/admin/systeminfo/composer.html.twig
  src/bundle/Resources/views/admin/systeminfo/database.html.twig
  src/bundle/Resources/views/admin/systeminfo/hardware.html.twig
  src/bundle/Resources/views/admin/systeminfo/php.html.twig
  src/bundle/Resources/views/admin/systeminfo/symfony_kernel.html.twig
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/link_manager/view.html.twig
  src/bundle/Templating/Twig/TabExtension.php
Labels: ready for review

#622 EZP-29616: Create a custom dropdown JS class to be reused in multiple places
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
  src/bundle/Resources/public/js/scripts/fieldType/ezselection.js
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
  src/bundle/Resources/views/fieldtypes/edit/ezselection.html.twig
  src/bundle/Resources/views/layout.html.twig
  src/lib/Behat/PageElement/Fields/Selection.php
Labels: enhancement, ready for QA, ready for review

#615 EZP-29579 As an Editor, I want to see dates in preferred timezone
  src/bundle/Resources/config/services/ui_config/common.yml
  src/bundle/Resources/public/js/scripts/admin.format.date.js
  src/bundle/Resources/public/js/scripts/helpers/timezone.helper.js
  src/bundle/Resources/views/admin/content_type/list.html.twig
  src/bundle/Resources/views/admin/search/search_table_row.html.twig
  src/bundle/Resources/views/content/content_edit/content_edit.html.twig
  src/bundle/Resources/views/content/content_edit/user_edit.html.twig
  src/bundle/Resources/views/content/tab/details.html.twig
  src/bundle/Resources/views/content/tab/versions/table.html.twig
  src/bundle/Resources/views/dashboard/tab/all_content.html.twig
  src/bundle/Resources/views/dashboard/tab/all_media.html.twig
  src/bundle/Resources/views/dashboard/tab/my_content.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/dashboard/tab/my_media.html.twig
  src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
  src/bundle/Resources/views/layout.html.twig
  src/bundle/Resources/views/link_manager/list.html.twig
  src/bundle/Resources/views/link_manager/view.html.twig
  src/bundle/Resources/views/user/settings/list.html.twig
  src/lib/UI/Config/Provider/DateFormat.php
  src/lib/UI/Config/Provider/Timezone.php
Labels: enhancement

#625 EZP-29614: Application does not respond after downloading a file.
  src/bundle/Resources/public/js/scripts/admin.prevent.click.js
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
Labels: QA done, ready for review

#626 CustomDropdown class: fixed item selection
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
Labels: bug, ready for review

#627 EZEE-2323: Fixes js error in MS Edge
  src/bundle/Resources/views/layout.html.twig
Labels: bug, ready for QA

#628 EZP-29636: Additional Update button visible on User Setting update screen
  src/bundle/Resources/views/user/settings/update.html.twig
Labels: QA done, bug

#629 EZP-29638: Fixed Uncaught TypeError exception when removing action fr…
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
Labels: QA done, bug, ready for review

#631 EZP-29508: As an editor I want to manage ALT field with an image asset field type
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
  src/bundle/Resources/views/fieldtypes/edit/ezimageasset.html.twig
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
  src/bundle/Resources/views/fieldtypes/preview/ezimageasset.html.twig
Labels: ready for QA

#636 EZP-29652 - Multilingual support for ezbinaryfile download in admin UI
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
Labels: QA done

#642 EZP-29615: User is unable to redo the same step after using web browser back button
  src/bundle/Resources/views/content/widgets/content_create.html.twig
Labels: QA done, bug, ready for review

#634 EZP-29602: Large images do not fit in the editor window
  src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
Labels: QA done, bug

#618 EZP-29603: Improved styling of Search and Search filters
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_content-type-selector.scss
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/views/admin/search/search.html.twig
  src/bundle/Resources/views/admin/search/search_form.html.twig
Labels: QA done

#640 EZP-29662: Reviewed Send to Trash modal in Content Type Editing view
  src/bundle/Resources/public/scss/_card.scss
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/views/admin/content_type/delete_confirmation_modal.html.twig
  src/bundle/Resources/views/admin/content_type/edit.html.twig
Labels: QA done, bug

#643 EZP-29649: [Content Type Fields] Date and time hidden fields not hidden enough
  src/bundle/Resources/views/fieldtypes/edit/ezdate.html.twig
  src/bundle/Resources/views/fieldtypes/edit/ezdatetime.html.twig
  src/bundle/Resources/views/fieldtypes/edit/eztime.html.twig
Labels: QA done, bug

#645 EZP-29670: Date for Single and Multiple relation is not updated with the user settings timezone
  src/bundle/Resources/views/fieldtypes/preview/ezobjectrelationlist_row.html.twig
Labels: bug, ready for review

#647 [i18n] Added missing UI translations
  src/bundle/Resources/translations/ezrepoforms_content_type.en.xliff
  src/bundle/Resources/translations/ezrepoforms_role.en.xliff
  src/bundle/Resources/views/Limitation/null_limitation_values.html.twig
  src/bundle/Resources/views/Limitation/udw_limitation_value.html.twig
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
Labels: QA done, ready for review

#632 EZP-29635: Styled labels in Admin Panel Edit views
  src/bundle/Resources/public/scss/_labels.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/views/admin/content_type/create.html.twig
  src/bundle/Resources/views/admin/content_type/edit.html.twig
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/admin/content_type_group/create.html.twig
  src/bundle/Resources/views/admin/content_type_group/edit.html.twig
  src/bundle/Resources/views/admin/language/create.html.twig
  src/bundle/Resources/views/admin/language/edit.html.twig
  src/bundle/Resources/views/admin/object_state/add.html.twig
  src/bundle/Resources/views/admin/object_state/edit.html.twig
  src/bundle/Resources/views/admin/object_state_group/add.html.twig
  src/bundle/Resources/views/admin/object_state_group/edit.html.twig
  src/bundle/Resources/views/admin/role/add.html.twig
  src/bundle/Resources/views/admin/role/edit.html.twig
  src/bundle/Resources/views/admin/section/create.html.twig
  src/bundle/Resources/views/admin/section/update.html.twig
  src/bundle/Resources/views/link_manager/edit.html.twig
  src/bundle/Resources/views/user-profile/change_user_password.html.twig
  src/bundle/Resources/views/user-profile/form_fields.html.twig
  src/bundle/Resources/views/user/settings/update.html.twig
Labels: QA done

#648 EZP-29672: Missing spacing between form fields
  src/bundle/Resources/public/scss/_admin.section-view.scss
  src/bundle/Resources/public/scss/_extra-actions.scss
  src/bundle/Resources/public/scss/_login.scss
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
  src/bundle/Resources/public/scss/ezplatform-bootstrap.scss
  src/bundle/Resources/public/scss/ezplatform.scss
Labels: QA done, bug, ready for review

#650 EZP-29654: No margin at the bottom of the page on Safari
  src/bundle/Resources/public/scss/_admin.content-type-view.scss
  src/bundle/Resources/public/scss/ezplatform.scss
Labels: bug, ready for QA, ready for review

#591 EZP-29408: As an editor I want to delete a content item with an image asset field
  src/bundle/Controller/ContentViewController.php
  src/bundle/Controller/Location/TrashLocationWithAssetController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/public/js/scripts/button.state.radio.toggle.js
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/modal_location_trash_with_asset.html.twig
  src/bundle/Resources/views/content/modal_location_trash_with_single_asset.html.twig
  src/lib/Form/Data/Location/LocationTrashWithAssetData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/Location/LocationTrashWithAssetType.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Specification/Content/ContentHaveAssetRelation.php
  src/lib/Specification/Content/ContentHaveUniqueRelation.php
  src/lib/Validator/Constraints/LocationHaveUniqueAssetRelation.php
  src/lib/Validator/Constraints/LocationHaveUniqueAssetRelationValidator.php
Labels: ready for QA
