Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-10, with the labels that each got.

#649 EZP-29674: Translation extractor displays error when processing Tag/Style mappers
  src/bundle/Resources/config/services/ui_config/mappers.yml
  src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag.php
  src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag/CommonAttributeMapper.php
Labels: QA done, ready for merge

#651 EZP-29687: eZ(date)Picker field clear button (X) does not clear date in flatpickr instance
  src/bundle/Resources/public/js/scripts/admin.picker.js
Labels: bug, ready for QA

#653 EZP-29688: eZ Map Location fieldtype validation error message is not displaying correctly
  src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
Labels: QA done, bug, ready for review

#655 EZP-29620: Date is not changed on Notifications pop-up
  src/bundle/Resources/views/notifications/notification_row.html.twig
Labels: QA done, bug

#652 EZP-29682: Cannot set default Location for objectrelationlist
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
  src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationStartingLocationId.php
Labels: QA done

#660 EZP-29679: Validation error messages not visible when trying to publish content
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss
  src/bundle/Resources/translations/content_edit.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
  src/bundle/Resources/views/content/content_edit/content_create.html.twig
  src/bundle/Resources/views/content/content_edit/content_edit.html.twig
  src/bundle/Resources/views/content/content_edit/user_create.html.twig
  src/bundle/Resources/views/content/content_edit/user_edit.html.twig
  src/bundle/Resources/views/content/content_on_the_fly/content_create_on_the_fly.html.twig
Labels: QA done, bug, ready for review

#656 EZP-29623: Fix System Information / Composer isn't covered on timezone change
  src/bundle/Resources/views/admin/systeminfo/composer.html.twig
Labels: QA done, bug

#661 EZP-29683: Status in link manager is misaligned
  src/bundle/Resources/views/link_manager/list.html.twig
Labels: QA done, bug, ready for review

#659 EZEE-2487: Version conflict pop-up missing for My scheduled on Dashboard
  src/bundle/Resources/views/dashboard/dashboard.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
Labels: QA done, bug

#623 EZEE-2304 As a QA I want to run DBP and FXW test features on Enterprise Demo
  src/lib/Behat/Helper/EzEnvironmentConstants.php
Labels: enhancement, ready for review

#654 EZP-29684: Remove the hyphen from the "E-mail" in whole application
  features/ContentTypeFields.feature
  src/bundle/Resources/translations/fieldtypes_preview.en.xliff
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
  src/lib/Behat/PageElement/Fields/EmailAddress.php
  src/lib/Behat/PageElement/Fields/EzFieldElement.php
Labels: QA done, ready for review

#662 EZP-29653: Image asset is not properly styled on Safari
  src/bundle/Resources/public/scss/fieldType/preview/_ezimageasset.scss
  src/bundle/Resources/views/fieldtypes/preview/ezimageasset.html.twig
Labels: QA done, bug, ready for review

#664 EZP-29650: Fix Selection field (Content Type fields) arrow color
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
Labels: QA done, bug, ready for review

#657 EZP-29624: Value in ezdatetime field is not changed
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
Labels: QA done, bug

#663 EZP-29610: 'Create new URL alias' modal is rendered when user select URL tab
  src/bundle/Resources/public/js/scripts/admin.location.add.custom_url.js
  src/bundle/Resources/views/content/tab/urls.html.twig
Labels: QA done, ready for review

#667 EZP-29663: Login page redirects to notifications/count
  src/bundle/Resources/public/js/scripts/admin.notifications.modal.js
Labels: QA done

#594 EZP-29510: Editing a draft should be able to cancel if user has version remove permission
  src/lib/Menu/ContentEditRightSidebarBuilder.php
Labels: QA done

#668 EZP-29080: Select data range - date selectors are too close
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/views/admin/search/search_form.html.twig
Labels: QA done, bug, ready for review

#666 EZEE-2490: Update BaseField validator to handle custom elements definition
  src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
Labels: QA done, bug, enhancement, ready for review

#672 EZP-29639: Labels for checkboxes and radioboxes are misaligned with inputs
  src/bundle/Resources/public/scss/_forms.scss
Labels: QA done, bug

#671 EZP-29676: Arrow pointing into Filters is too thin in Edge
  src/bundle/Resources/public/scss/_filters.scss
Labels: bug, ready for QA, ready for review

#675 EZP-29707: Cannot read property remove of null error from Selection
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
Labels: QA done, bug

#673 EZP-29700: Syntax error after logging out
  src/bundle/Resources/config/bazinga_js_translation.yml
  src/bundle/Resources/public/js/scripts/admin.notifications.modal.js
  src/bundle/Resources/translations/notifications.en.xliff
Labels: QA done, bug, ready for review

#678 EZP-29709: RequestLocaleListener tries to match SiteAccess on /_fos_user_context_hash
  src/lib/EventListener/RequestLocaleListener.php
Labels: QA done, bug

#681 EZP-29715: Javascript error with ez platform 2.3. maybe related to the new ezimageasset fieldtype
  src/bundle/Controller/ContentViewController.php
Labels: QA done, bug

#679 EZP-29660: Ezobjectrelationlist ignores allowed content types when creating content via UDW
  src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
  src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationAllowedContentTypes.php
Labels: QA done, bug, ready for merge

#641 EZP-29617: No route found after adding new translation
  src/bundle/Resources/config/services/form_processors.yml
  src/lib/RepositoryForms/Form/Processor/Content/UrlRedirectProcessor.php
Labels: QA done

#680 EZEE-2462: Edit button still active after closing draft conflict modal window - enable passing onClose callback for location edit modal
  src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js
Labels: QA done, bug

#686 EZP-29730: Cannot add UDW configuration from YAML file located in other bundle
  src/bundle/DependencyInjection/Configuration/Parser/Module/UniversalDiscoveryWidget.php
Labels: bug, ready for QA, ready for review

#687 EZP-29731: Fixed missing icon in RichText Custom Tags UI config
  src/lib/Tests/UI/Config/Mapper/FieldType/RichText/CustomTagTest.php
  src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag.php
Labels: QA done

#699 EZP-29745: Improve styling in Rich Text Editor
  src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnCustomTag.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnCustomTag.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnHeading.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnHeading.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImage.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImage.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnOrderedList.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnOrderedList.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnParagraph.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnParagraph.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnTable.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnTable.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnUnorderedList.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnUnorderedList.js.map
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-customtag.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embed.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-heading.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-image.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-linkedit.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-orderedlist.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-paragraph.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-table.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-unorderedlist.js
  src/bundle/Resources/public/scss/_alloyeditor-buttons.scss
  src/bundle/Resources/public/scss/_alloyeditor-link-edit.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/translations/alloy_editor.en.xliff
Labels: Improvement, QA approved

#694 CSS coding standard fixes
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/_icons.scss
Labels: Bug, QA approved, Ready for review, Rebase required

#684 EZP-29729: As an editor, I want to have access to all my drafts
  src/bundle/Controller/ContentDraftController.php
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/config/services/dashboard.yml
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/translations/drafts.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/views/admin/content_draft/list.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/form_fields.html.twig
  src/lib/Form/Data/Content/Draft/ContentRemoveData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/Content/Draft/ContentRemoveType.php
  src/lib/Menu/UserMenuBuilder.php
  src/lib/Tab/Dashboard/MyDraftsTab.php
  src/lib/UI/Dataset/ContentDraftsDataset.php
  src/lib/UI/Dataset/DatasetFactory.php
  src/lib/UI/Value/Content/VersionId.php
Labels: QA approved

#691 EZP-29713: As an Editor, I want to Move multiple content items at a time
  src/bundle/Controller/BulkOperation/BulkOperationController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/rest.yml
  src/lib/EventListener/ApiRequestListener.php
  src/lib/REST/Input/Parser/BulkOperation.php
  src/lib/REST/Input/Parser/Operation.php
  src/lib/REST/Output/ValueObjectVisitor/BulkOperationResponse.php
  src/lib/REST/Value/BulkOperation.php
  src/lib/REST/Value/BulkOperationResponse.php
  src/lib/REST/Value/Operation.php
  src/lib/REST/Value/OperationResponse.php
Labels: QA approved, Ready for MERGE

#696 EZP-29734: As an Administrator I want to add Content Type limitation for Section/Assign policy
  src/bundle/Controller/SectionController.php
  src/bundle/Resources/views/admin/section/assigned_content.html.twig
  src/bundle/Resources/views/admin/section/list.html.twig
  src/lib/UniversalDiscovery/Event/Subscriber/SectionAssign.php
  src/lib/Util/PermissionUtil.php
Labels: QA approved, Ready for review

#702 EZP-28067; EZP-29713: Implement bulk delete, bulk move - pass udwConfig to Sub-items
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/views/content/locationview.html.twig
Labels: Feature, QA approved

#692 EZEE-2234: Extend context of Create component to pass language
  src/bundle/Controller/ContentOnTheFlyController.php
  src/bundle/Resources/views/content/content_edit/content_create.html.twig
  src/bundle/Resources/views/content/content_on_the_fly/content_create_on_the_fly.html.twig
Labels: QA approved
