Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-02, with the labels that each got.

#342 EZP-28810: Version conflict window after clicking edit button of existing draft in Dashboard
  src/bundle/Resources/views/dashboard/dashboard.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
Labels: ready for QA, ready for review

#340 EZP-28791: As a user I want to change password
  src/bundle/Controller/UserProfile/UserPasswordChangeController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/menu.yml
  src/bundle/Resources/config/services/validators.yml
  src/bundle/Resources/public/js/scripts/user_password.change.js
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/user_change_password.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
  src/bundle/Resources/views/user-profile/change_user_password.html.twig
  src/bundle/Resources/views/user-profile/form_fields.html.twig
  src/lib/Form/Data/User/UserPasswordChangeData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/User/UserPasswordChangeType.php
  src/lib/Menu/Event/ConfigureMenuEvent.php
  src/lib/Menu/UserMenuBuilder.php
  src/lib/Menu/UserPasswordChangeRightSidebarBuilder.php
  src/lib/Tests/Validator/Constraint/UserPasswordTest.php
  src/lib/Tests/Validator/Constraint/UserPasswordValidatorTest.php
  src/lib/Validator/Constraints/UserPassword.php
  src/lib/Validator/Constraints/UserPasswordValidator.php
Labels: ready for QA, ready for review

#343 EZP-28831: Draft conflict window after clicking edit button of existing draft in Dashboard and Sub-items list
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/button.content.edit.js
  src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/versions/table.html.twig
  src/bundle/Resources/views/layout.html.twig
Labels: QA done, ready for review

#358 EZP-28875: User can't remove translation without content/all permission
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/UI/Value/ValueFactory.php
Labels: QA done, ready for review

#357 EZP-28851: Added credentials to the request checking if selected item can be considered as an image
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImage.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImage.js.map
  src/bundle/Resources/public/js/alloyeditor/src/base/ez-embedimage.js
Labels: QA done, bug, ready for review

#360 EZP-28877: As a developer I would like to inject custom tabs configuration into the Universal Discovery module instance
  src/bundle/Resources/views/layout.html.twig
Labels: QA done, ready for review
