Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-11, with the labels that each got.

#706 EZP-29702: Can't create new draft due to lack of language code in URL
  src/bundle/Resources/public/js/scripts/button.content.edit.js
Labels: QA approved, Ready for MERGE

#704 EZP-29089: Usability bug when deleting containers
  src/bundle/Controller/ContentViewController.php
  src/bundle/Controller/LocationController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/public/js/scripts/admin.trash.container.js
  src/bundle/Resources/public/js/scripts/button.state.checkbox.toggle.js
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/modal_location_trash_container.html.twig
  src/lib/Form/Data/Location/LocationTrashContainerData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/Location/LocationTrashContainerType.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Specification/Location/HasChildren.php
  src/lib/Validator/Constraints/LocationHasChildren.php
  src/lib/Validator/Constraints/LocationHasChildrenValidator.php
Labels: QA approved

#707 EZP-29769: Added discovery bar to the Drafts interface
  src/bundle/Resources/views/admin/content_draft/list.html.twig
Labels: Feature, QA approved, Ready for review

#708 EZP-29793: Implement permissions for the Create button on the dashboard
  src/bundle/Controller/DashboardController.php
  src/bundle/Resources/translations/dashboard.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/views/dashboard/dashboard.html.twig
Labels: Improvement, QA approved, Ready for review

#709 EZP-29328: As an editor I want AE to support formatted text
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomStyleConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomStyleConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomTagConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomTagConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedImageConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedImageConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezFormattedConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezFormattedConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezHeadingConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezHeadingConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezParagraphConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezParagraphConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezToolbarAdd.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezToolbarAdd.js.map
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-formatted.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/ez-add.js
  src/bundle/Resources/public/js/scripts/fieldType/ezrichtext.js
  src/bundle/Resources/public/scss/fieldType/edit/_ezrichtext.scss
  src/bundle/Resources/translations/alloy_editor.en.xliff
  webpack.config.js
Labels: Feature

#716 EZP-29728: Longitude validation appears when user try to publish after editing
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
  src/bundle/Resources/views/fieldtypes/edit/ezgmaplocation.html.twig
Labels: Bug, QA approved, Ready for review

#717 EZP-29813: Pass custom parameters to menu item templates in right sidebar
  src/bundle/Resources/views/parts/menu/sidebar_base.html.twig
Labels: Improvement, QA approved, Ready for review

#701 EZP-29748: Replacing the outdated verbiage of eZ Publish from eZ Platform when adding a Policy
  features/Roles.feature
  src/bundle/Resources/config/services/translation.yml
  src/bundle/Resources/translations/ezrepoforms_role.en.xliff
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/views/admin/policy/list.html.twig
  src/bundle/Resources/views/content/tab/policies/table.html.twig
  src/lib/Form/Type/Policy/PolicyChoiceType.php
  src/lib/Translation/Extractor/PolicyTranslationExtractor.php
Labels: QA approved, Ready for review

#700 EZP-29171: Update Navbar menu items order
  src/bundle/Resources/config/services/menu.yml
  src/lib/Menu/Admin/ReorderMenuListener.php
Labels: QA approved

#719 EZP-29761: RichText Editor crashes after adding link to the content into unordered list
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedImageConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedImageConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezToolbarAdd.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezToolbarAdd.js.map
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-embed.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-image.js
Labels: Bug, QA approved

#718 [EZP-29819] Set config providers which use dynamic settings to lazy
  src/bundle/Resources/config/services/ui_config/common.yml
Labels: Bug, QA approved, Ready for review

#723 EZP-29832: Unable to use AdminUI without admin rights
  src/lib/Menu/Admin/ReorderMenuListener.php
Labels: QA approved

#722 EZP-29828: Custom Dropdown improvements
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
Labels: Improvement, QA approved, Ready for review

#721 EZP-29827: Harmonized Preview Switcher in Content Section Editing view
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/_preview.scss
Labels: Bug

#711 EZP-29766: As an editor, I want to filter the search using subtree parameter
  src/bundle/Controller/SearchController.php
  src/bundle/Resources/config/services/ui_config/common.yml
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/js/scripts/udw/select.location.js
  src/bundle/Resources/public/scss/_content-type-selector.scss
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/translations/search.en.xliff
  src/bundle/Resources/translations/universal_discovery_widget.en.xliff
  src/bundle/Resources/views/admin/search/search.html.twig
  src/bundle/Resources/views/admin/search/search_form.html.twig
  src/bundle/Resources/views/form_fields.html.twig
  src/bundle/Templating/Twig/PathStringExtension.php
  src/lib/Form/Data/Search/SearchData.php
  src/lib/Form/Type/Search/SearchType.php
Labels: Feature, QA approved
