Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-06, with the labels that each got.

#498 EZP-29268: Change bookmark status in Location page when bookmark changed elsewhere on the site
  src/bundle/Resources/public/js/scripts/admin.location.bookmark.js
Labels: QA done

#504 EZP-29295: Second level of main menu has no context passed
  src/bundle/Resources/views/parts/navigation.html.twig
Labels: QA done, bug, ready for review

#503 EZEE-2065 / EZEE-2066: Ui Action event dispatching and view management for content translation
  src/bundle/Controller/ContentEditController.php
  src/bundle/DependencyInjection/Compiler/ViewBuilderRegistryPass.php
  src/bundle/DependencyInjection/Configuration/Parser/ContentTranslateView.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/form_ui_action_mappers.yml
  src/bundle/Resources/config/services/views.yml
  src/bundle/Resources/config/views.yml
  src/bundle/Resources/public/js/scripts/admin.location.add.translation.js
  src/bundle/Resources/public/scss/_add-translation.scss
  src/bundle/Resources/views/content/modal_add_translation.html.twig
  src/bundle/Resources/views/content/tab/translations/modal_add_translation.html.twig
  src/bundle/Resources/views/content/tab/translations/translation_add_form_fields.html.twig
  src/bundle/Resources/views/content/translation_add_form_fields.html.twig
  src/bundle/Resources/views/http/no_content.html.twig
  src/lib/EventListener/ContentTranslateViewFilterParametersListener.php
  src/lib/Form/SubmitHandler.php
  src/lib/RepositoryForms/Data/Mapper/ContentTranslationMapper.php
  src/lib/RepositoryForms/View/ViewParametersListener.php
  src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php
  src/lib/UI/Action/EventDispatcher.php
  src/lib/UI/Action/EventDispatcherInterface.php
  src/lib/UI/Action/FormUiActionMapper.php
  src/lib/UI/Action/FormUiActionMapperInterface.php
  src/lib/UI/Action/FormUiActionMappingDispatcher.php
  src/lib/UI/Action/UiActionEvent.php
  src/lib/UI/Action/UiActionEventInterface.php
  src/lib/Util/ContentTypeUtil.php
  src/lib/View/Builder/ContentTranslateViewBuilder.php
  src/lib/View/ContentTranslateSuccessView.php
  src/lib/View/ContentTranslateView.php
  src/lib/View/Filter/ContentTranslateViewFilter.php
  src/lib/View/Provider/ContentTranslateView/Configured.php
Labels: enhancement, ready for review

#509 EZP-29266: Content item seems to be always bookmarked
  src/bundle/Resources/public/js/scripts/admin.location.bookmark.js
  src/bundle/Resources/public/scss/_add-to-bookmarks.scss
  src/bundle/Resources/views/parts/form/location_bookmark.html.twig
Labels: bug, ready for review

#507 EZP-29119: Display proper validation error message when non-image file uploaded in image FieldType
  src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
  src/bundle/Resources/views/content/form_fields.html.twig
  src/bundle/Resources/views/fieldtypes/edit/binary_base.html.twig
Labels: ready for QA, ready for review

#514 EZP-29309: Validators with errors not exposed on the frontend
  .prettierrc
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
Labels: QA done, bug, ready for review

#513 EZP-29306: Display notification about missing Language on adding CT i…
  src/bundle/Controller/ContentTypeController.php
  src/bundle/Resources/translations/content_type.en.xliff
Labels: QA done, ready for review

#515 EZP-29310: Implement permissions for Add Location in Locations tab
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
  src/lib/Tab/LocationView/LocationsTab.php
Labels: ready for QA, ready for review

#517 EZP-29312: Implement permissions for Swap Location in Locations tab
  src/bundle/Resources/views/content/tab/locations/panel_swap.html.twig
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
  src/lib/Tab/LocationView/LocationsTab.php
Labels: QA done, ready for review

#520 EZP-29313: Implement permissions for Version remove in Versions tab
  src/bundle/Resources/views/content/tab/versions/table.html.twig
  src/lib/UI/Value/Content/VersionInfo.php
  src/lib/UI/Value/ValueFactory.php
Labels: QA done, ready for review

#519 EZP-29311: Implement permissions for Change main Location in Locations tab
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
  src/lib/UI/Value/Content/Location.php
  src/lib/UI/Value/ValueFactory.php
Labels: QA done, ready for review

#529 EZEE-2121: Added header block in page layout
  src/bundle/Resources/views/layout.html.twig
Labels: QA done, bug, ready for review

#530 EZEE-2111: Landing Page field is visible while creating new Page with COTF
  src/bundle/DependencyInjection/Configuration/Parser/AdminUiForms.php
  src/bundle/DependencyInjection/EzPlatformAdminUiExtension.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/admin_ui_forms.yml
  src/bundle/Resources/config/services/ui_config/common.yml
  src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
  src/bundle/Tests/DependencyInjection/Configuration/Parser/AdminUiFormsTest.php
Labels: QA done

#535 Fixed 2 parameters types passed to SubItems & MultiFileUpload
  src/bundle/Resources/public/js/scripts/admin.location.view.js
Labels: QA done, bug, ready for review

#528 EZP-29203: Implement permissions for Trash
  src/bundle/Controller/TrashController.php
  src/bundle/Resources/views/admin/trash/list.html.twig
  src/lib/Menu/LeftSidebarBuilder.php
Labels: QA done, ready for review

#536 EZP-28805: Inconsistency for Publish later container - Date & Time input is almost invisible
  src/bundle/Resources/public/scss/_extra-actions.scss
Labels: QA done, bug, ready for review

#537 EZP-29337: Fix LocationsTransformerTest unit test
  src/lib/Tests/Form/DataTransformer/LocationsTransformerTest.php
Labels: QA done, ready for review

#539 EZP-29330: Long title covers (X) button in message bar
  src/bundle/Resources/public/scss/_notifications.scss
Labels: bug, ready for review

#540 EZP-29180: Update styling of notifications
  src/bundle/Resources/public/scss/_notifications.scss
Labels: enhancement, ready for review

#532 EZP-29322: As an editor I want to use translated Admin panel
  src/bundle/Resources/config/services.yml
  src/lib/EventListener/RequestLocaleListener.php
Labels: ready for review

#538 EZP-29179: Implement permissions for "Content/Hide"
  src/bundle/Controller/LocationController.php
  src/bundle/Resources/public/js/scripts/admin.location.visibility.js
  src/bundle/Resources/public/js/scripts/helpers/notification.helper.js
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
  src/bundle/Resources/views/layout.html.twig
  src/lib/Tab/LocationView/LocationsTab.php
Labels: ready for review

#544 EZP-29288: Edit button on Bookmarks list is not aligned
  src/bundle/Resources/views/admin/bookmark/list.html.twig
Labels: bug, enhancement, ready for review

#545 EZP-29342: Deleting related object for ezobjectrelations field throws error 500
  src/bundle/Controller/ContentViewController.php
Labels: QA done

#548 EZP-29114: Fix pagination parameter naming for draft, system and custom url
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/config/services/controllers.yml
Labels: QA done

#549 EZP-29101: Implement permissions for Content Types
  src/bundle/Controller/ContentTypeController.php
  src/bundle/Controller/ContentTypeGroupController.php
  src/bundle/Resources/views/admin/content_type/list.html.twig
  src/bundle/Resources/views/admin/content_type/view.html.twig
  src/bundle/Resources/views/admin/content_type_group/list.html.twig
Labels: QA done, ready for review

#547 EZP-29341: I want Bookmark button to work without page reload
  src/bundle/Controller/ContentViewController.php
  src/bundle/Controller/Location/BookmarkController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/public/js/scripts/admin.location.bookmark.js
  src/bundle/Resources/public/scss/_add-to-bookmarks.scss
  src/bundle/Resources/views/parts/form/location_bookmark.html.twig
  src/bundle/Resources/views/parts/location_bookmark.html.twig
  src/bundle/Resources/views/parts/page_title.html.twig
  src/lib/Form/Data/Location/LocationUpdateBookmarkData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/SubmitHandler.php
  src/lib/Form/Type/Location/LocationUpdateBookmarkType.php
Labels: QA done, enhancement, ready for review
