Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-05, with the labels that each got.

#457 EZP-29131: Improvements to disabling/hiding elements
  src/bundle/Resources/translations/object_state.en.xliff
  src/bundle/Resources/views/admin/language/view.html.twig
  src/bundle/Resources/views/admin/section/list.html.twig
  src/bundle/Resources/views/admin/section/view.html.twig
  src/bundle/Resources/views/content/tab/details.html.twig
  src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php
  src/lib/Tab/LocationView/DetailsTab.php
Labels: QA done, ready for review

#451 EZP-28479: In the content item edit view, the application does not display the help text when I hover over the input field
  src/bundle/Resources/views/content/form_fields.html.twig
Labels: QA done, ready for review

#449 EZP-28806: As a developer I want to define the SiteAccess name
  src/bundle/Resources/views/content/content_preview.html.twig
Labels: ready for review

#461 EZP-29036: As an Editor, I want useful information about the Image field type in Content View mode
  src/bundle/Resources/public/scss/fieldType/preview/_ezimage.scss
  src/bundle/Resources/translations/fieldtypes_preview.en.xliff
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
Labels: QA done, ready for review

#462 EZP-29133: Implement permission to access Admin Panel
  src/bundle/Resources/config/services.yml
  src/lib/EventListener/MenuPermissionsListener.php
  src/lib/Menu/MainMenuBuilder.php
  src/lib/Tests/Menu/MainMenuBuilerTest.php
Labels: QA done, ready for review

#466 EZP-29125: Links attached via UDW in RichText are removed
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js.map
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-linkedit.js
Labels: bug, ready for review

#464 EZP-29161: Hide Section table in Details if the user does not have "Section/View"
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/views/admin/search/search_form.html.twig
  src/bundle/Resources/views/content/tab/details.html.twig
  src/lib/Form/Type/Search/SearchType.php
  src/lib/Tab/LocationView/DetailsTab.php
Labels: QA done, ready for review

#463 EZP-29099: Implement permissions for Section management in Admin Panel
  src/bundle/Controller/SectionController.php
  src/bundle/Resources/views/admin/section/assigned_content.html.twig
  src/bundle/Resources/views/admin/section/list.html.twig
  src/bundle/Resources/views/admin/section/view.html.twig
Labels: QA done, ready for review

#465 EZP-28840: As an editor I want to bookmark a content item from Content View
  src/bundle/Controller/ContentViewController.php
  src/bundle/Controller/Location/BookmarkController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services/service_aliases.yml
  src/bundle/Resources/public/js/scripts/admin.location.bookmark.js
  src/bundle/Resources/public/scss/_add-to-bookmarks.scss
  src/bundle/Resources/public/scss/_animations.scss
  src/bundle/Resources/public/scss/_header.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/parts/form/location_bookmark.html.twig
  src/lib/Form/Data/Location/LocationUpdateBookmarkData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/Location/LocationUpdateBookmarkType.php
Labels: QA done

#470 EZP-29160: Hide Roles and Policies tab if the user does not have "Role/Read" permission
  src/lib/Tab/LocationView/PoliciesTab.php
  src/lib/Tab/LocationView/RolesTab.php
Labels: QA done, ready for review

#475 EZEE-2025: Add extension point in `content_edit_base.html.twig` allowing spoofing form templates
  src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
Labels: enhancement, ready for review

#473 EZP-28837: As an editor I want to access to my bookmarks
  src/bundle/Controller/BookmarkController.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/translations/bookmark.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/views/admin/bookmark/list.html.twig
  src/bundle/Resources/views/form_fields.html.twig
  src/lib/Form/Data/Bookmark/BookmarkRemoveData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/Bookmark/BookmarkRemoveType.php
  src/lib/Menu/LeftSidebarBuilder.php
  src/lib/Menu/UserMenuBuilder.php
  src/lib/UI/Dataset/BookmarksDataset.php
  src/lib/UI/Dataset/DatasetFactory.php
  src/lib/UI/Value/Location/Bookmark.php
  src/lib/UI/Value/ValueFactory.php
Labels: QA done, ready for review

#478 EZP-29212: Error 500 when user doen't have Content/versionread policy
  src/lib/Tab/LocationView/VersionsTab.php
Labels: QA done, bug, ready for review

#479 EZP-29213: Error 500 when user doesn't have Content/reverserelatedlist policy
  src/lib/Tab/LocationView/RelationsTab.php
Labels: QA done, bug, ready for review

#469 EZP-29103: Implement permissions for Object State in Admin Panel
  src/bundle/Controller/ObjectStateController.php
  src/bundle/Controller/ObjectStateGroupController.php
  src/bundle/Resources/views/admin/object_state/list.html.twig
  src/bundle/Resources/views/admin/object_state_group/list.html.twig
  src/bundle/Resources/views/content/tab/details.html.twig
  src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php
  src/lib/Menu/MainMenuBuilder.php
  src/lib/Tab/LocationView/DetailsTab.php
Labels: QA done, ready for review

#481 EZP-29209: Front-end Notification System (from JS) API
  src/bundle/DependencyInjection/Configuration/Parser/Notifications.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services/ui_config/common.yml
  src/bundle/Resources/public/js/scripts/admin.notifications.js
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/layout.html.twig
  src/bundle/Resources/views/parts/notification.html.twig
  src/lib/UI/Config/Provider/Notifications.php
Labels: enhancement, ready for QA, ready for review

#477 EZP-29216: Implement permissions for Role management in Admin Panel
  src/bundle/Controller/PolicyController.php
  src/bundle/Controller/RoleAssignmentController.php
  src/bundle/Controller/RoleController.php
  src/bundle/Resources/views/admin/policy/list.html.twig
  src/bundle/Resources/views/admin/role/list.html.twig
  src/bundle/Resources/views/admin/role_assignment/list.html.twig
Labels: QA done, ready for review

#483 EZP-29214: Error 403 after trying to publish CI without Content/Publish or Content/Edit policies
  src/bundle/Resources/views/content/content_edit/content_create.html.twig
  src/lib/Menu/ContentCreateRightSidebarBuilder.php
  src/lib/Menu/ContentEditRightSidebarBuilder.php
Labels: QA done, ready for review

#484 EZP-29204: RichText link popup on Microsoft Edge has broken styling
  src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
Labels: QA done, bug, ready for review

#485 EZP-29154: As a developer, I want to configure the number of sub-items displayed in the sub-items list
  src/bundle/Resources/config/services/ui_config/common.yml
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/views/content/locationview.html.twig
  src/lib/UI/Config/Provider/Module/SubItemsList.php
  src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php
Labels: QA done, ready for review

#487 EZEE-2021: Fields view in Page View mode for Page builder
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/utils.yml
  src/bundle/Resources/views/content/content_view_fields.html.twig
  src/bundle/Resources/views/content/tab/content.html.twig
  src/lib/Tab/LocationView/ContentTab.php
  src/lib/Tests/Tab/ContentTabTest.php
  src/lib/Tests/Util/FieldDefinitionGroupsUtilTest.php
  src/lib/Util/FieldDefinitionGroupsUtil.php
Labels: QA done, enhancement

#493 Reorganized SCSS mixins and moved all of them to one file
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
Labels: enhancement, ready for QA, ready for review

#495 EZP-29259: Fix pagination for content displayed by route _ez_content_view
  src/bundle/Controller/ContentViewController.php
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/views/content/tab/policies/tab.html.twig
  src/bundle/Resources/views/content/tab/roles/tab.html.twig
  src/bundle/Resources/views/content/tab/urls.html.twig
  src/bundle/Resources/views/content/tab/versions/tab.html.twig
Labels: QA done, bug, ready for review
