Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-04, with the labels that each got.

#435 EZP-29028: Subtree should be shown in a new line
  composer.json
  features/ContentType.feature
  src/bundle/DependencyInjection/EzPlatformAdminUiExtension.php
  src/bundle/Resources/config/role.yml
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/views/Limitation/null_limitation_values.html.twig
  src/bundle/Resources/views/Limitation/udw_limitation_value.html.twig
  src/bundle/Resources/views/admin/content_type/view.html.twig
Labels: QA done, ready for review

#430 EZP-27961: Copying a content item - Restrict a user from selecting a non-container location in the UDW component
  src/bundle/Resources/public/js/scripts/udw/copy.js
  src/bundle/Resources/public/js/scripts/udw/move.js
Labels: QA done

#428 EZP-28980: When restoring a trash item under a new parent, the user should not be able to select multiple location in the UDW
  src/bundle/Resources/public/js/scripts/admin.trash.list.js
Labels: QA done

#427 EZP-28862: Require an explicit permission for the System Info route
  src/bundle/Controller/SystemInfoController.php
Labels: QA done

#437 EZP-29049: As a user, I want to delete a single item in the trash.
  src/bundle/Controller/TrashController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/public/js/scripts/admin.trash.list.js
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/trash.en.xliff
  src/bundle/Resources/views/admin/trash/list.html.twig
  src/lib/Form/Data/Trash/TrashItemDeleteData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/Trash/TrashItemDeleteType.php
Labels: QA done, ready for review

#436 EZP-28955: Adding pagination to URL Aliases in the URL alias tab
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/pagination.html.twig
  src/bundle/Resources/views/content/tab/url/custom_urls_table.html.twig
  src/bundle/Resources/views/content/tab/url/system_urls_table.html.twig
  src/bundle/Resources/views/content/tab/urls.html.twig
  src/lib/Tab/LocationView/UrlsTab.php
Labels: QA done

#441 EZP-29068: [Content Types] Regression - missing PR #422 with label in consistencies fix
  features/ContentType.feature
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/views/admin/content_type/view.html.twig
Labels: ready for QA, ready for review

#431 EZP-28059: As an Editor, I want to search/filter for a content item by entering the name of the creator
  src/bundle/Controller/SearchController.php
  src/bundle/DependencyInjection/Configuration/Parser/UserIdentifier.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/translations/search.en.xliff
  src/bundle/Resources/views/admin/search/search_form.html.twig
  src/lib/Form/Data/Search/SearchData.php
  src/lib/Form/DataTransformer/UserTransformer.php
  src/lib/Form/Type/Search/SearchType.php
  src/lib/Form/Type/User/UserType.php
  src/lib/Tests/Form/DataTransformer/UserTransformerTest.php
Labels: QA done, ready for review

#444 EZP-29070: Add edit button on content type view.
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/views/admin/content_type/list.html.twig
  src/bundle/Resources/views/admin/content_type/macros.html.twig
  src/bundle/Resources/views/admin/content_type/view.html.twig
Labels: QA done, ready for review

#443 EZP-29066: As a website administrator, I want to see the roles assigned to a user or user group
  src/bundle/Controller/ContentViewController.php
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
  src/bundle/DependencyInjection/Configuration/Parser/UserGroupIdentifier.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/config/services/tabs/locationview.yml
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/translations/role.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/roles/limitation_values.html.twig
  src/bundle/Resources/views/content/tab/roles/tab.html.twig
  src/bundle/Resources/views/content/tab/roles/table.html.twig
  src/bundle/Templating/Twig/TabExtension.php
  src/lib/EventListener/SystemInfoTabGroupListener.php
  src/lib/Specification/ContentType/ContentTypeIsUser.php
  src/lib/Specification/ContentType/ContentTypeIsUserGroup.php
  src/lib/Tab/ConditionalTabInterface.php
  src/lib/Tab/Event/Subscriber/ConditionalTabSubscriber.php
  src/lib/Tab/Event/TabEvents.php
  src/lib/Tab/LocationView/RolesTab.php
  src/lib/Tests/EventListener/SystemInfoTabGroupListenerTest.php
  src/lib/UI/Dataset/DatasetFactory.php
  src/lib/UI/Dataset/RolesDataset.php
  src/lib/UI/Value/User/Role.php
  src/lib/UI/Value/ValueFactory.php
Labels: QA done, ready for review

#454 Fixed EZP-29087: Changed policy which allows to trash a Location
  src/lib/Menu/ContentRightSidebarBuilder.php
Labels: QA done

#456 EZP-29020: Cannot access content menu tabs when state assign policy is set
  src/lib/UI/Value/ValueFactory.php
Labels: QA done, ready for review

#455 EZP-29022: If user has logged out in edit mode of CT nobody can edit this CT
  src/bundle/Controller/ContentTypeController.php
  src/bundle/Resources/translations/content_type.en.xliff
Labels: QA done, ready for review

#458 EZEE-1974: Correct SVG icons identifiers names for reusing them in Page Builder blocks
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/collection.svg
  src/bundle/Resources/public/img/icons/contentlist.svg
  src/bundle/Resources/public/img/icons/embed.svg
  src/bundle/Resources/public/img/icons/keyword.svg
  src/bundle/Resources/public/img/icons/places.svg
Labels: QA done, bug, ready for review
