Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-08, with the labels that each got.

#578 EZP-29091: Publishing Content from the frontend results in error
  src/bundle/Resources/config/services/form_processors.yml
  src/lib/RepositoryForms/Form/Processor/Content/UrlRedirectProcessor.php
Labels: QA done

#590 EZP-29496: Improved styling of ez_author field type buttons in edit view
  src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss
Labels: bug

#587 EZP-29495: Reviewed Object Relations table header action btns in edit…
  src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
  src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
Labels: bug

#584 EZP-29224: Implement permissions for "Content/Remove"
  src/lib/Menu/ContentRightSidebarBuilder.php
Labels: QA done, ready for review

#589 EZP-29498: showDangerNotification duplicates the functionality of showErrorNotification
  src/bundle/Resources/public/js/scripts/helpers/notification.helper.js
Labels: QA done, bug, ready for review

#593 EZEE-2262: Add icons for fields in Form Builder
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/button.svg
  src/bundle/Resources/public/img/icons/captcha.svg
  src/bundle/Resources/public/img/icons/checkbox-multiple.svg
  src/bundle/Resources/public/img/icons/checkbox.svg
  src/bundle/Resources/public/img/icons/date.svg
  src/bundle/Resources/public/img/icons/dropdown.svg
  src/bundle/Resources/public/img/icons/input-hidden.svg
  src/bundle/Resources/public/img/icons/input-line-multiple.svg
  src/bundle/Resources/public/img/icons/input-line.svg
  src/bundle/Resources/public/img/icons/input-number.svg
  src/bundle/Resources/public/img/icons/radio-button-multiple.svg
  src/bundle/Resources/public/img/icons/radio-button.svg
  src/bundle/Resources/public/img/icons/rate.svg
Labels: ready for review

#592 EZEE-2264: Add icons for the timeline events
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/back-current-date.svg
  src/bundle/Resources/public/img/icons/block-invisible.svg
  src/bundle/Resources/public/img/icons/block-visible-recurring.svg
  src/bundle/Resources/public/img/icons/block-visible.svg
Labels: enhancement

#597 EZEE-2016: Fix date/time format on Dashboard & Link manager
  src/bundle/Resources/views/admin/content_type/list.html.twig
  src/bundle/Resources/views/admin/search/search_table_row.html.twig
  src/bundle/Resources/views/dashboard/tab/all_content.html.twig
  src/bundle/Resources/views/dashboard/tab/all_media.html.twig
  src/bundle/Resources/views/dashboard/tab/my_content.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/dashboard/tab/my_media.html.twig
  src/bundle/Resources/views/link_manager/list.html.twig
  src/bundle/Resources/views/link_manager/view.html.twig
Labels: QA done, bug

#596 EZP-29232: ez-user-menu covered by ez-context-menu in Safari
  src/bundle/Resources/public/scss/_user-menu.scss
Labels: QA done, bug

#595 EZP-29530: Simplify extending global eZ config
  src/bundle/Resources/translations/validators.en.xliff
  src/bundle/Resources/views/layout.html.twig
Labels: QA done, enhancement, ready for review

#607 Added the utility class for preventing scroll
  src/bundle/Resources/public/scss/_general.scss
Labels: enhancement, ready for merge, ready for review

#586 EZP-29290: As an Editor, I want to have preconfigured "Author" section while creating the content
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
Labels: QA done, ready for merge

#546 EZP-29348: Edit buttons in tables are not aligned with delete button in table header
  src/bundle/Resources/public/js/scripts/button.state.toggle.js
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/views/admin/bookmark/list.html.twig
  src/bundle/Resources/views/admin/content_type/list.html.twig
  src/bundle/Resources/views/admin/content_type/view.html.twig
  src/bundle/Resources/views/admin/content_type_group/list.html.twig
  src/bundle/Resources/views/admin/language/list.html.twig
  src/bundle/Resources/views/admin/language/view.html.twig
  src/bundle/Resources/views/admin/object_state/list.html.twig
  src/bundle/Resources/views/admin/object_state/view.html.twig
  src/bundle/Resources/views/admin/object_state_group/list.html.twig
  src/bundle/Resources/views/admin/object_state_group/view.html.twig
  src/bundle/Resources/views/admin/policy/list.html.twig
  src/bundle/Resources/views/admin/role/list.html.twig
  src/bundle/Resources/views/admin/role_assignment/list.html.twig
  src/bundle/Resources/views/admin/search/search_table_row.html.twig
  src/bundle/Resources/views/admin/section/list.html.twig
  src/bundle/Resources/views/admin/section/view.html.twig
  src/bundle/Resources/views/admin/trash/list.html.twig
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
  src/bundle/Resources/views/content/tab/translations/tab.html.twig
  src/bundle/Resources/views/content/tab/url/custom_urls_table.html.twig
  src/bundle/Resources/views/content/tab/versions/table.html.twig
  src/bundle/Resources/views/dashboard/tab/all_content.html.twig
  src/bundle/Resources/views/dashboard/tab/all_media.html.twig
  src/bundle/Resources/views/dashboard/tab/my_content.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/dashboard/tab/my_media.html.twig
  src/bundle/Resources/views/link_manager/list.html.twig
  src/bundle/Resources/views/link_manager/view.html.twig
  src/lib/Behat/PageElement/Tables/LinkedListTable.php
  src/lib/Behat/PageElement/Tables/SimpleListTable.php
Labels: bug, enhancement, ready for review

#601 README update
  README.md
Labels: ready for merge
