Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-03, with the labels that each got.

#364 EZP-28880: Needless <> for ezauthor in view mode
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
Labels: QA done, bug, ready for review

#367 EZP-28887: Unexpected radio buttons in the content type selector and language selector
  src/bundle/Resources/public/scss/_extra-actions.scss
  src/bundle/Resources/views/form_fields.html.twig
Labels: QA done, bug

#353 EZP-28892: User UI Config provider breaks when using Guard authentication
  src/lib/UI/Config/Provider/User.php
Labels: QA done

#351 EZP-28852: Rework AdminUI content edit views to allow extending without using pagelayout
  src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
  src/bundle/Resources/views/content/content_edit/parts/javascripts.html.twig
  src/bundle/Resources/views/content/content_edit/parts/stylesheets.html.twig
Labels: enhancement, ready for review

#374 EZP-28850: Add optional location parameter to draft edit for more appropriate redirection
  src/bundle/Controller/Content/VersionDraftConflictController.php
  src/bundle/Controller/ContentController.php
  src/bundle/Controller/ContentEditController.php
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/views/content/content_edit/content_edit.html.twig
  src/bundle/Resources/views/content/content_preview.html.twig
  src/bundle/Resources/views/content/modal_draft_conflict.html.twig
  src/bundle/Resources/views/content/tab/versions/table.html.twig
  src/lib/Form/Data/Content/Draft/ContentEditData.php
  src/lib/Form/Type/Content/Draft/ContentEditType.php
  src/lib/RepositoryForms/Form/Processor/PreviewFormProcessor.php
  src/lib/Tab/LocationView/VersionsTab.php
  src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php
Labels: ready for review

#373 EZP-26238: eZPlatform login screen redirecting to the link the user entered initially
  src/bundle/Resources/views/Security/login.html.twig
Labels: QA done

#372 EZP-28884: Removing click when editing content in one single language
  src/bundle/Resources/public/js/scripts/sidebar/btn/content.edit.js
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/widgets/content_edit.html.twig
Labels: QA done

#363 EZP-27840: As an Editor, I want to create a custom URL alias for a content item
  src/bundle/Controller/UrlAliasController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/public/js/scripts/admin.location.add.custom_url.js
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
  src/bundle/Resources/translations/content_url.en.xliff
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/url/checkbox.html.twig
  src/bundle/Resources/views/content/tab/url/modal_add_custom_url.html.twig
  src/bundle/Resources/views/content/tab/urls.html.twig
  src/lib/Form/Data/Content/CustomUrl/CustomUrlAddData.php
  src/lib/Form/EventListener/AddLanguageFieldBasedOnContentListener.php
  src/lib/Form/EventListener/BuildPathFromRootListener.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/Content/CustomUrl/CustomUrlAddType.php
  src/lib/Tab/LocationView/UrlsTab.php
Labels: QA done, enhancement, ready for review

#375 EZP-28920: Configure content edit view in AdminUI
  src/bundle/Resources/config/default_parameters.yml
  src/bundle/Resources/config/views.yml
Labels: QA done, enhancement, ready for review

#369 EZP-27536: As a Editor I want to delete a URL alias in the URL alias tab
  src/bundle/Controller/Controller.php
  src/bundle/Controller/UrlAliasController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/translations/content_url.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/content/tab/url/modal_add_custom_url.html.twig
  src/bundle/Resources/views/content/tab/urls.html.twig
  src/lib/Form/Data/Content/CustomUrl/CustomUrlRemoveData.php
  src/lib/Form/EventListener/AddLanguageFieldBasedOnContentListener.php
  src/lib/Form/EventListener/BuildPathFromRootListener.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/Content/CustomUrl/CustomUrlAddType.php
  src/lib/Form/Type/Content/CustomUrl/CustomUrlRemoveType.php
  src/lib/Tab/LocationView/UrlsTab.php
  src/lib/UI/Dataset/CustomUrlsDataset.php
  src/lib/UI/Dataset/DatasetFactory.php
  src/lib/UI/Value/Content/UrlAlias.php
  src/lib/UI/Value/ValueFactory.php
Labels: ready for QA, ready for review

#371 EZP-28314: As a v2 Editor, I want to select a SiteAccess in the Preview mode
  src/bundle/Controller/ContentController.php
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/components.yml
  src/bundle/Resources/config/services/components/content/edit.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/config/services/siteaccess.yml
  src/bundle/Resources/public/js/scripts/admin.preview.js
  src/bundle/Resources/public/scss/_alerts.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/_preview.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/translations/content_edit_component_preview_unavailable.en.xliff
  src/bundle/Resources/translations/content_preview.en.xliff
  src/bundle/Resources/views/content/content_edit/component/preview_unavailable.html.twig
  src/bundle/Resources/views/content/content_edit/content_edit.html.twig
  src/bundle/Resources/views/content/content_preview.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/lib/Component/Content/PreviewUnavailableTwigComponent.php
  src/lib/Menu/ContentEditRightSidebarBuilder.php
  src/lib/RepositoryForms/Form/Processor/PreviewFormProcessor.php
  src/lib/Siteaccess/NonAdminSiteaccessResolver.php
  src/lib/Siteaccess/SiteaccessResolver.php
  src/lib/Siteaccess/SiteaccessResolverInterface.php
Labels: QA done, enhancement

#381 EZP-28894: Cannot publish Content Object with Image field type
  src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
  src/bundle/Resources/views/fieldtypes/edit/binary_base.html.twig
  src/bundle/Resources/views/fieldtypes/edit/ezmedia.html.twig
Labels: bug, ready for QA

#376 EZP-28921: Configure content create view in AdminUI
  src/bundle/Resources/config/default_parameters.yml
  src/bundle/Resources/config/views.yml
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
Labels: ready for QA, ready for review

#72 [EZP-28238] Add the ability to manage states in admin
  src/bundle/Controller/ObjectStateController.php
  src/bundle/Controller/ObjectStateGroupController.php
  src/bundle/ParamConverter/ContentInfoParamConverter.php
  src/bundle/ParamConverter/ObjectStateGroupParamConverter.php
  src/bundle/ParamConverter/ObjectStateParamConverter.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/config/services/menu.yml
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/object-state.svg
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/translations/object_state.en.xliff
  src/bundle/Resources/views/admin/object_state/add.html.twig
  src/bundle/Resources/views/admin/object_state/base.html.twig
  src/bundle/Resources/views/admin/object_state/edit.html.twig
  src/bundle/Resources/views/admin/object_state/list.html.twig
  src/bundle/Resources/views/admin/object_state/view.html.twig
  src/bundle/Resources/views/admin/object_state_group/add.html.twig
  src/bundle/Resources/views/admin/object_state_group/base.html.twig
  src/bundle/Resources/views/admin/object_state_group/edit.html.twig
  src/bundle/Resources/views/admin/object_state_group/list.html.twig
  src/bundle/Resources/views/admin/object_state_group/view.html.twig
  src/bundle/Resources/views/content/tab/details.html.twig
  src/lib/Form/Data/ObjectState/ContentObjectStateUpdateData.php
  src/lib/Form/Data/ObjectState/ObjectStateCreateData.php
  src/lib/Form/Data/ObjectState/ObjectStateDeleteData.php
  src/lib/Form/Data/ObjectState/ObjectStateGroupCreateData.php
  src/lib/Form/Data/ObjectState/ObjectStateGroupDeleteData.php
  src/lib/Form/Data/ObjectState/ObjectStateGroupUpdateData.php
  src/lib/Form/Data/ObjectState/ObjectStateGroupsDeleteData.php
  src/lib/Form/Data/ObjectState/ObjectStateUpdateData.php
  src/lib/Form/Data/ObjectState/ObjectStatesDeleteData.php
  src/lib/Form/DataTransformer/ObjectStateGroupTransformer.php
  src/lib/Form/DataTransformer/ObjectStateTransformer.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php
  src/lib/Form/Type/ObjectState/ObjectStateChoiceType.php
  src/lib/Form/Type/ObjectState/ObjectStateCreateType.php
  src/lib/Form/Type/ObjectState/ObjectStateDeleteType.php
  src/lib/Form/Type/ObjectState/ObjectStateGroupCreateType.php
  src/lib/Form/Type/ObjectState/ObjectStateGroupDeleteType.php
  src/lib/Form/Type/ObjectState/ObjectStateGroupType.php
  src/lib/Form/Type/ObjectState/ObjectStateGroupUpdateType.php
  src/lib/Form/Type/ObjectState/ObjectStateGroupsDeleteType.php
  src/lib/Form/Type/ObjectState/ObjectStateType.php
  src/lib/Form/Type/ObjectState/ObjectStateUpdateType.php
  src/lib/Form/Type/ObjectState/ObjectStatesDeleteType.php
  src/lib/Menu/Admin/ObjectState/ObjectStateCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateEditRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateGroupCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateGroupEditRightSidebarBuilder.php
  src/lib/Menu/Event/ConfigureMenuEvent.php
  src/lib/Menu/MainMenuBuilder.php
  src/lib/Tab/LocationView/DetailsTab.php
  src/lib/UI/Dataset/ObjectStatesDataset.php
Labels: enhancement, ready for QA, ready for review

#379 EZP-28937: Simplified filtered search
  src/bundle/Controller/SearchController.php
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/scss/_content-type-selector.scss
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/search.en.xliff
  src/bundle/Resources/views/admin/search/search.html.twig
  src/bundle/Resources/views/admin/search/search_form.html.twig
  src/bundle/Resources/views/form_fields.html.twig
  src/lib/Form/Data/Search/SearchData.php
  src/lib/Form/DataTransformer/DateIntervalTransformer.php
  src/lib/Form/Type/Search/DateIntervalType.php
  src/lib/Form/Type/Search/SearchType.php
Labels: enhancement

#380 EZP-28930: Labels are one line below checkbox/radiobutton
  src/bundle/Resources/views/admin/content_type/create.html.twig
  src/bundle/Resources/views/admin/content_type/edit.html.twig
  src/bundle/Resources/views/admin/language/create.html.twig
  src/bundle/Resources/views/admin/language/edit.html.twig
Labels: bug, ready for QA, ready for review

#370 EZP-28792: As an editor, I want to reset my forgotten password in Admin U.I.
  src/bundle/Controller/User/UserForgotPasswordController.php
  src/bundle/DependencyInjection/Configuration/Parser/Security.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/public/scss/_login.scss
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
  src/bundle/Resources/views/Security/base.html.twig
  src/bundle/Resources/views/Security/forgot_user_password/index.html.twig
  src/bundle/Resources/views/Security/forgot_user_password/success.html.twig
  src/bundle/Resources/views/Security/forgot_user_password/with_login.html.twig
  src/bundle/Resources/views/Security/form_fields.html.twig
  src/bundle/Resources/views/Security/login.html.twig
  src/bundle/Resources/views/Security/mail/forgot_user_password.html.twig
  src/bundle/Resources/views/Security/reset_user_password/index.html.twig
  src/bundle/Resources/views/Security/reset_user_password/invalid_link.html.twig
  src/bundle/Resources/views/Security/reset_user_password/success.html.twig
  src/lib/Form/Data/User/UserPasswordForgotData.php
  src/lib/Form/Data/User/UserPasswordForgotWithLoginData.php
  src/lib/Form/Data/User/UserPasswordResetData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/User/UserPasswordForgotType.php
  src/lib/Form/Type/User/UserPasswordForgotWithLoginType.php
  src/lib/Form/Type/User/UserPasswordResetType.php
Labels: ready for review

#377 EZP-28922: Design consistency for modals across the whole application
  src/bundle/Resources/public/scss/_add-translation.scss
Labels: QA done

#387 EZP-28931: Large values in Longitude of Map location
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
Labels: QA done, bug, ready for review

#393 EZP-28929: User is unable to add translation to Content item
  src/bundle/Controller/ContentEditController.php
Labels: QA done

#386 EZP-28874: Main Menu is not responsive under 992 pixels
  src/bundle/Resources/views/content/content_edit/content_create_draft.html.twig
  src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
  src/bundle/Resources/views/parts/navigation.html.twig
  src/lib/Behat/PageElement/UpperMenu.php
Labels: QA done, bug, ready for review

#390 EZP-28922: Modal Draft Conflict design consistency update
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/views/content/modal_draft_conflict.html.twig
Labels: ready for QA

#392 EZP-28859: Bad request after filling one coordinate from ezmaplocation
  src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
Labels: QA done, bug, ready for review

#396 EZP-28859: Bad request after filling one coordinate from ezmaplocation - obsolete code removal
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
Labels: QA done, enhancement, ready for merge

#391 EZP-28334: Fix for restoring from trash after removing structure of items.
  src/bundle/Resources/views/admin/trash/list.html.twig
  src/lib/Form/Data/TrashItemData.php
Labels: ready for review

#397 EZP-28947: Filtered search inconsistencies
  src/bundle/Controller/SearchController.php
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/scss/_content-type-selector.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/search.en.xliff
  src/bundle/Resources/views/admin/search/search_form.html.twig
  src/bundle/Resources/views/form_fields.html.twig
  src/lib/Form/Data/Search/SearchData.php
Labels: QA done, bug, ready for merge

#398 EZP-28957: Cannot open draft conflict modal when two jQuery are loaded
  src/bundle/Resources/public/js/scripts/admin.location.tab.js
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/js/scripts/admin.version.edit.conflict.js
  src/bundle/Resources/public/js/scripts/button.content.edit.js
  src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/versions/tab.html.twig
Labels: QA done, bug

#399 EZP-28941: OpenStreetMaps does not load over a secure HTTPS connection
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
Labels: QA done, bug, ready for merge

#394 EZP-28965: Modals Close button harmonization in AdminUI
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/views/admin/bulk_delete_confirmation_modal.html.twig
  src/bundle/Resources/views/admin/content_type/delete_confirmation_modal.html.twig
  src/bundle/Resources/views/admin/language/delete_confirmation_modal.html.twig
  src/bundle/Resources/views/admin/section/delete_confirmation_modal.html.twig
  src/bundle/Resources/views/admin/trash/empty_trash_confirmation_modal.html.twig
  src/bundle/Resources/views/bulk_delete_confirmation_modal.html.twig
  src/bundle/Resources/views/content/modal_draft_conflict.html.twig
  src/bundle/Resources/views/content/modal_location_trash.html.twig
  src/bundle/Resources/views/content/modal_user_delete.html.twig
  src/bundle/Resources/views/content/modal_version_conflict.html.twig
  src/bundle/Resources/views/content/tab/translations/modal_add_translation.html.twig
Labels: QA done, enhancement, ready for review

#395 EZP-28932: Broken empty option design after selecting it from ezselection fieldtype
  src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
  src/bundle/Resources/public/scss/fieldType/preview/_ezselection.scss
Labels: QA done, bug, ready for review

#400 EZP-28954: Label is one line below checkbox/radiobutton
  src/bundle/Resources/config/views.yml
  src/bundle/Resources/public/scss/_card.scss
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/views/admin/content_type/create.html.twig
  src/bundle/Resources/views/admin/content_type/edit.html.twig
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/admin/role_assignment/create.html.twig
Labels: QA done, bug, ready for review

#404 EZP-28416: [MapLocation] Problem with Address field
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
  src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
Labels: bug, ready for QA, ready for review

#401 EZP-28279: User cannot set max file size in Image field type
  src/bundle/Resources/views/fieldtypes/edit/ezimage.html.twig
Labels: QA done

#403 EZP-28682: Error 404 after fast double click
  src/bundle/Resources/public/js/scripts/admin.prevent.click.js
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/views/layout.html.twig
Labels: bug

#388 EZP-28386: Update Create & Edit design layout
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
  src/bundle/Resources/views/content/content_edit/component/preview_unavailable.html.twig
  src/bundle/Resources/views/content/content_edit/content_create.html.twig
  src/bundle/Resources/views/content/content_edit/content_edit.html.twig
  src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
  src/bundle/Resources/views/content/content_edit/user_create.html.twig
  src/bundle/Resources/views/content/content_edit/user_edit.html.twig
Labels: enhancement, ready for QA

#407 EZP-28968: Error when creating URL alias at root level
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/views/content/tab/url/checkbox.html.twig
  src/lib/Form/EventListener/BuildPathFromRootListener.php
  src/lib/Form/EventListener/DisableSiteRootCheckboxIfRootLocationListener.php
  src/lib/Form/Type/Content/CustomUrl/CustomUrlAddType.php
Labels: QA done

#402 EZP-28856: Toolbar from Richtext disappears
  src/bundle/Resources/public/js/alloyeditor/dist/ezHeadingConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezHeadingConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezParagraphConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezParagraphConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-heading.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-paragraph.js
Labels: QA done, bug, ready for review

#412 EZP-28984: Search filters modals design update
  src/bundle/Resources/public/scss/_modals.scss
Labels: QA done

#406 EZP-28945: User will be able to search for content items by just selecting the filters.
  src/bundle/Controller/SearchController.php
  src/lib/Form/Data/Search/SearchData.php
  src/lib/Form/Type/Search/SearchType.php
Labels: QA done, ready for review

#409 EZP-28982: Modal Send to trash content update
  src/bundle/Resources/public/scss/_card.scss
  src/bundle/Resources/views/admin/content_type/delete_confirmation_modal.html.twig
  src/bundle/Resources/views/bulk_delete_confirmation_modal.html.twig
Labels: QA done

#411 EZP-28362: Display Language name and not language code.
  src/bundle/Resources/config/services/ui_config/common.yml
  src/bundle/Resources/views/content/tab/urls.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/lib/UI/Config/Provider/Languages.php
Labels: QA done, ready for QA, ready for review

#419 EZP-28974: Misaligned label of "Default value/Multiple choice" checkbox
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
Labels: QA done, bug, ready for review

#420 EZP-29008: Number and language in the same line on Details tab of CI
  src/bundle/Resources/views/content/tab/details.html.twig
Labels: QA done, ready for review

#413 EZP-28939: Internal Server Error when saving unpublished Draft
  src/bundle/Controller/ContentController.php
  src/bundle/Resources/translations/content_edit.en.xliff
  src/bundle/Resources/views/content/content_edit/content_edit.html.twig
  src/bundle/Resources/views/content/content_preview.html.twig
  src/lib/Component/Content/PreviewUnavailableTwigComponent.php
  src/lib/Menu/ContentEditRightSidebarBuilder.php
  src/lib/RepositoryForms/Form/Processor/PreviewFormProcessor.php
  src/lib/RepositoryForms/View/ViewParametersListener.php
  src/lib/Siteaccess/SiteaccessResolver.php
  src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php
  src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php
Labels: QA done, bug, ready for review

#426 EZP-29010: Move Content on the Fly common configuration to root namespace od AdminUI config
  src/bundle/Resources/config/services/ui_config/common.yml
  src/bundle/Resources/views/content/tab/urls.html.twig
  src/bundle/Resources/views/content/tab/versions/table.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/lib/UI/Config/Provider/ContentTypes.php
  src/lib/UI/Config/Provider/Languages.php
  src/lib/UI/Config/Provider/Module/UniversalDiscoveryWidget.php
Labels: ready for QA, ready for review

#424 EZP-28803: Edit button in sections is not aligned to the right
  src/bundle/Resources/views/admin/section/view.html.twig
Labels: QA done, ready for review

#422 EZP-28181: Inconsistence with labels in content type specific view
  features/ContentType.feature
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/views/admin/content_type/view.html.twig
Labels: QA done, ready for review

#416 EZP-28998: Login screen design update
  src/bundle/Resources/public/img/ez-logo.svg
  src/bundle/Resources/public/scss/_login.scss
Labels: QA done, bug

#414 EZP-28915: Hardcoded Administrator in content edit details section
  src/bundle/Resources/views/content/content_edit/content_edit.html.twig
  src/bundle/Resources/views/content/content_edit/user_edit.html.twig
  src/lib/RepositoryForms/View/ViewParametersListener.php
  src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php
Labels: QA done, ready for review

#417 EZP-28999: Object state set button style update
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/views/content/tab/details.html.twig
Labels: bug

#415 EZEE-1907: Missing notification after publishing/sending for review/publishing in the future
  src/bundle/Resources/config/services/form_processors.yml
  src/bundle/Resources/translations/content_edit.en.xliff
  src/lib/RepositoryForms/Form/Processor/ContentEditNotificationFormProcessor.php
Labels: QA done, ready for review

#425 EZP-29019: "Send to trash" action should be disabled when user doesn't have sufficient permission
  src/lib/Menu/ContentRightSidebarBuilder.php
Labels: QA done

#418 EZP-28439: Related content is still displayed after it is moved to trash
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/fieldtypes/preview/ezobjectrelationlist_row.html.twig
Labels: QA done, ready for review
