Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-07, with the labels that each got.

#554 EZP-29375: Add style for blockquote in RichText
  src/bundle/Resources/public/scss/fieldType/edit/_ezrichtext.scss
Labels: QA done, enhancement, ready for review

#555 EZP-29254: Images embedded in RichText editor dissapear after undo
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-embed.js
Labels: QA done, bug

#562 EZP-29337: Change date and time formats
  composer.json
  features/ContentTypeFields.feature
  src/lib/Behat/PageElement/Fields/Date.php
  src/lib/Behat/PageElement/Fields/DateAndTime.php
  src/lib/Behat/PageElement/Fields/Time.php
Labels: ready for merge

#556 EZP-28890: Impl. extractor for *.js files
  composer.json
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/translation.yml
  src/lib/Translation/Extractor/JavaScriptFileVisitor.php
Labels: QA done

#512 EZP-29275 As a QA I want to cover scenarios of testing fields editing in content management
  features/ContentCreation.feature
  features/ContentTypeFields.feature
  src/lib/Behat/BusinessContext/ContentUpdateContext.php
  src/lib/Behat/BusinessContext/ContentViewContext.php
  src/lib/Behat/BusinessContext/NavigationContext.php
  src/lib/Behat/PageElement/ContentField.php
  src/lib/Behat/PageElement/DateAndTimePopup.php
  src/lib/Behat/PageElement/Fields/Checkbox.php
  src/lib/Behat/PageElement/Fields/ContentRelationMultiple.php
  src/lib/Behat/PageElement/Fields/ContentRelationSingle.php
  src/lib/Behat/PageElement/Fields/Date.php
  src/lib/Behat/PageElement/Fields/DateAndTime.php
  src/lib/Behat/PageElement/Fields/RichText.php
  src/lib/Behat/PageElement/Fields/Time.php
  src/lib/Behat/PageElement/PlatformElementFactory.php
  src/lib/Behat/PageElement/Tables/ContentRelationTable.php
  src/lib/Behat/PageElement/Tables/SubItemsTable.php
  src/lib/Behat/PageElement/UpdateForm.php
  src/lib/Behat/PageObject/ContentItemPage.php
Labels: ready for review

#567 EZP-29423: Lazy loading value of the admin_ui_config Twig global variable (CS)
  src/bundle/Templating/Twig/UiConfigExtension.php
  src/lib/UI/Config/ConfigWrapper.php
Labels: ready for merge

#566 EZP-29276 - As a QA I want to cover scenarios of testing media, binar…
  behat_suites.yml
  features/ContentTypeFields.feature
  src/lib/Behat/Helper/UtilityContext.php
  src/lib/Behat/PageElement/Fields/File.php
  src/lib/Behat/PageElement/Fields/Image.php
  src/lib/Behat/PageElement/Fields/Media.php
  src/lib/Behat/PageElement/PlatformElementFactory.php
  src/lib/Behat/TestFiles/binary1.txt.zip
  src/lib/Behat/TestFiles/binary2.txt.zip
  src/lib/Behat/TestFiles/image1.png.zip
  src/lib/Behat/TestFiles/image2.png.zip
  src/lib/Behat/TestFiles/video1.mp4.zip
  src/lib/Behat/TestFiles/video2.mp4.zip
Labels: ready for review

#565 EZP-29426: As a frontend developer I would like to convert size in pixels to rems with a function
  .prettierrc
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/public/scss/functions/_calculate.rem.scss
Labels: enhancement, ready for review

#569 EZP-29446: Broken pagination in Bookmarks list when is more than 25 elements
  src/bundle/Controller/BookmarkController.php
  src/lib/Pagination/Pagerfanta/BookmarkAdapter.php
  src/lib/UI/Dataset/BookmarksDataset.php
Labels: QA done, ready for review

#573 EZP-29449: Cannot read property 'innerHTML' of null on upload in ezimage, ezmedia & ezbinaryfile
  src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
  src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezimage.scss
  src/bundle/Resources/views/fieldtypes/edit/ezmedia.html.twig
Labels: QA done, ready for review

#568 Fix EZP-29433. Unauthorized exception user has no permission to read the parent location
  src/bundle/Resources/translations/content_url.en.xliff
  src/bundle/Resources/views/content/tab/url/modal_add_custom_url.html.twig
  src/lib/Tab/LocationView/UrlsTab.php
Labels: QA done

#581 EZP-29342: Deleting related object for ezobjectrelations field throws error 500
  src/bundle/Controller/ContentViewController.php
Labels: QA done, ready for review
