Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2018-12, with the labels that each got.

#633 EZP-29613: As a developer I want access ContentType on Content to avoid re-loading it
  composer.json
  src/bundle/Controller/ContentViewController.php
  src/bundle/Controller/LocationController.php
  src/bundle/Controller/SectionController.php
  src/bundle/Controller/TrashController.php
  src/lib/EventListener/ContentTranslateViewFilterParametersListener.php
  src/lib/Menu/ContentCreateRightSidebarBuilder.php
  src/lib/Specification/Location/IsContainer.php
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
  src/lib/Tab/LocationView/RelationsTab.php
  src/lib/Tests/Validator/Constraint/LocationIsContainerValidatorTest.php
  src/lib/UI/Config/Provider/User.php
  src/lib/UI/Dataset/ContentDraftsDataset.php
  src/lib/UI/Dataset/PoliciesDataset.php
  src/lib/UI/Dataset/RelationsDataset.php
  src/lib/UI/Dataset/RolesDataset.php
  src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php
  src/lib/UI/Value/ValueFactory.php
  src/lib/UniversalDiscovery/Event/Subscriber/SectionAssign.php
  src/lib/Validator/Constraints/LocationIsContainerValidator.php
  src/lib/View/Builder/ContentTranslateViewBuilder.php
  src/lib/View/Filter/ContentTranslateViewFilter.php
Labels: QA approved

#729 Added missing translations
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/search.en.xliff
Labels: Bug, Ready for QA, Ready for review

#714 EZEE-2303: Impl. RichText block
  src/bundle/Resources/config/services/forms.yml
  src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedUpdate.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedUpdate.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImage.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImage.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImageUpdate.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImageUpdate.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImageVariation.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImageVariation.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezToolbarAdd.js.map
  src/bundle/Resources/public/js/alloyeditor/src/base/ez-embeddiscovercontent.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-linkedit.js
  src/bundle/Resources/public/js/scripts/fieldType/alloyeditor/custom.tags.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
  src/bundle/Resources/public/js/scripts/fieldType/ezrichtext.js
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezrichtext.scss
  src/bundle/Resources/views/content/content_edit/parts/javascripts.html.twig
  src/bundle/Resources/views/form_fields.html.twig
  src/lib/Form/Extension/RichTextTypeExtension.php
  src/lib/UniversalDiscovery/Event/Subscriber/RichTextAllowedLanguages.php
Labels: Feature, QA approved, Ready for review

#732 EZP-29854: Cannot remove a selected item from custom dropdown
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
Labels: Bug, QA approved

#720 EZP-29825 Change form templates merge order to let me override form fragments
  src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
Labels: QA approved

#733 EZP-29855: Expose `pages` query param in Location View / Versions tab for implementing custom pagination
  src/bundle/Controller/ContentViewController.php
Labels: Improvement, QA approved

#734 EZP-29856: Expose form's data ContentCreateStruct in content create view
  src/bundle/Resources/views/content/content_edit/content_create.html.twig
  src/lib/RepositoryForms/View/ViewParametersListener.php
  src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php
Labels: Improvement, QA approved

#728 EZP-29848: Make existing AdminUI tabs extendable by allowing template path and parameters change
  src/bundle/Resources/config/services/tabs.yml
  src/bundle/Resources/views/content/tab/versions/tab.html.twig
  src/bundle/Resources/views/content/tab/versions/table.html.twig
  src/lib/Tab/AbstractEventDispatchingTab.php
  src/lib/Tab/Event/TabEvents.php
  src/lib/Tab/Event/TabViewRenderEvent.php
  src/lib/Tab/LocationView/ContentTab.php
  src/lib/Tab/LocationView/DetailsTab.php
  src/lib/Tab/LocationView/LocationsTab.php
  src/lib/Tab/LocationView/PoliciesTab.php
  src/lib/Tab/LocationView/RelationsTab.php
  src/lib/Tab/LocationView/RolesTab.php
  src/lib/Tab/LocationView/TranslationsTab.php
  src/lib/Tab/LocationView/UrlsTab.php
  src/lib/Tab/LocationView/VersionsTab.php
Labels: Improvement, QA approved

#736 EZP-29812: As an editor, I want to embed a content item within a block element
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedInline.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedInline.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomStyleConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomStyleConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomTagConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomTagConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedInlineConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedInlineConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezFormattedConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezFormattedConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezHeadingConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezHeadingConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezListConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezListConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezParagraphConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezParagraphConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginFocusBlock.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginFocusBlock.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginMoveElement.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginMoveElement.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginRemoveBlock.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginRemoveBlock.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezTableConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezTableConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embed.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embedinline.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-removeblock.js
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-embed.js
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-focus-block.js
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-move-element.js
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-remove-block.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-embed-inline.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-heading.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-list.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-paragraph.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-text.js
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
  src/bundle/Resources/public/scss/_mixins.scss
  webpack.config.js
Labels: Improvement, QA approved

#725 EZP-29744: Implement permissions for Content/Create in Sub-items table
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/views/content/locationview.html.twig
  src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php
Labels: QA approved, Ready for review

#739 EZP-29862: Trash button is disabled after using browser back button
  src/bundle/Resources/public/js/scripts/admin.trash.list.js
  src/bundle/Resources/public/js/scripts/button.state.radio.toggle.js
  src/bundle/Resources/public/js/scripts/button.state.toggle.js
Labels: Bug, QA approved, Ready for MERGE

#743 Fix Dashboard "Me" section selector
  src/lib/Behat/PageObject/DashboardPage.php
Labels: Ready for MERGE

#742 EZP-29714: Fix failing to detect disabled next button
  src/lib/Behat/PageElement/Pagination.php
Labels: Ready for MERGE

#737 EZEE-2305: Port PageBuilder tests to demo
  composer.json
  src/lib/Behat/Helper/TableNodeExtension.php
  src/lib/Behat/PageElement/DateAndTimePopup.php
  src/lib/Behat/PageElement/ElementFactory.php
  src/lib/Behat/PageObject/FolderPreview.php
  src/lib/Behat/PageObject/PageObjectFactory.php
  src/lib/Behat/PageObject/PreviewPage.php
  src/lib/Tests/Behat/ExtendedTableNodeTest.php
Labels: Ready for MERGE

#744 EZP-29863: Exclamation mark is misaligned for Selection validation
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
Labels: Bug, Ready for QA, Ready for review

#745 EZP-29884: Embed toolbar is visible after removing embed item.
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginRemoveBlock.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginRemoveBlock.js.map
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-remove-block.js
Labels: Bug, QA approved, Ready for MERGE

#731 EZP-29122: As a developer, I want to configure password policies in ezuser
  src/bundle/Controller/User/UserForgotPasswordController.php
  src/bundle/Controller/UserProfile/UserPasswordChangeController.php
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/User/UserPasswordChangeType.php
  src/lib/Form/Type/User/UserPasswordResetType.php
Labels: Feature, QA approved

#712 EZP-29747: As an editor, I want to see a list of content items impossible to delete
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/admin.notifications.js
  src/bundle/Resources/public/js/scripts/helpers/notification.helper.js
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/public/scss/_notifications.scss
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/translations/search.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/modal_location_bulk_action_failed.html.twig
  src/bundle/Resources/views/content/modal_location_bulk_action_failed_row.html.twig
Labels: Feature, QA approved, Ready for MERGE

#748 EZP-29889: Cannot set property 'disabled' of null error in console in Trash
  src/bundle/Resources/public/js/scripts/admin.trash.list.js
  src/bundle/Resources/public/js/scripts/button.state.radio.toggle.js
  src/bundle/Resources/public/js/scripts/button.state.toggle.js
Labels: Bug, QA approved, Ready for MERGE

#746 EZP-29882: Embed content item is not visible in edit mode in Rich Text Editor
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-embed.js
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
Labels: Bug, QA approved, Ready for review

#749 EZP-29898: Add workflow icon to Admin Interface
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/workflow.svg
Labels: Ready for review

#755 Fixed LocationsTransformerTest::testReverseTransformWithIds (v1.3)
  src/lib/Tests/Form/DataTransformer/LocationsTransformerTest.php
Labels: Bug

#754 EZP-29871: Error 500 after creating Content Item based on Content Type with ezuser
  src/lib/Specification/ContentType/ContentTypeIsUser.php
Labels: Bug, QA approved, Ready for review

#753 EZP-29738: Triple validation message for invalid email address
  src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
Labels: Bug, QA approved, Ready for review

#750 EZP-29897: Workflow state panel becomes unusable in the Content Edit, when its container is displayed below the fold
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
Labels: Bug, QA approved, Ready for review

#752 EZP-29877: Custom tags and nested table focus issue
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
  src/lib/Behat/PageElement/Fields/RichText.php
Labels: Bug

#758 EZP-29875: Facebook tag set focus issue
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnCustomTagUpdate.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnCustomTagUpdate.js.map
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-customtag-update.js
Labels: Bug, Ready for review

#756 EZP-29902: Admin UI - Locale is not correctly set
  src/lib/Behat/PageElement/Fields/Date.php
  src/lib/EventListener/RequestLocaleListener.php
Labels: Ready for QA, Ready for review

#677 EZP-29716: It is not possible to translate Admin UI footer
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/Security/base.html.twig
Labels: Ready for QA

#761 EZP-29919: Add 'approved' and 'rejected' icons
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/approved.svg
  src/bundle/Resources/public/img/icons/rejected.svg
Labels: Improvement, Ready for review

#759 EZP-29900: Validation of XML content failed when changing block styles in List block
  src/bundle/Resources/public/js/alloyeditor/dist/ezListConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezListConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-list.js
Labels: Bug, QA approved, Ready for review

#764 EZP-29911: Incorrect action attribute value in the translation remove form for content
  src/bundle/Resources/views/admin/content_type/tab/translations.html.twig
  src/bundle/Resources/views/content/tab/translations/tab.html.twig
Labels: Bug, QA approved

#763 EZP-29921: Add possibility to use icons with custom path in Sidebar menu
  src/bundle/Resources/views/parts/menu/sidebar_base.html.twig
Labels: Improvement, Ready for QA, Ready for review

#765 EZP-29923: Add unit tests to RequestLocaleListener
  src/lib/Tests/EventListener/RequestLocaleListenerTest.php
Labels: Ready for review

#767 EZP-29910: Image link icon disappears when I edit the content item
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
Labels: Bug, QA approved, Ready for review

#766 EZP-29917: Impossible to include custom tags, images, embed inside a custom tag (ezcontent)
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnCustomTagUpdate.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnCustomTagUpdate.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedInline.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedInline.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedUpdate.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedUpdate.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImage.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImage.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImageUpdate.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImageUpdate.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImageVariation.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImageVariation.js.map
  src/bundle/Resources/public/js/alloyeditor/src/base/ez-embeddiscovercontent.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-customtag-update.js
Labels: Bug, QA approved

#768 EZP-29904: Unable to select Base translation for a Content Item
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/translations/tab.html.twig
  src/bundle/Resources/views/layout.html.twig
Labels: Bug, Ready for QA, Ready for review

#762 EZP-28413: Empty username field after copying a user
  src/bundle/Resources/config/services/menu.yml
  src/lib/Menu/ContentRightSidebarBuilder.php
Labels: QA approved

#769 EZP-29935: Add Sub items limit value to User Preferences
  src/bundle/Resources/config/services/modules/subitems.yml
  src/bundle/Resources/config/services/user_settings.yml
  src/bundle/Resources/translations/user_settings.en.xliff
  src/lib/UI/Config/Provider/Module/SubItemsList.php
  src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php
  src/lib/UserSetting/Setting/SubitemsLimit.php
Labels: QA approved, Ready for review

#771 EZP-29933: Admin UI REST API listener considers 3rd party routes as REST routes
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/routing_rest.yml
  src/bundle/Resources/config/services/rest.yml
  src/lib/EventListener/ApiRequestListener.php
Labels: QA approved

#775 EZP-29890: Wrong translation form is opened after using browser back button
  src/bundle/Resources/public/js/scripts/admin.location.add.translation.js
Labels: Bug, QA approved

#773 EZP-29925: Content Type Translate in Edit mode is not based on browser's settings
  src/lib/View/Builder/ContentTranslateViewBuilder.php
  src/lib/View/Filter/ContentTranslateViewFilter.php
Labels: QA approved, Ready for MERGE

#772 EZP-29952: Injected user-preferred language into CT of Content View mode
  src/bundle/Controller/ContentViewController.php
Labels: Bug, QA approved, Ready for MERGE

#770 EZP-29932: As a Developer I want list of Languages based on User's browser settings
  src/bundle/ParamConverter/ContentTypeParamConverter.php
  src/bundle/Resources/config/services.yml
  src/lib/EventListener/RequestLocaleListener.php
  src/lib/Form/Type/ChoiceList/Loader/ContentTypeChoiceLoader.php
  src/lib/Tests/EventListener/RequestLocaleListenerTest.php
  src/lib/UI/Config/Provider/ContentTypeNames.php
  src/lib/UI/Config/Provider/ContentTypes.php
Labels: Feature, QA approved, Ready for MERGE

#777 EZP-29913: Missing disabled look and feel for some of the fields when translating Content Type
  src/bundle/Resources/public/scss/_general.scss
Labels: Bug, QA approved, Ready for review

#781 EZEE-2652: Cannot add Landing page translation via action bar button
  src/bundle/Resources/public/js/scripts/admin.location.add.translation.js
Labels: Bug
