Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-07, with the labels that each got.

#1029 EZP-30705: Removed deprecated SubtreeQuery class
  src/lib/Tab/Dashboard/SubtreeQuery.php
Labels: Improvement, Ready for review

#1030 EZP-30659: Cannot select image from repository in ImageAsset field
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
Labels: Bug, QA approved

#1031 EZP-30649: Browse field for image/media/file field types
  src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezimageasset.scss
Labels: Bug, QA approved

#1002 EZP-30595 [Behat] Element with selector: .c-select-content-button was not found
  src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
Labels: Ready for review

#1032 EZP-30640 [Behat] Invalid values are entered in text fields
  src/lib/Behat/PageElement/Fields/Keywords.php
  src/lib/Behat/PageElement/Fields/RichText.php
Labels: Ready for review

#1025 EZP-30701: Removed deprecated 'universal_discovery_widget_module.default_location_id' setting
  src/bundle/DependencyInjection/Configuration/Parser/Module/UniversalDiscoveryWidget.php
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/bundle/Resources/config/universal_discovery_widget.yaml
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Menu/LeftSidebarBuilder.php
  src/lib/UI/Config/Provider/Module/UniversalDiscoveryWidget.php
Labels: Improvement

#1033 EZP-30728: flattenArrayOfLimitationsForCurrentUser works incorect
  src/lib/Permission/PermissionChecker.php
Labels: QA approved

#1039 EZP-30697: Fixed adding RoleLimitation when policy has no limitation itself
  src/lib/Permission/PermissionChecker.php
  src/lib/Tests/Permission/PermissionCheckerTest.php
Labels: Bug, QA approved, Ready for MERGE

#1009 Update Twig namespaces
  src/bundle/Templating/Twig/ComponentExtension.php
  src/bundle/Templating/Twig/ContentTypeIconExtension.php
  src/bundle/Templating/Twig/PathStringExtension.php
  src/bundle/Templating/Twig/TabExtension.php
  src/bundle/Templating/Twig/UiConfigExtension.php
  src/bundle/Templating/Twig/UniversalDiscoveryExtension.php
Labels: QA approved, Ready for review

#1038 EZP-30724: Fixed message displayed when content type is locked
  src/bundle/Controller/ContentTypeController.php
Labels: Bug, QA approved, Ready for review

#1040 EZEE-2819: Changed permission subscriber to be run when create tab is present in UDW
  src/lib/Tests/UniversalDiscovery/Event/Subscriber/ContentCreateTest.php
  src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php
Labels: Bug, QA approved, Ready for review

#1044 EZP-30766: CSS might be not loaded when exception occurs in Twig
  src/bundle/Controller/SearchController.php
  src/bundle/Resources/views/admin/search/search_form.html.twig
  src/lib/EventListener/AdminExceptionListener.php
  src/lib/Form/Type/Search/SearchType.php
Labels: Bug, Ready for review
