Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-09, with the labels that each got.

#1075 EZP-30786: 'Cannot update notifications count' notification message
  src/bundle/Resources/public/js/scripts/admin.notifications.modal.js
Labels: Bug, QA approved

#1074 EZEE-2805: "Admin" tab is not the last one in AdminUI menu
  src/bundle/Resources/config/services/menu.yml
  src/lib/Menu/Admin/ReorderMenuListener.php
  src/lib/Menu/Listener/ReorderByOrderNumberListener.php
Labels: QA approved

#1072 EZP-30899: Change default CT sorting field from identifier to name in AdminUI
  src/bundle/Controller/ContentTypeController.php
  src/lib/Form/Type/ChoiceList/Loader/ContentTypeChoiceLoader.php
  src/lib/UI/Config/Provider/ContentTypes.php
Labels: Improvement, QA approved

#1070 EZP-30896: Use ContentType Provider instead of deprecated ContentTypeNames
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
  src/bundle/Resources/public/js/scripts/helpers/content.type.helper.js
  src/lib/UI/Config/Provider/ContentTypeNames.php
Labels: QA approved

#1079 EZP-30916: Delete content confirmation modal - button stays disabled
  src/bundle/Resources/public/js/scripts/button.state.checkbox.toggle.js
Labels: Bug, QA approved, Ready for review

#1076 EZP-30902: Remove deprecated view parameters
  src/bundle/Controller/LanguageController.php
  src/lib/EventListener/ContentTranslateViewFilterParametersListener.php
  src/lib/Tab/LocationView/ContentTab.php
  src/lib/UI/Config/Provider/DateFormat.php
  src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php
Labels: QA approved

#1080 EZP-30787: Change icon in Save button when in Admin panel User settings
  src/lib/Menu/Admin/Role/RoleAssignmentCreateRightSidebarBuilder.php
  src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
Labels: Bug, Improvement, QA approved

#1082 Bumped php-cs-fixer to ~2.15.3 and adjusted its configuration
  .php_cs
  composer.json
Labels: Bug

#1060 EZP-30797: As an administrator, I want to configure a password expiration for users
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/translations/fieldtypes_preview.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/Security/error/credentials_expired.html.twig
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
  src/lib/EventListener/CredentialsExpirationWarningListener.php
  src/lib/EventListener/CredentialsExpiredListener.php
Labels: Feature, QA approved

#1081 EZP-30491: Design fix for "Conflict when hiding content item" modal
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/content/modal_content_hide_confirmation.html.twig
Labels: Improvement, QA approved

#1087 EZP-30946: Empty space under sidebar menu
  src/bundle/Resources/public/scss/_admin.content-type-view.scss
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/ezplatform.scss
Labels: Improvement, QA approved

#1085 EZP-29973: Deleting content modal inconsistency
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/content/modal_location_trash_container.html.twig
  src/bundle/Resources/views/content/modal_location_trash_with_asset.html.twig
  src/bundle/Resources/views/content/modal_location_trash_with_single_asset.html.twig
Labels: Improvement, QA approved, Ready for MERGE

#1088 EZP-30947: Removed deprecated methods
  src/bundle/Controller/NotificationController.php
  src/bundle/Resources/config/routing.yaml
  src/lib/Form/Factory/FormFactory.php
Labels: Improvement, QA approved, Ready for MERGE

#1078 EZP-29618: Update user menu order and add icons
  src/bundle/Resources/public/js/scripts/admin.user.menu.js
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/_notifications-menu.scss
  src/bundle/Resources/public/scss/_user-menu.scss
  src/bundle/Resources/views/themes/admin/ui/menu/user_menu.html.twig
  src/lib/Menu/UserMenuBuilder.php
Labels: Improvement, QA approved

#1068 EZP-30884: Implement scenarios for Subtree editor
  .travis.yml
  behat_suites.yml
  features/personas/SubtreeEditor.feature
  src/lib/Behat/BusinessContext/ContentViewContext.php
  src/lib/Behat/BusinessContext/NavigationContext.php
  src/lib/Behat/BusinessContext/RightMenuContext.php
  src/lib/Behat/BusinessContext/UDWContext.php
  src/lib/Behat/PageElement/RightMenu.php
  src/lib/Behat/PageElement/UpperMenu.php
  src/lib/Behat/PageObject/ContentItemPage.php
Labels: Ready for MERGE

#1094 [Behat] Moved AdminUI features
  behat_suites.yml
  features/standard/Authentication.feature
  features/standard/ContentCreation.feature
  features/standard/ContentDraft.feature
  features/standard/ContentManagement.feature
  features/standard/ContentType.feature
  features/standard/ContentTypeFields.feature
  features/standard/ContentTypeGroup.feature
  features/standard/Languages.feature
  features/standard/ObjectStates.feature
  features/standard/Roles.feature
  features/standard/Sections.feature
  features/standard/SystemInfo.feature
  features/standard/Trash.feature
Labels: Ready for MERGE

#1090 EZP-30843: Tabs rendering moved to Components
  src/bundle/Resources/config/services/components.yaml
  src/bundle/Resources/config/services/dashboard.yaml
  src/bundle/Resources/config/services/tabs.yaml
  src/bundle/Resources/config/services/tabs/content_type.yaml
  src/bundle/Resources/config/services/tabs/locationview.yaml
  src/bundle/Resources/config/services/tabs/systeminfo.yaml
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content_type/index.html.twig
  src/bundle/Resources/views/themes/admin/system_info/info.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig
  src/lib/Component/TabsComponent.php
Labels: QA approved

#1093 EZP-30967: Cannot open View notifications modal on Safari
  src/bundle/Resources/public/scss/_user-menu.scss
Labels: Bug, QA approved
