Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-01, with the labels that each got.

#793 EZP-29779: [Safari] Nothing responds after using web browser back button
  src/bundle/Resources/views/layout.html.twig
Labels: Bug, Ready for MERGE

#787 EZP-29833 : Limiting "Content\Create" to Section disables "Publish" button
  src/lib/Menu/ContentCreateRightSidebarBuilder.php
Labels: Bug, QA approved

#786 ezdatetime displays selected date and timeon calendar after clearing the field
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
  src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
Labels: Bug, QA approved, Ready for MERGE

#791 EZP-29914: When translating the Content Type disable 'Select item' button for Content Relation (Single and Multi)
  src/bundle/Resources/views/admin/content_type/edit.html.twig
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
Labels: QA approved

#795 EZP-29993: As the eZ Platform developer I would like to use Sass compiler in the Admin UI modules styles
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/views/layout.html.twig
Labels: Improvement, QA approved

#794 EZP 30001 : Limiting "Content\Create" to Section disables "Create" button in COTF
  src/bundle/Controller/ContentOnTheFlyController.php
Labels: Bug, QA approved

#803 EZP-30011: Harmonized Embed icon in RTEditor with PBuilder Embed block icon
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedInline.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedInline.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedUpdate.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbedUpdate.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embed.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embedinline.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embedupdate.js
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
Labels: Bug, QA approved

#783 EZP-29970: As a Developer I'd like to order components & tabs in Admin UI
  src/bundle/DependencyInjection/Compiler/ComponentPass.php
  src/bundle/DependencyInjection/Compiler/TabPass.php
Labels: QA approved

#778 EZP-29821: Reduce API/SPI lookups in Admin UI
  src/bundle/Resources/config/services/ui_config/common.yml
  src/lib/Specification/ContentIsUser.php
  src/lib/UI/Config/Provider/ContentTypeNames.php
  src/lib/UI/Config/Provider/Languages.php
Labels: QA approved

#780 EZP-29967: Content Type name is not translated in AdminUI tables
  src/bundle/Controller/TrashController.php
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
  src/lib/UI/Value/ValueFactory.php
Labels: Bug, QA approved, Ready for review

#806 EZP-29200: Admin menu disappear when user is redirected from policy to limitations
  src/lib/Menu/MainMenuBuilder.php
Labels: QA approved, Ready for review

#801 EZP-28773: [v2] Issues with page scrolling during actions in rich text editor
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnEmbed.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImage.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnImage.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js.map
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embed.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-image.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-linkedit.js
Labels: Bug, Ready for MERGE

#790 EZP-29811: Content field definitions is misaligned while creating Content Type
  src/bundle/Resources/public/scss/_card.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/views/admin/content_type/create.html.twig
  src/bundle/Resources/views/admin/content_type/edit.html.twig
Labels: Bug, QA approved, Ready for MERGE

#807 Fix ported to 2.2 to prevent tests from failing
  src/lib/Tests/Form/DataTransformer/LocationsTransformerTest.php
Labels: Ready for review

#800 EZP-29168: Side and Context Menu bars styling improvements
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/_main-row.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/views/admin/base.html.twig
  src/bundle/Resources/views/admin/bookmark/list.html.twig
  src/bundle/Resources/views/admin/content_draft/list.html.twig
  src/bundle/Resources/views/admin/content_type_group/base.html.twig
  src/bundle/Resources/views/admin/language/base.html.twig
  src/bundle/Resources/views/admin/object_state/base.html.twig
  src/bundle/Resources/views/admin/object_state_group/base.html.twig
  src/bundle/Resources/views/admin/policy/base.html.twig
  src/bundle/Resources/views/admin/role/base.html.twig
  src/bundle/Resources/views/admin/role_assignment/base.html.twig
  src/bundle/Resources/views/admin/search/search.html.twig
  src/bundle/Resources/views/admin/section/base.html.twig
  src/bundle/Resources/views/admin/trash/list.html.twig
  src/bundle/Resources/views/content/content_edit/content_create_draft.html.twig
  src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/dashboard/dashboard.html.twig
  src/bundle/Resources/views/layout.html.twig
  src/bundle/Resources/views/parts/tab/content_type.html.twig
  src/lib/Behat/PageElement/Fields/Selection.php
Labels: Bug, QA approved

#810 EZP-30053: Dashboard header is not adjusted
  src/bundle/Resources/public/scss/_main-row.scss
Labels: Bug, QA approved, Ready for review

#799 EZP-29849: Allow user to remove location in subtree/location limitation (content/create)
  src/bundle/Resources/public/js/scripts/admin.limitation.pick.js
  src/bundle/Resources/public/js/scripts/udw/select.location.js
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/_tag.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/translations/universal_discovery_widget.en.xliff
  src/bundle/Resources/views/Limitation/udw_limitation_value.html.twig
  src/bundle/Resources/views/Limitation/udw_limitation_value_list_item.html.twig
  src/bundle/Resources/views/admin/search/search_form.html.twig
  src/bundle/Resources/views/parts/tag.html.twig
Labels: Feature, Improvement, QA approved, Ready for review

#813 EZP-30058: Swapped name and identifier fields in Section form
  src/bundle/Resources/views/admin/section/create.html.twig
  src/bundle/Resources/views/admin/section/update.html.twig
Labels: Bug, QA approved, Ready for MERGE

#804 EZP-29998: As a developer, I want to define icons for content types
  src/bundle/DependencyInjection/Configuration/Parser/ContentType.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/default_parameters.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/ui_config/common.yml
  src/bundle/Resources/public/js/scripts/helpers/content.type.helper.js
  src/bundle/Resources/views/layout.html.twig
  src/bundle/Templating/Twig/ContentTypeIconExtension.php
  src/lib/Tests/UI/Config/Service/ContentTypeIconResolverTest.php
  src/lib/UI/Config/Provider/ContentTypes.php
  src/lib/UI/Service/ContentTypeIconResolver.php
Labels: Feature, QA approved, Ready for MERGE

#814 EZP-30064: As an editor I would like to view a content tree in location view
  src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
  src/bundle/Resources/public/scss/_view-content.scss
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/layout.html.twig
  src/bundle/Resources/views/parts/tab/locationview.html.twig
Labels: Feature, Ready for review

#816 EZP-30024: Simplifies object states table
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/views/content/tab/details.html.twig
  src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php
Labels: Feature, QA approved, Ready for review

#820 EZP-30069: As an editor I would like to change manually the width of content tree panel
  src/bundle/Resources/public/scss/_view-content.scss
Labels: Feature, Ready for review

#808 EZP-29857: Unable to upload audio to Media field type
  src/bundle/Resources/views/fieldtypes/edit/ezmedia.html.twig
Labels: QA approved
