Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-10, with the labels that each got.

#1098 Fix regression in draft_list.html.twig
  src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig
Labels: Bug

#1095 EZP-30900: Added pagination to content's reverse relations
  src/bundle/Controller/ContentViewController.php
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/relations/tab.html.twig
  src/bundle/Resources/views/content/tab/relations/table_relations_reverse.html.twig
  src/lib/Pagination/Pagerfanta/ReverseRelationAdapter.php
  src/lib/Tab/LocationView/RelationsTab.php
  src/lib/UI/Dataset/DatasetFactory.php
  src/lib/UI/Dataset/RelationListDataset.php
  src/lib/UI/Dataset/ReverseRelationListDataset.php
  src/lib/UI/Value/Content/Relation.php
  src/lib/UI/Value/Content/RelationInterface.php
  src/lib/UI/Value/Content/UnauthorizedRelation.php
  src/lib/UI/Value/ValueFactory.php
Labels: Bug, QA approved

#1099 EZP-30983: As an Administrator, I want prevent users from reusing old password
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
Labels: QA approved

#1101 EZP-30985: Removed usage of deprecated event classes
  src/lib/EventListener/AdminExceptionListener.php
  src/lib/EventListener/RequestListener.php
  src/lib/EventListener/RequestLocaleListener.php
  src/lib/Tests/EventListener/RequestListenerTest.php
  src/lib/Tests/EventListener/RequestLocaleListenerTest.php
Labels: Improvement, Ready for QA

#1105 EZP-30959: Long URL overlaps "clear URL input" button in Online Editor
  src/bundle/Resources/public/scss/_alloyeditor-link-edit.scss
Labels: Bug, QA approved

#1106 Use Twig namespaces
  src/bundle/Resources/config/services.yaml
  src/lib/RepositoryForms/Form/Processor/Content/ContentOnTheFlyProcessor.php
  src/lib/Tab/Dashboard/MyDraftsTab.php
  src/lib/Translation/Extractor/JavaScriptFileVisitor.php
  src/lib/Translation/Extractor/NotificationTranslationExtractor.php
Labels: Improvement, Ready for MERGE

#1107 EZP-30819: Replace deprecated controller syntax
  src/bundle/Resources/config/views.yaml
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/index.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/view.html.twig
  src/bundle/Resources/views/themes/admin/section/view.html.twig
  src/bundle/Resources/views/themes/admin/user/role/index.html.twig
Labels: Improvement, QA approved

#1097 EZP-30376 [Travis] Implementing reporting tool to behat automated tests
  .travis.yml
  .travis/rsa_allure.enc
Labels: Ready for MERGE

#1111 EZP-31029: Adjust Role transformers to introduced type hints in RoleService
  src/lib/Form/DataTransformer/RoleAssignmentTransformer.php
  src/lib/Form/DataTransformer/RoleTransformer.php
  src/lib/Tests/Form/DataTransformer/RoleAssignmentTransformerTest.php
  src/lib/Tests/Form/DataTransformer/RoleTransformerTest.php
Labels: Improvement, QA approved

#1112 EZP-31052: Provided minimal support for CustomTag link attr. type
  composer.json
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-customtag-update.js
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-custom-tag-base.js
Labels: Bug, Improvement, QA approved

#1113 Add workflow scenarios
  features/personas/SubtreeEditor.feature
  features/standard/Authentication.feature
  src/lib/Behat/BusinessContext/AuthenticationContext.php
  src/lib/Behat/BusinessContext/NavigationContext.php
  src/lib/Behat/BusinessContext/UserNotificationContext.php
  src/lib/Behat/PageElement/PlatformElementFactory.php
  src/lib/Behat/PageElement/Tables/SimpleTable.php
  src/lib/Behat/PageElement/UpperMenu.php
  src/lib/Behat/PageElement/UserNotificationPopup.php
  src/lib/Behat/PageObject/DashboardPage.php
Labels: Ready for MERGE

#1110 EZP-30985: Replaced usage of deprecated transchoice Twig function
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/translations/draft_conflict.en.xliff
  src/bundle/Resources/views/themes/admin/content/modal/draft_conflict.html.twig
  src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
Labels: Improvement, Ready for MERGE
