Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-08, with the labels that each got.

#1022 EZP-30687: As a Maintainer I want to deprecated code in EzSystems\EzPlatformAdminUi\UserSetting be dropped
  composer.json
  src/bundle/Controller/User/UserForgotPasswordController.php
  src/bundle/Controller/User/UserSettingsController.php
  src/bundle/Controller/UserProfile/UserPasswordChangeController.php
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/config/services/user_settings.yaml
  src/lib/Form/Type/User/Setting/UserSettingUpdateType.php
  src/lib/Pagination/Pagerfanta/UserSettingsAdapter.php
  src/lib/UI/Config/Provider/DateFormat.php
  src/lib/UserSetting/FormMapperInterface.php
  src/lib/UserSetting/Setting/SubitemsLimit.php
  src/lib/UserSetting/Setting/Timezone.php
  src/lib/UserSetting/UserSetting.php
  src/lib/UserSetting/UserSettingService.php
  src/lib/UserSetting/ValueDefinitionInterface.php
Labels: Improvement, QA approved

#1050 Fixed _ezplatform_branch_for_behat_tests in composer.json
  composer.json
Labels: Bug

#1046 Added Behat debug info
  src/lib/Behat/Helper/Hooks.php
  src/lib/Behat/Helper/LogFileReader.php
Labels: Ready for MERGE

#1049 EZP-30814: Removed Twig deprecations
  src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
  src/bundle/Resources/views/content/content_view_fields.html.twig
  src/bundle/Resources/views/content/tab/policies/limitation_values.html.twig
  src/bundle/Resources/views/content/tab/roles/limitation_values.html.twig
  src/bundle/Resources/views/fieldtypes/edit/ezselection.html.twig
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
  src/bundle/Resources/views/parts/menu/top_menu.html.twig
Labels: Improvement, Ready for review

#1053 EZP-30820: AdminExceptionListener could not be autowired due to missing EncoreBundle definitions
  src/bundle/Resources/config/services.yml
  src/lib/EventListener/AdminExceptionListener.php
Labels: Bug, Ready for review

#1052 EZP-29386: Removed Admin service aliases in favor of Kernel
  src/bundle/Resources/config/services/service_aliases.yaml
Labels: QA approved

#1048 EZP-30812: Fixed deprecated use of Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch method
  src/bundle/Templating/Twig/TabExtension.php
  src/lib/Component/Renderer/DefaultRenderer.php
  src/lib/Menu/AbstractBuilder.php
  src/lib/Tab/AbstractEventDispatchingTab.php
  src/lib/UI/Action/EventDispatcher.php
  src/lib/UniversalDiscovery/ConfigResolver.php
Labels: Improvement, QA approved

#1051 EZP-30819: Removed deprecated controller references from routes definitions
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/routing_rest.yaml
Labels: Improvement, QA approved

#1054 EZP-30828: Replaced \Symfony\Component\EventDispatcher\Event usage in favor of Symfony\Contracts\EventDispatcher\Event
  src/lib/Component/Event/RenderGroupEvent.php
  src/lib/Component/Event/RenderSingleEvent.php
  src/lib/Menu/AbstractBuilder.php
  src/lib/Menu/Event/ConfigureMenuEvent.php
  src/lib/Tab/Event/TabEvent.php
  src/lib/Tab/Event/TabGroupEvent.php
  src/lib/Tab/Event/TabViewRenderEvent.php
  src/lib/UI/Action/UiActionEvent.php
  src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
Labels: Improvement, QA approved

#1043 EZP-30802: Fixed OE JS error in case of missing element path
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table-cell.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table-row.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/ez-add.js
Labels: Bug, QA approved, Ready for review

#1055 EZP-30844: Implemented getExtendedTypes method in Form Type Extensions
  src/bundle/Resources/config/services/forms.yaml
  src/lib/Form/Extension/RichTextTypeExtension.php
  src/lib/Form/Type/Extension/Content/ContentEditTypeExtension.php
Labels: Improvement, QA approved

#1056 EZP-30848: Fixed usage of hasAccess method with section/view permission in Admin UI
  src/lib/Form/Type/Search/SearchType.php
  src/lib/Menu/MainMenuBuilder.php
  src/lib/Tab/LocationView/DetailsTab.php
Labels: Bug, QA approved, Ready for MERGE

#1057 EZP-30853: The button "Add Section" has been hidden for a user which has Limitation to view Sections
  src/bundle/Controller/SectionController.php
  src/bundle/Resources/views/admin/section/list.html.twig
Labels: Bug, QA approved

#1059 EZP-30864: Handle removed content which is embed
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
  src/bundle/Resources/translations/alloy_editor.en.xliff
Labels: QA approved

#1065 Fixed unclosed element "a" in forgot user password e-mail template
  src/bundle/Resources/views/Security/mail/forgot_user_password.html.twig
Labels: Bug

#1067 EZP-30819: Removed deprecated controller reference syntax from account/notifications/modal.html.twig
  src/bundle/Resources/views/themes/admin/account/notifications/modal.html.twig
Labels: Improvement

#1047 EZP-30809: changed all default ezsettings to admin_group settings
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/ezplatform_default_settings.yaml
Labels: Improvement, QA approved, Ready for review

#1042 EZP-30792: Remove deprecated functions in JS
  src/bundle/Resources/public/js/scripts/admin.format.date.js
  src/bundle/Resources/public/js/scripts/helpers/timezone.helper.js
Labels: Improvement, QA approved

#1062 EZP-30880: Aligned MatcherFactory service definition with Kernel changes
  src/bundle/Resources/config/services/views.yaml
Labels: Improvement, QA approved

#1066 EZP-30888: Moved search query build logic from SearchController to dedicated QueryType
  src/bundle/Controller/SearchController.php
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/config/services/query_types.yaml
  src/lib/QueryType/SearchQueryType.php
  src/lib/Tests/QueryType/SearchQueryTypeTest.php
Labels: Improvement, QA approved

#1064 EZP-28997: Fixed issue with access to root of tree content and parent…
  src/bundle/Controller/ContentViewController.php
  src/lib/RepositoryForms/View/ViewParametersListener.php
  src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php
Labels: Bug, QA approved

#1073 EZP-30788: Harmonize Confirm button in widgets
  src/bundle/Resources/public/scss/_buttons.scss
Labels: Bug, QA approved, Ready for review
