Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-11, with the labels that each got.

#1127 EZP-31093: Introduced strict types for TrashService
  src/lib/Form/DataTransformer/TrashItemTransformer.php
Labels: Bug, QA approved

#1083 EZP-30320: As user I want to see container-adapting tabs collapsed into a dropdown
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js
  src/bundle/Resources/public/scss/_tabs.scss
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/views/themes/admin/ui/tab/location_view.html.twig
Labels: Feature, QA approved

#1132 EZP-31108: Fixed code-style according to the rules from ezplatform-code-style
  .php_cs
  composer.json
  src/bundle/Controller/ContentOnTheFlyController.php
  src/lib/Behat/PageElement/AdminUpdateForm.php
  src/lib/Behat/PageElement/ContentUpdateForm.php
  src/lib/Component/LinkComponent.php
  src/lib/Component/ScriptComponent.php
  src/lib/Form/Data/Location/LocationUpdateData.php
  src/lib/Form/Data/Section/SectionCreateData.php
  src/lib/Form/Data/Section/SectionUpdateData.php
  src/lib/Form/Factory/FormFactory.php
Labels: Improvement, Ready for review

#1133 EZP-31103: Introduced strict types for ContentTypeService
  src/lib/Form/DataTransformer/ContentTypeGroupTransformer.php
  src/lib/Tests/Form/DataTransformer/ContentTypeGroupTransformerTest.php
Labels: Bug, QA approved

#1100 EZP-30949: Introduced improved delete warning dialogs
  src/bundle/Controller/ContentViewController.php
  src/bundle/Controller/Location/TrashLocationWithAssetController.php
  src/bundle/Controller/LocationController.php
  src/bundle/Resources/config/services/forms.yml
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.trash.js
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/location.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/modal_location_trash.html.twig
  src/bundle/Resources/views/content/modal_location_trash_container.html.twig
  src/bundle/Resources/views/content/modal_location_trash_with_asset.html.twig
  src/bundle/Resources/views/content/modal_location_trash_with_single_asset.html.twig
  src/lib/Form/Data/Location/LocationTrashContainerData.php
  src/lib/Form/Data/Location/LocationTrashData.php
  src/lib/Form/Data/Location/LocationTrashWithAssetData.php
  src/lib/Form/Extension/HelpMultilineMessageExtension.php
  src/lib/Form/TrashLocationOptionProvider/HasAssetRelation.php
  src/lib/Form/TrashLocationOptionProvider/HasChildren.php
  src/lib/Form/TrashLocationOptionProvider/HasReverseRelations.php
  src/lib/Form/TrashLocationOptionProvider/HasUniqueAssetRelation.php
  src/lib/Form/TrashLocationOptionProvider/OptionsFactory.php
  src/lib/Form/TrashLocationOptionProvider/TrashLocationOptionProvider.php
  src/lib/Form/Type/Location/LocationTrashContainerType.php
  src/lib/Form/Type/Location/LocationTrashType.php
  src/lib/Form/Type/Location/LocationTrashWithAssetType.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Specification/Location/HasChildren.php
Labels: QA approved

#1141 EZP-31008: Changed to code style from EzPlatformInternalConfigFactory
  .php_cs
Labels: Bug, Ready for review

#1142 EZP-31108: Fixed invalid code-style
  src/lib/FieldType/Mapper/AuthorFormMapper.php
  src/lib/FieldType/Mapper/DateFormMapper.php
  src/lib/FieldType/Mapper/DateTimeFormMapper.php
  src/lib/FieldType/Mapper/MediaFormMapper.php
  src/lib/FieldType/Mapper/TimeFormMapper.php
  src/lib/Form/Type/ContentType/ContentTypeEditType.php
Labels: Bug, Ready for review

#1137 EZP-31058: No new line can be inserted in RTE below custom tags
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-custom-tag.js
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-custom-tag-base.js
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
Labels: Bug, QA approved

#1129 EZEE-2915: Implement minimal test coverage for Richtext block in Page Builder
  src/lib/Behat/PageElement/Fields/RichText.php
Labels: Ready for MERGE

#1140 EZP-31030: Introduced strict types for SectionService
  src/lib/Form/DataTransformer/SectionTransformer.php
  src/lib/Tests/Form/DataTransformer/SectionTransformerTest.php
Labels: Bug, QA approved

#1135 EZP-30918: Added RelationView to allow displaying restricted relation
  src/bundle/Controller/ContentController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/content/relation.html.twig
  src/bundle/Resources/views/content/relation_unauthorized.html.twig
  src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
Labels: Bug, QA approved

#1134 EZP-30936 Editing Content with a Translation after adding a required field to ContentType will fail with an error
  src/bundle/Controller/ContentController.php
Labels: QA approved

#1136 EZP-31021: Revised exception and command messages
  src/bundle/Controller/ContentController.php
  src/bundle/Controller/LocationController.php
  src/bundle/Controller/Version/VersionConflictController.php
  src/bundle/DependencyInjection/Compiler/ComponentPass.php
  src/bundle/DependencyInjection/Compiler/TabPass.php
  src/bundle/ParamConverter/ContentInfoParamConverter.php
  src/bundle/ParamConverter/ContentTypeGroupParamConverter.php
  src/bundle/ParamConverter/ContentTypeParamConverter.php
  src/bundle/ParamConverter/LanguageParamConverter.php
  src/bundle/ParamConverter/ObjectStateGroupParamConverter.php
  src/bundle/ParamConverter/ObjectStateParamConverter.php
  src/bundle/ParamConverter/PolicyDraftParamConverter.php
  src/bundle/ParamConverter/PolicyParamConverter.php
  src/bundle/ParamConverter/RoleAssignmentParamConverter.php
  src/bundle/ParamConverter/RoleParamConverter.php
  src/bundle/ParamConverter/SectionParamConverter.php
  src/bundle/ParamConverter/TranslationLanguageParamConverter.php
  src/bundle/Tests/DependencyInjection/Compiler/ComponentPassTest.php
  src/bundle/Tests/ParamConverter/ContentTypeGroupParamConverterTest.php
  src/bundle/Tests/ParamConverter/ContentTypeParamConverterTest.php
  src/bundle/Tests/ParamConverter/LanguageParamConverterTest.php
  src/bundle/Tests/ParamConverter/PolicyParamConverterTest.php
  src/bundle/Tests/ParamConverter/RoleAssignmentParamConverterTest.php
  src/bundle/Tests/ParamConverter/RoleParamConverterTest.php
  src/bundle/Tests/ParamConverter/SectionParamConverterTest.php
  src/lib/Behat/BusinessContext/ContentTypeContext.php
  src/lib/Behat/BusinessContext/DashboardContext.php
  src/lib/Behat/BusinessContext/ObjectStatesContext.php
  src/lib/Behat/BusinessContext/RolesContext.php
  src/lib/Behat/BusinessContext/SectionsContext.php
  src/lib/Behat/PageElement/Fields/ContentRelationSingle.php
  src/lib/Behat/PageElement/Fields/DefaultFieldElement.php
  src/lib/Behat/PageElement/Tables/SubItemsTable.php
  src/lib/Behat/PageElement/Tables/Table.php
  src/lib/Behat/PageElement/UserNotificationPopup.php
  src/lib/Behat/PageObject/PlatformPageObjectFactory.php
  src/lib/Behat/PageObject/SectionPage.php
  src/lib/Behat/PageObject/SystemInfoPage.php
  src/lib/Behat/PageObject/TrashPage.php
  src/lib/EventListener/RequestListener.php
  src/lib/EventListener/SetViewParametersListener.php
  src/lib/Form/DataTransformer/DateTimePickerTransformer.php
  src/lib/Form/DataTransformer/LanguageTransformer.php
  src/lib/Form/DataTransformer/VersionInfoTransformer.php
  src/lib/Service/Role/RoleService.php
  src/lib/Siteaccess/NonAdminSiteaccessResolver.php
  src/lib/Specification/Content/ContentHaveAssetRelation.php
  src/lib/Specification/Content/ContentHaveUniqueRelation.php
  src/lib/Specification/ContentType/ContentTypeIsUser.php
  src/lib/Specification/ContentType/ContentTypeIsUserGroup.php
  src/lib/Specification/SiteAccess/IsAdmin.php
  src/lib/Tab/TabGroup.php
  src/lib/Tab/TabRegistry.php
  src/lib/Tests/EventListener/RequestListenerTest.php
  src/lib/Tests/EventListener/RequestLocaleListenerTest.php
  src/lib/Tests/Specification/ContentType/ContentTypeIsUserTest.php
  src/lib/Tests/Tab/TabGroupTest.php
  src/lib/Tests/Tab/TabRegistryTest.php
  src/lib/Translation/Extractor/NotificationTranslationExtractor.php
  src/lib/View/Builder/ContentTranslateViewBuilder.php
Labels: Ready for MERGE

#1147 EZEE-2941: Added missing required argument when SiteAccess is constructed
  src/lib/EventListener/AdminExceptionListener.php
Labels: Bug, Ready for QA, Ready for review

#1146 Fix deprecation in HelpMultilineMessageExtension
  src/lib/Form/Extension/HelpMultilineMessageExtension.php
Labels: Bug
