Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-03, with the labels that each got.

#864 EZP-30192: Content Tree panel is partially visible when toggled
  src/bundle/Resources/public/scss/_view-content.scss
Labels: Bug, Ready for review

#861 EZP-30185: Expose ContentTree configuration to AdminUI
  src/bundle/DependencyInjection/Configuration/Parser/Module/ContentTree.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services/modules/content_tree.yml
  src/bundle/Resources/views/content/locationview.html.twig
  src/lib/UI/Config/Provider/Module/ContentTree.php
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Improvement, Ready for review

#867 Use pathString instead of locationId in ContentTree
  src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
  src/bundle/Resources/views/content/locationview.html.twig
Labels: Improvement, Ready for review

#868 EZP-30197: Missing default value for content_tree_module.tree_root_location_id setting
  src/bundle/DependencyInjection/Configuration/Parser/Module/ContentTree.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
Labels: Bug, Ready for MERGE

#860 EZP-30184: As an Editor I want to collapse/expand content preview
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.location.tooglecontentpreview.js
  src/bundle/Resources/public/scss/_field-group.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/content/content_view_fields.html.twig
  src/bundle/Resources/views/content/tab/content.html.twig
Labels: Feature, QA approved

#870 EZP-30209: Expose logged User ID to ContentTree
  src/bundle/Resources/views/content/locationview.html.twig
Labels: Improvement, Ready for review

#871 EZP-30205: As an editor I would like content tree to hold separate state for different users
  src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
Labels: Improvement, Ready for review

#865 EZP-30139: As an editor I want to hide and reveal a content item
  src/bundle/Controller/ContentController.php
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/hide.svg
  src/bundle/Resources/public/img/icons/reveal.svg
  src/bundle/Resources/public/js/scripts/sidebar/btn/content.hide.js
  src/bundle/Resources/public/js/scripts/sidebar/btn/content.reveal.js
  src/bundle/Resources/public/scss/_alerts.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/modal_content_hide_confirmation.html.twig
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
  src/lib/Form/Data/Content/ContentVisibilityUpdateData.php
  src/lib/Form/Type/Content/ContentVisibilityUpdateType.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Tab/LocationView/LocationsTab.php
Labels: Feature, QA approved, Ready for review

#873 fix: User Setting `character_counter` is not exposed in Twig
  src/bundle/Resources/views/fieldtypes/edit/ezrichtext.html.twig
  src/bundle/Templating/Twig/UserPreferencesGlobalExtension.php
Labels: Bug

#874 EZP-30220: CustomTagTest::testMapConfig fails in phpunit
  src/lib/Tests/UI/Config/Mapper/FieldType/RichText/CustomTagTest.php
Labels: Bug, Ready for review

#876 EZP-30224: Make `ez_user_settings` twig global load user settings dynamically
  src/bundle/Templating/Twig/UserPreferencesGlobalExtension.php
Labels: Improvement, Ready for review

#878 Moved Language setting to ezplatform-admin-ui to ezplatform-user
  src/bundle/DependencyInjection/Configuration/Parser/UserPreferences.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services/forms.yml
  src/bundle/Resources/config/services/user_settings.yml
  src/lib/Form/Type/ChoiceList/Loader/AvailableLocaleChoiceLoader.php
  src/lib/Tests/Form/Type/ChoiceList/Loader/AvailableLocaleChoiceLoaderTest.php
  src/lib/UserSetting/Setting/Language.php
Labels: Improvement

#846 EZP-30099: Define preferred user date format
  composer.json
  src/bundle/Resources/public/js/scripts/admin.format.date.js
  src/bundle/Resources/public/js/scripts/helpers/timezone.helper.js
  src/bundle/Resources/views/admin/content_draft/list.html.twig
  src/bundle/Resources/views/admin/content_type/list.html.twig
  src/bundle/Resources/views/admin/search/search_table_row.html.twig
  src/bundle/Resources/views/admin/systeminfo/composer.html.twig
  src/bundle/Resources/views/content/content_edit/content_edit.html.twig
  src/bundle/Resources/views/content/content_edit/user_edit.html.twig
  src/bundle/Resources/views/content/tab/details.html.twig
  src/bundle/Resources/views/content/tab/versions/table.html.twig
  src/bundle/Resources/views/dashboard/tab/all_content.html.twig
  src/bundle/Resources/views/dashboard/tab/all_media.html.twig
  src/bundle/Resources/views/dashboard/tab/my_content.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/dashboard/tab/my_media.html.twig
  src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
  src/bundle/Resources/views/fieldtypes/preview/ezobjectrelationlist_row.html.twig
  src/bundle/Resources/views/form_fields.html.twig
  src/bundle/Resources/views/link_manager/list.html.twig
  src/bundle/Resources/views/link_manager/view.html.twig
  src/bundle/Resources/views/notifications/notification_row.html.twig
  src/bundle/Resources/views/user/settings/update.html.twig
  src/lib/Pagination/Pagerfanta/UserSettingsAdapter.php
  src/lib/UI/Config/Provider/DateFormat.php
Labels: Feature, Ready for review

#880 EZP-30223: Collapse all button is not always displayed in Content Tree
  src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
Labels: Bug, QA approved

#881 EZP-30231: When resizing Content Tree text is accidentally selected
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/_view-content.scss
Labels: Bug, QA approved

#883 EZP-30241: Characters counter does not work when formatted style is used
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved, Ready for review

#884 EZP-30239: Characters counter is activated only after clicking on RTE in edit mode
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved, Ready for review

#882 EZP-30235: Editor can't add location if content/create limitations on ContentType of Parent are set
  src/lib/Tab/LocationView/LocationsTab.php
Labels: QA approved, Ready for review

#885 EZP-30242: Characters counter does not work properly with embed inline
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved, Ready for MERGE

#887 EZP-30258: [Content tree] After reloading tree is partially collapsed
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Bug, QA approved

#877 EZP-30214: Add Content Tree to Bookmarks, Trash & Search
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
  src/bundle/Resources/public/scss/_content-tree.scss
  src/bundle/Resources/public/scss/_main-row.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/views/admin/bookmark/list.html.twig
  src/bundle/Resources/views/admin/content_draft/list.html.twig
  src/bundle/Resources/views/admin/search/search.html.twig
  src/bundle/Resources/views/admin/search/search_form.html.twig
  src/bundle/Resources/views/admin/trash/list.html.twig
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/layout.html.twig
Labels: Bug, Ready for QA, Ready for review

#889 EZP-30251: Display the rendering of time & date when editing the Short/Long Date & Time format
  src/bundle/Controller/User/UserSettingsController.php
  src/bundle/Resources/config/views.yml
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.settings.datetimeformat.update.js
  src/bundle/Resources/translations/user_settings.en.xliff
  src/bundle/Resources/views/user/settings/update_datetime_format.html.twig
Labels: Bug, QA approved

#894 EZP-30164: After removing option from ezselection it it not possible to add more options
  src/bundle/Resources/public/js/scripts/admin.contenttype.selection.js
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
Labels: QA approved

#598 EZP-29279: Fix value displayed by the Date Field Type being affected by browser time zone
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
Labels: Ready for QA

#899 EZP-30287: Cannot add inline custom tag to table
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-inlinecustomtag-update.js
Labels: Bug, QA approved

#898 EZP-30175: Error when editing anchor in image
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnInlineCustomTag.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnInlineCustomTag.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnInlineCustomTagEdit.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnInlineCustomTagEdit.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnInlineCustomTagUpdate.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnInlineCustomTagUpdate.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezInlineCustomTagConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezInlineCustomTagConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-anchoredit.js
Labels: Bug, QA approved

#895 EZP-30114: As an editor, I want the online editor toolbar to be sticky to the top of the text area
  src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
  src/bundle/Resources/public/js/alloyeditor/dist/ezHeadingConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezHeadingConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezParagraphConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezParagraphConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base-fixed.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-heading.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-paragraph.js
Labels: QA approved

#897 EZP-30107: Name of Content Item is not updated after changing the main language
  composer.json
  src/bundle/Controller/ContentController.php
  src/lib/Form/Data/Content/Translation/MainTranslationUpdateData.php
  src/lib/Form/DataMapper/MainTranslationUpdateMapper.php
  src/lib/Form/DataTransformer/ContentTransformer.php
  src/lib/Form/Type/Content/ContentType.php
  src/lib/Form/Type/Content/Translation/MainTranslationUpdateType.php
  src/lib/Tab/LocationView/TranslationsTab.php
Labels: QA approved

#903 EZP-30179: Anchor to image not displayed when returning to editor
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
Labels: Bug, QA approved

#902 EZP-30307: After removing option from ezauthor it is not possible to add more
  src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
  src/bundle/Resources/views/fieldtypes/edit/ezauthor.html.twig
Labels: QA approved

#901 EZP-30297: Error when I try to add a translation for a user object
  src/lib/RepositoryForms/Data/ContentTranslationData.php
  src/lib/RepositoryForms/Data/Mapper/ContentTranslationMapper.php
Labels: Ready for QA, Ready for review

#906 EZP-30297: Error when I try to add a translation for a user object - fix tests
  src/lib/RepositoryForms/Data/ContentTranslationData.php
  src/lib/Tests/RepositoryForms/Data/Mapper/ContentTranslationMapperTest.php
Labels: Ready for review

#905 EZP-30291: Console error when adding link inside inline custom tag
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
Labels: Bug, QA approved

#886 EZEE-2716: Richtext block: tooltip for links can render in way that part of it won't be visible
  src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
Labels: Bug, Ready for QA

#904 EZEE-30310: SearchLimit UDW: UDW search limit configuration in YAML
  src/bundle/Resources/config/universal_discovery_widget.yml
  src/bundle/Templating/Twig/UniversalDiscoveryExtension.php
Labels: QA approved

#908 EZP-30308: User menu changes width depending on user name length
  src/bundle/Resources/public/scss/_user-menu.scss
Labels: Bug, QA approved, Ready for review

#892 EZEE-2533: Error HTTP 400 trying to preview Form during creation
  src/bundle/Resources/config/services/siteaccess.yml
  src/lib/Siteaccess/AbstractSiteaccessPreviewVoter.php
  src/lib/Siteaccess/AdminSiteaccessPreviewVoter.php
  src/lib/Siteaccess/SiteaccessPreviewVoterContext.php
  src/lib/Siteaccess/SiteaccessPreviewVoterInterface.php
  src/lib/Siteaccess/SiteaccessResolver.php
Labels: Bug, QA approved, Ready for review

#907 EZP-30176: Anchor icon changes position in table
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/ez-add.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved

#910 EZP-29291 remove "EZP-29291-excluded" tag
  features/ContentTypeFields.feature
Labels: Ready for review

#893 EZEE-2481: Time picker bases on system time ignoring time zone in user settings
  src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
  src/bundle/Resources/public/js/scripts/helpers/timezone.helper.js
  src/lib/Behat/PageElement/DateAndTimePopup.php
Labels: Bug, QA approved

#891 EZP-30230: [Content tree] Inconsistency when displaying hidden content items
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Bug, QA approved, Ready for review

#913 EZP-30206: Anchor icon is displayed even if anchor is not saved
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved

#912 EZP-30285: Focus is set to inline custom tag toolbar in edit mode
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-custom-tag.js
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-custom-tag-base.js
Labels: Bug, QA approved

#911 EZP-30286: Inline custom tag toolbar skips when moving cursor outside RTE
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
Labels: Bug, QA approved

#916 EZP-30219: Message displayed for content item visibility should be be…
  src/bundle/Resources/public/scss/_header.scss
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/parts/page_title.html.twig
Labels: Bug, QA approved, Ready for review

#915 EZP-30288: Inline custom tag does not work with formatted style
  src/bundle/Resources/public/scss/_custom-tag.scss
Labels: Bug, QA approved

#917 EZP-30178: Extra spaces added after placing anchor when formatted style is used
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-anchoredit.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved

#918 EZP-30233: Messages for content item visibility are not displayed for all scenarios
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
Labels: Bug, Feature, QA approved, Ready for review

#921 EZP-30312: Refresh Content Tree on location visibility change
  src/bundle/Resources/public/js/scripts/admin.location.visibility.js
Labels: Bug, Improvement, QA approved

#922 EZP-30304: Cannot change text position in RTE
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnBlockTextAlignCenter.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnBlockTextAlignCenter.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnBlockTextAlignJustify.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnBlockTextAlignJustify.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnBlockTextAlignLeft.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnBlockTextAlignLeft.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnBlockTextAlignRight.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnBlockTextAlignRight.js.map
  src/bundle/Resources/public/js/alloyeditor/src/base/ez-blocktextalign.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved

#923 EZP-29056: [Object States] Update notification for Object State Group and Object State contains Identifiers instead of Names
  features/ObjectStates.feature
  src/bundle/Controller/ObjectStateController.php
  src/bundle/Controller/ObjectStateGroupController.php
  src/bundle/Resources/translations/object_state.en.xliff
Labels: QA approved

#919 EZP-30177: Validation of XML content failed when adding two anchors w…
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-anchoredit.js
  src/bundle/Resources/public/scss/_alloyeditor-anchor-edit.scss
  src/bundle/Resources/translations/alloy_editor.en.xliff
Labels: Bug, QA approved

#924 EZP-30323: Copy Subtree does not use data-udw-config
  src/bundle/Resources/public/js/scripts/udw/copy_subtree.js
  src/lib/Menu/ContentRightSidebarBuilder.php
Labels: QA approved

#927 EZP-29752: Cannot Move Up/Down table in RichText Editor
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginMoveElement.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginMoveElement.js.map
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-move-element.js
Labels: Bug, QA approved

#925 EZP-30163: Icons are not aligned with other elements
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezkeyword.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
  src/bundle/Resources/views/fieldtypes/edit/ezgmaplocation.html.twig
  src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
Labels: Bug, QA approved, Ready for review

#920 EZP-30326: Expose search domain translations to the frontend
  src/bundle/Resources/config/bazinga_js_translation.yml
Labels: QA approved, Ready for review

#929 EZP-30329: [Chrome] Drag and drop does not work for ezfile, ezmedia, ezimage
  src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
Labels: Bug, QA approved, Ready for MERGE

#932 EZP-30342: Content tree should hold separate state for different users (opened/closed)
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
Labels: Bug, QA approved

#896 EZP-30229: Unlock Location visibility on hidden content
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
  src/lib/Tab/LocationView/LocationsTab.php
Labels: QA approved

#928 EZP-30359: Override Content Tree module root for Users, Media, Forms locations
  src/bundle/Controller/Content/ContentTreeController.php
  src/bundle/Controller/ContentViewController.php
  src/bundle/DependencyInjection/Configuration/Parser/Module/ContentTree.php
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
  src/bundle/Resources/views/layout.html.twig
  src/lib/UI/Config/Provider/Module/ContentTree.php
Labels: Feature, Improvement, Ready for review

#933 EZP-30362: Hidden default location in Relation List field type crashes Content Type editing
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
Labels: Ready for QA

#930 EZP-30346: Broken notifications with html
  src/bundle/Resources/public/js/scripts/admin.notifications.js
  src/bundle/Resources/public/js/scripts/helpers/notification.helper.js
Labels: QA approved, Ready for review

#909 EZP-30263 : User date format don't apply to date fields in content item update and preview
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
  src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
  src/bundle/Resources/public/js/scripts/fieldType/eztime.js
  src/bundle/Resources/public/js/scripts/helpers/timezone.helper.js
  src/bundle/Resources/translations/fieldtypes_preview.en.xliff
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
  src/lib/UI/Config/Provider/DateFormat.php
Labels: Bug, Feature, Ready for QA, Ready for review

#937 EZP-29754: Embed block is overwritten by Table in RichText Editor
  src/bundle/Resources/public/js/alloyeditor/dist/ezCoreTable.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezCoreTable.js.map
  src/bundle/Resources/public/js/alloyeditor/src/core/table.js
  webpack.config.js
Labels: Bug, QA approved

#939 EZP-29754: Embed block is overwritten by Table in RichText Editor
  src/bundle/Resources/encore/ez.js.config.js
Labels: Bug, QA approved

#935 EZP-30154: Allow UDW configuration decoupled from Content on the Fly
  src/bundle/Templating/Twig/UniversalDiscoveryExtension.php
  src/lib/UniversalDiscovery/Event/Subscriber/DecoupleContentOnTheFlyAllowedConfiguration.php
Labels: QA approved

#940 EZP-30154: Decouple Content on the Fly from browse & search by default
  src/bundle/Resources/config/universal_discovery_widget.yml
Labels: QA approved

#941 EZP-30375: User is unable to go to Content structure without Content/Reverserelatedlist
  src/bundle/Controller/ContentViewController.php
Labels: QA approved

#888 EZP-30269: [Content Tree] Collapse all button jumps a little bit when scrolling
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
Labels: Bug, Ready for review
