Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-02, with the labels that each got.

#821 EZP-30073: As an editor I would like to see a content tree button in the left sidebar
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/content-tree.svg
  src/bundle/Resources/translations/menu.en.xliff
  src/lib/Menu/LeftSidebarBuilder.php
Labels: Feature, Ready for review

#811 EZP-29320: As an Editor, I want to be able to switch content main tra…
  src/bundle/Controller/ContentController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/public/js/scripts/admin.main.translation.update.js
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/translations/tab.html.twig
  src/lib/Form/Data/Content/Translation/MainTranslationUpdateData.php
  src/lib/Form/DataMapper/MainTranslationUpdateMapper.php
  src/lib/Form/Type/Content/Translation/MainTranslationUpdateType.php
  src/lib/Tab/ContentType/TranslationsTab.php
  src/lib/Tab/LocationView/TranslationsTab.php
  src/lib/UI/Value/Content/Language.php
  src/lib/UI/Value/ValueFactory.php
Labels: Feature, QA approved, Ready for review

#826 EZP-30090: As an editor I would like content tree panel staying opened until clicking on a Content Tree button again
  src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/_view-content.scss
  src/lib/Menu/LeftSidebarBuilder.php
Labels: Feature, Ready for review

#828 EZP-30103: Missing asterisks from obligatory fields in Admin menu
  src/bundle/Resources/public/scss/_labels.scss
Labels: QA approved, Ready for review

#829 EZP-30109: Add autofocus attribute to creation forms in the Admin section
  src/bundle/Resources/views/admin/content_type/create.html.twig
  src/bundle/Resources/views/admin/content_type_group/create.html.twig
  src/bundle/Resources/views/admin/language/create.html.twig
  src/bundle/Resources/views/admin/object_state/add.html.twig
  src/bundle/Resources/views/admin/object_state_group/add.html.twig
  src/bundle/Resources/views/admin/policy/add.html.twig
  src/bundle/Resources/views/admin/role/add.html.twig
  src/bundle/Resources/views/admin/section/create.html.twig
Labels: QA approved, Ready for review

#805 EZP-29999: As an editor, I want to see custom icons for content types
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/scss/_extra-actions.scss
  src/bundle/Resources/public/scss/_instant-filter.scss
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/views/admin/bookmark/list.html.twig
  src/bundle/Resources/views/admin/content_draft/list.html.twig
  src/bundle/Resources/views/admin/content_type/edit.html.twig
  src/bundle/Resources/views/admin/content_type/list.html.twig
  src/bundle/Resources/views/admin/search/search.html.twig
  src/bundle/Resources/views/admin/search/search_table_row.html.twig
  src/bundle/Resources/views/admin/trash/list.html.twig
  src/bundle/Resources/views/content/content_edit/content_create.html.twig
  src/bundle/Resources/views/content/content_edit/content_edit.html.twig
  src/bundle/Resources/views/content/content_edit/user_create.html.twig
  src/bundle/Resources/views/content/content_edit/user_edit.html.twig
  src/bundle/Resources/views/dashboard/tab/all_content.html.twig
  src/bundle/Resources/views/dashboard/tab/all_media.html.twig
  src/bundle/Resources/views/dashboard/tab/my_content.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/dashboard/tab/my_media.html.twig
  src/bundle/Resources/views/form_fields.html.twig
  src/bundle/Resources/views/parts/page_title.html.twig
  src/bundle/Resources/views/parts/tab/content_type.html.twig
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
  src/lib/UI/Config/Provider/ContentTypes.php
  src/lib/UI/Dataset/ContentDraftsDataset.php
Labels: Improvement, Ready for review

#774 [2.5] EZP-29961: Add preferred language value to User Preferences
  src/bundle/DependencyInjection/Configuration/Parser/UserPreferences.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services/forms.yml
  src/bundle/Resources/config/services/user_settings.yml
  src/bundle/Resources/translations/user_settings.en.xliff
  src/lib/EventListener/RequestLocaleListener.php
  src/lib/Form/Type/ChoiceList/Loader/AvailableLocaleChoiceLoader.php
  src/lib/Tests/EventListener/RequestLocaleListenerTest.php
  src/lib/Tests/Form/Type/ChoiceList/Loader/AvailableLocaleChoiceLoaderTest.php
  src/lib/UserSetting/Setting/Language.php
Labels: QA approved, Ready for review

#834 EZP-30119: Fix database error on cache clear command when database is not configured
  src/lib/UserSetting/Setting/Language.php
Labels: Ready for review

#837 EZP-30124: Right sidebar menu is broken when editing link in Link manager
  src/bundle/Resources/views/link_manager/edit.html.twig
Labels: Bug, QA approved, Ready for review

#838 EZP-30125: Error page is displayed with right sidebar
  src/bundle/Resources/public/scss/_main-row.scss
  src/bundle/Resources/views/errors/403.html.twig
  src/bundle/Resources/views/errors/404.html.twig
  src/bundle/Resources/views/errors/error.html.twig
Labels: Bug, QA approved, Ready for review

#835 EZP-29410: As an Editor I want to be informed that I can't edit CI because of missing policies.
  src/bundle/Controller/Content/VersionDraftConflictController.php
  src/bundle/Resources/public/js/scripts/button.content.edit.js
  src/bundle/Resources/translations/content.en.xliff
Labels: QA approved, Ready for QA, Ready for review

#839 EZP-30102: updated ezselection field type
  src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
  src/bundle/Resources/public/scss/fieldType/preview/_ezselection.scss
Labels: Bug, QA approved

#833 EZP-30032: CustomTags not saved correctly
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnCustomTagUpdate.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginCustomTag.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezPluginCustomTag.js.map
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-custom-tag.js
Labels: Bug, QA approved

#830 [Travis] Move Varnish/Redis jobs to nightly jobs
  .travis.yml
Labels: Ready for MERGE

#825 EZP-30096: Solr scoring is not taken into account in the backend search results list order
  src/bundle/Controller/SearchController.php
Labels: Bug, QA approved

#844 [Backported] EZP-29856: Expose form's data ContentCreateStruct in content create view
  src/bundle/Resources/views/content/content_edit/content_create.html.twig
  src/lib/RepositoryForms/View/ViewParametersListener.php
  src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php
Labels: QA approved, Ready for review

#836 EZP-30066: As an editor I would like to see current location marked as selected in the content tree
  src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
  src/bundle/Resources/views/content/locationview.html.twig
Labels: Improvement, Ready for review

#843 [Doc] Created more detailed README.md
  README.md
Labels: Improvement, Ready for MERGE

#848 EZP-30007: Link to another page is not saved in Richtext
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js.map
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-linkedit.js
Labels: Bug, QA approved, Ready for review

#847 EZP-30100: As an Editor I want to change Object States with dropdowns instead of Set buttons
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.form.autosubmit.js
  src/bundle/Resources/translations/object_state.en.xliff
  src/bundle/Resources/views/content/tab/details.html.twig
  src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php
Labels: Feature, QA approved, Ready for review

#850 EZP-30156: eZ logo is not aligned with other entries in the main menu…
  src/bundle/Resources/public/scss/_main-nav.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss
  src/bundle/Resources/public/scss/fieldType/preview/_ezimage.scss
  src/bundle/Resources/public/scss/fieldType/preview/_ezimageasset.scss
Labels: QA approved, Ready for QA

#824 EZP-29990: As an Administrator I want to translate ezselection Field Definition options
  src/bundle/Controller/ContentTypeController.php
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
Labels: QA approved

#851 EZP-30162: Revert BC broken in EZP-30100
  src/bundle/Resources/translations/object_state.en.xliff
  src/bundle/Resources/views/content/tab/details.html.twig
  src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php
Labels: Improvement, QA approved, Ready for review

#849 EZP-30158: As an Editor I want to assign Section or set sorting order…
  src/bundle/Resources/views/content/tab/details.html.twig
Labels: Feature, Ready for QA, Ready for review

#852 Removed extra space from the end of the 'tab.details.change_section' translation key
  src/bundle/Resources/views/content/tab/details.html.twig
Labels: Bug

#831 EZP-29280: As an editor, I want to add anchors to RichText content
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/link-anchor.svg
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnAnchor.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnAnchor.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnAnchorEdit.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnAnchorEdit.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezBtnLinkEdit.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomStyleConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomStyleConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomTagConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomTagConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedImageConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezEmbedImageConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezFormattedConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezFormattedConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezHeadingConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezHeadingConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezListConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezListConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezParagraphConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezParagraphConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/dist/ezTableConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezTableConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-anchor.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-anchoredit.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-linkedit.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-custom-style.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-custom-tag.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-embed.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-formatted.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-heading.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-image.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-list.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-paragraph.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
  src/bundle/Resources/public/scss/_alloyeditor-anchor-edit.scss
  src/bundle/Resources/public/scss/_alloyeditor-buttons.scss
  src/bundle/Resources/public/scss/_custom-tag.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/alloyeditor.scss
  src/bundle/Resources/translations/alloy_editor.en.xliff
  webpack.config.js
Labels: Feature

#853 EZP-30172: Cannot edit Content Type with ezobjectrelation/ezobjectrelationlist with deleted starting location
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
Labels: Bug, QA approved, Ready for MERGE

#854 EZP-30065: As an editor I would like content tree to use real data
  src/bundle/Controller/Content/ContentTreeController.php
  src/bundle/DependencyInjection/Configuration/Parser/Module/ContentTree.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/routing_rest.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/config/services/modules/content_tree.yml
  src/bundle/Resources/config/services/rest.yml
  src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequest.php
  src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequestNode.php
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/Node.php
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/Root.php
  src/lib/REST/Value/ContentTree/LoadSubtreeRequest.php
  src/lib/REST/Value/ContentTree/LoadSubtreeRequestNode.php
  src/lib/REST/Value/ContentTree/Node.php
  src/lib/REST/Value/ContentTree/Root.php
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Feature, Ready for review

#827 EZP-29539 : Deleting object will remove all subtree items even when user does not have permission to delete them
  src/bundle/Controller/LocationController.php
Labels: Bug, Ready for QA, Ready for review

#855 EZP-30065: Fixed service definitions for ContentTree Input Parsers
  src/bundle/Resources/config/services/rest.yml
Labels: Bug, Ready for MERGE

#856 EZP-30182: ContentTree/loadSubitems action is not respecting offset value
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Bug, Ready for review

#840 EZP-30071: As an editor I would like to see tables not breaking location view design while making its container small
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/public/scss/_view-content.scss
  src/bundle/Resources/public/scss/fieldType/preview/_ezgmaplocation.scss
  src/bundle/Resources/public/scss/fieldType/preview/_ezimage.scss
  src/bundle/Resources/public/scss/fieldType/preview/_ezimageasset.scss
  src/bundle/Resources/public/scss/fieldType/preview/_ezmedia.scss
  src/bundle/Resources/public/scss/mixins/_image-preview.scss
  src/bundle/Resources/views/content/tab/details.html.twig
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
  src/bundle/Resources/views/content/tab/policies/table.html.twig
  src/bundle/Resources/views/content/tab/relations/table_relations.html.twig
  src/bundle/Resources/views/content/tab/relations/table_relations_reverse.html.twig
  src/bundle/Resources/views/content/tab/roles/table.html.twig
  src/bundle/Resources/views/content/tab/translations/tab.html.twig
  src/bundle/Resources/views/content/tab/url/custom_urls_table.html.twig
  src/bundle/Resources/views/content/tab/url/system_urls_table.html.twig
  src/bundle/Resources/views/content/tab/versions/table.html.twig
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
  src/bundle/Resources/views/fieldtypes/preview/ezimageasset.html.twig
  src/lib/Behat/PageElement/Fields/Image.php
Labels: Improvement, QA approved, Ready for MERGE, Ready for review

#857 EZP-30072: As an editor I would like to see the content tree state restored after reloading a page
  src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
  src/bundle/Resources/public/scss/_view-content.scss
  src/bundle/Resources/views/content/locationview.html.twig
Labels: Feature, Ready for review

#858 EZP-20181: Editor is not able to select any item in the ezobjectrelation/ezobjectrelationlist FTs if starting location is not accessible
  src/bundle/Resources/views/fieldtypes/edit/ezobjectrelation.html.twig
  src/bundle/Resources/views/fieldtypes/edit/ezobjectrelationlist.html.twig
Labels: Bug, QA approved, Ready for MERGE
