Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-04, with the labels that each got.

#947 EZP-29808: Newly created content via Multi Upload has wrong language set
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/views/content/locationview.html.twig
Labels: Bug, QA approved

#936 EZP-30367: Error: `Location cannot be displayed as it is flagged as invisible.`
  src/lib/EventListener/RequestAttributesListener.php
Labels: Ready for QA

#944 EZEE-2747 Implement minimal test coverage for Copy subtree
  features/ContentCreation.feature
  features/Sections.feature
  src/lib/Behat/BusinessContext/ContentViewContext.php
Labels: Ready for MERGE

#949 EZP-29963: In rich text editor, inline style in table triggers a javascript error
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomStyleConfig.js
  src/bundle/Resources/public/js/alloyeditor/dist/ezCustomStyleConfig.js.map
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-custom-style.js
Labels: Bug, QA approved

#951 EZEE-2749: Long message not displayed correctly on Notifications pop-up
  src/bundle/Resources/public/scss/_notifications-modal.scss
Labels: Bug, QA approved

#954 EZP-30425: Content view is shrunk - Remove redundant div added during merge-up
  src/bundle/Resources/views/content/locationview.html.twig
Labels: Bug, Ready for review

#948 EZP-30399: Fix lang attribute on <html> element
  src/bundle/Resources/views/layout.html.twig
Labels: Bug, QA approved, Ready for review

#957 EZEE-2736 [Travis][Behat] Non-deterministic errors in Form- and Page-Builders
  src/lib/Behat/PageElement/DateAndTimePopup.php
Labels: Bug, Ready for MERGE

#955 Add php-cs-fixer Travis job
  .travis.yml
Labels: Ready for MERGE

#959 EZEE-2747 Implement minimal test coverage for Copy subtree
  features/ContentCreation.feature
  features/Sections.feature
Labels: Ready for review

#812 EZP-30098 [Travis] Implement solution for running tests in threads based on fastest
  .travis.yml
  behat_suites.yml
  composer.json
  features/ContentCreation.feature
  features/ContentDraft.feature
  features/ContentManagement.feature
  src/lib/Behat/PageElement/Tables/SubItemsTable.php
  src/lib/Behat/PageElement/Tables/Table.php
  src/lib/Behat/PageObject/ContentItemPage.php
Labels: Ready for QA, Ready for review

#960 EZP-30454: Broken table in notifications modal when notification list is empty
  src/bundle/Resources/views/notifications/notifications_modal_body.html.twig
Labels: Bug, QA approved

#972 EZP-30471: Sending Relation to trash will crash Relating Content view in Back Office
  src/bundle/Controller/ContentViewController.php
Labels: Bug, QA approved

#953 EZP 29094: Cannot create user from Content on the Fly
  src/bundle/Controller/ContentOnTheFlyController.php
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/views/content/content_on_the_fly/content_create_on_the_fly.html.twig
  src/bundle/Resources/views/content/content_on_the_fly/create_on_the_fly.html.twig
  src/bundle/Resources/views/content/content_on_the_fly/user_create_on_the_fly.html.twig
  src/bundle/Resources/views/fieldtypes/preview/ezobjectrelationlist_row.html.twig
  src/lib/RepositoryForms/Dispatcher/UserOnTheFlyDispatcher.php
  src/lib/RepositoryForms/Form/Processor/User/UserOnTheFlyProcessor.php
  src/lib/UI/Config/Provider/FieldType/RichText/AlloyEditor.php
Labels: Bug, Ready for QA

#952 EZEE-2692: Buttons are in different order while user doesn't have Content/Publish policy
  src/lib/Menu/Admin/ReorderMenuListener.php
  src/lib/Menu/ContentCreateRightSidebarBuilder.php
  src/lib/Menu/ContentEditRightSidebarBuilder.php
Labels: Bug, QA approved

#934 EZP-30344: Improved handling Language Limitation
  src/bundle/Controller/ContentController.php
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/config/bazinga_js_translation.yml
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services/permissions.yml
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/admin.version.edit.conflict.js
  src/bundle/Resources/public/js/scripts/button.content.edit.js
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/views/admin/content_draft/list.html.twig
  src/bundle/Resources/views/content/tab/versions/table.html.twig
  src/bundle/Resources/views/dashboard/macros.html.twig
  src/bundle/Resources/views/dashboard/tab/all_content.html.twig
  src/bundle/Resources/views/dashboard/tab/all_media.html.twig
  src/bundle/Resources/views/dashboard/tab/my_content.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/dashboard/tab/my_media.html.twig
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/ChoiceList/Loader/ContentEditTranslationChoiceLoader.php
  src/lib/Form/Type/Content/Draft/ContentEditType.php
  src/lib/Form/Type/Content/Translation/TranslationAddType.php
  src/lib/Menu/ContentEditRightSidebarBuilder.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Permission/LookupLimitationsTransformer.php
  src/lib/Tab/LocationView/TranslationsTab.php
Labels: Improvement, QA approved

#977 EZP-30489: Get console logs in failed tests
  src/lib/Behat/Helper/Hooks.php
Labels: Ready for MERGE
