Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-12, with the labels that each got.

#1063 EZP-29112 Implement scenarios for Site Access matching
  src/lib/Behat/Helper/UtilityContext.php
  src/lib/Behat/PageObject/AdminUpdateItemPage.php
  src/lib/Behat/PageObject/ContentItemPage.php
  src/lib/Behat/PageObject/ContentPreviewPage.php
  src/lib/Behat/PageObject/ContentTypeGroupPage.php
  src/lib/Behat/PageObject/ContentTypeGroupsPage.php
  src/lib/Behat/PageObject/ContentTypePage.php
  src/lib/Behat/PageObject/ContentUpdateItemPage.php
  src/lib/Behat/PageObject/DashboardPage.php
  src/lib/Behat/PageObject/LanguagePage.php
  src/lib/Behat/PageObject/LanguagesPage.php
  src/lib/Behat/PageObject/LoginPage.php
  src/lib/Behat/PageObject/ObjectStateGroupPage.php
  src/lib/Behat/PageObject/ObjectStateGroupsPage.php
  src/lib/Behat/PageObject/ObjectStatePage.php
  src/lib/Behat/PageObject/Page.php
  src/lib/Behat/PageObject/RolePage.php
  src/lib/Behat/PageObject/RolesPage.php
  src/lib/Behat/PageObject/SectionPage.php
  src/lib/Behat/PageObject/SectionsPage.php
  src/lib/Behat/PageObject/SystemInfoPage.php
  src/lib/Behat/PageObject/TrashPage.php
Labels: Ready for MERGE

#1150 EZP-29112 Implement scenarios for Studio site access matching - followup fix
  src/lib/Behat/Helper/UtilityContext.php
Labels: Ready for review

#1153 EZP-31021: Merged repository-forms exception & command messages refactoring
  src/bundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPass.php
  src/bundle/DependencyInjection/Compiler/LimitationFormMapperPass.php
  src/bundle/DependencyInjection/Compiler/LimitationValueMapperPass.php
  src/lib/Form/DataTransformer/DateIntervalToArrayTransformer.php
  src/lib/Form/DataTransformer/FieldType/AbstractBinaryBaseTransformer.php
  src/lib/Form/DataTransformer/FieldType/DateTimeValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/DateValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/ImageAssetValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/TimeValueTransformer.php
  src/lib/Form/Processor/ContentType/ContentTypeFormProcessor.php
  src/lib/Limitation/Mapper/ContentTypeLimitationMapper.php
  src/lib/Limitation/Mapper/LanguageLimitationMapper.php
  src/lib/Limitation/Mapper/ObjectStateLimitationMapper.php
  src/lib/Limitation/Mapper/SectionLimitationMapper.php
  src/lib/Limitation/Templating/LimitationBlockRenderer.php
  src/lib/Tests/Limitation/Mapper/ContentTypeLimitationMapperTest.php
  src/lib/Tests/Limitation/Mapper/LanguageTypeLimitationMapperTest.php
  src/lib/Tests/Limitation/Mapper/ObjectStateLimitationMapperTest.php
  src/lib/Tests/Limitation/Mapper/SectionLimitationMapperTest.php
Labels: Improvement, Ready for review

#1124 EZP-31096: Custom toolbars in Alloy Editor
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: QA approved

#1138 EZP-31138: Fixed missing Elements Path for richtext_widget
  src/bundle/Resources/views/form_fields.html.twig
Labels: QA approved

#1157 [Behat] Added waiting until RichText toolbar is visible
  src/lib/Behat/PageElement/Fields/RichText.php
Labels: Ready for MERGE

#1149 EZP-31201: Fixed Field Definition Edit Form rendering when custom edit template is not defined
  src/bundle/Resources/views/admin/content_type/edit.html.twig
Labels: Bug, DX, QA approved

#1155 EZP-31089: Wrong allowed content types list on object relation(s) fields
  src/bundle/Templating/Twig/UniversalDiscoveryExtension.php
  src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationAllowedContentTypes.php
Labels: QA approved

#1145 EZP-31194: Searching in UDW does not take allowed CT's into account when ezobjectrelation FieldType is used
  src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationAllowedContentTypes.php
Labels: Bug, QA approved

#1156 EZP-31207: Table header toolbar is added
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table-header.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: QA approved

#1160 EZP-31184: Removed background from active bookmark icon
  src/bundle/Resources/public/scss/_add-to-bookmarks.scss
Labels: QA approved

#1131 EZP-31125: Administration interface should respect siteaccess languages settings
  composer.json
  src/bundle/Controller/ContentController.php
  src/bundle/Controller/LocationController.php
  src/bundle/Controller/TranslationController.php
  src/bundle/Controller/VersionController.php
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/config/services/modules/content_tree.yml
  src/bundle/Resources/config/services/tabs/locationview.yml
  src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js
  src/bundle/Resources/public/js/scripts/admin.limitation.pick.js
  src/bundle/Resources/public/js/scripts/admin.role_assignment.add.js
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
  src/bundle/Resources/public/js/scripts/udw/select.location.js
  src/bundle/Resources/views/admin/role_assignment/create.html.twig
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/relations/table_relations.html.twig
  src/bundle/Resources/views/content/tab/relations/table_relations_reverse.html.twig
  src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
  src/lib/EventListener/RequestAttributesListener.php
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
  src/lib/Tab/LocationView/UrlsTab.php
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: QA approved

#1154 EZP-30758: Ensured the latest version is used when editing content
  src/bundle/Controller/ContentController.php
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/button.content.edit.js
  src/bundle/Resources/views/admin/bookmark/list.html.twig
  src/bundle/Resources/views/admin/search/search_table_row.html.twig
  src/bundle/Resources/views/dashboard/macros.html.twig
  src/bundle/Resources/views/link_manager/view.html.twig
Labels: Bug, QA approved, Ready for review

#1161 EZEE-2738: Hid previous location while dragging in D&D
  src/bundle/Resources/public/js/scripts/core/draggable.js
Labels: QA approved

#1165 EZP-28900: Added `localizednumber` filter to ezfloat value preview
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
Labels: Bug, QA approved, Ready for review

#1166 [Behat] Added waiting until RichText toolbar transition ends
  src/lib/Behat/PageElement/Fields/RichText.php
Labels: Ready for review

#1169 EZP-31078: Enhanced Content Type Value Object
  src/lib/Form/Processor/ContentType/ContentTypeFormProcessor.php
  src/lib/Specification/ContentType/ContentTypeIsUser.php
  src/lib/Util/FieldDefinitionGroupsUtil.php
Labels: Bug

#1108 EZP-31038: add configuration for UDW for bulk add location
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
Labels: QA approved

#1170 Fixed broken unit tests
  src/bundle/ParamConverter/ContentTypeGroupParamConverter.php
  src/bundle/ParamConverter/ContentTypeParamConverter.php
  src/bundle/ParamConverter/PolicyParamConverter.php
  src/bundle/ParamConverter/RoleAssignmentParamConverter.php
  src/bundle/ParamConverter/RoleParamConverter.php
  src/bundle/ParamConverter/SectionParamConverter.php
  src/bundle/Tests/ParamConverter/ContentTypeGroupParamConverterTest.php
  src/bundle/Tests/ParamConverter/ContentTypeParamConverterTest.php
  src/bundle/Tests/ParamConverter/PolicyParamConverterTest.php
  src/bundle/Tests/ParamConverter/RoleAssignmentParamConverterTest.php
  src/bundle/Tests/ParamConverter/RoleParamConverterTest.php
  src/bundle/Tests/ParamConverter/SectionParamConverterTest.php
  src/lib/Form/DataTransformer/SectionsTransformer.php
  src/lib/Tests/Form/Data/FormMapper/ContentTranslationMapperTest.php
  src/lib/Tests/Form/DataTransformer/SectionsTransformerTest.php
  src/lib/Tests/Form/Processor/ContentTypeFormProcessorTest.php
  src/lib/Tests/Limitation/Mapper/ContentTypeLimitationMapperTest.php
  src/lib/Tests/Limitation/Mapper/LanguageTypeLimitationMapperTest.php
  src/lib/Tests/Limitation/Mapper/ObjectStateLimitationMapperTest.php
  src/lib/Tests/Limitation/Mapper/SectionLimitationMapperTest.php
  src/lib/Tests/Specification/ContentType/ContentTypeIsUserTest.php
Labels: Bug

#1162 EZP-31218: Restyled login screen
  src/bundle/Resources/public/img/ez-logo.svg
  src/bundle/Resources/public/img/login-background.jpg
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_login.scss
  src/bundle/Resources/views/themes/admin/account/base.html.twig
  src/bundle/Resources/views/themes/admin/account/login/index.html.twig
  src/bundle/Resources/views/themes/admin/account/reset_password/confirmation_page.html.twig
  src/bundle/Resources/views/themes/admin/account/reset_password/invalid_link_page.html.twig
Labels: QA approved

#1168 EZEE-2954: Added icons for content comparison
  src/bundle/Resources/public/img/ez-icons.svg
Labels: Ready for QA

#1152 EZP-31204: Provided backwards compatibility layer in repository-forms package
  src/lib/FieldType/FieldDefinitionFormMapperInterface.php
  src/lib/Form/Data/FieldDefinitionData.php
  src/lib/Limitation/LimitationFormMapperInterface.php
  src/lib/Limitation/LimitationFormMapperRegistryInterface.php
  src/lib/Limitation/LimitationValueMapperInterface.php
  src/lib/Limitation/LimitationValueMapperRegistryInterface.php
Labels: Improvement, Ready for review

#1164 EZP-31205: Disabled sending form by hitting enter key (new content)
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
Labels: QA approved

#1173 Temporary load root location in UDW via sudo
  src/bundle/Controller/UniversalDiscoveryController.php
Labels: Bug

#1174 EZP-31257: Load field definition only if relation is field related in ValueFactory::{createRelation,createRelationItem}
  src/lib/UI/Value/ValueFactory.php
Labels: Bug
