Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-05, with the labels that each got.

#990 EZP-30514: Moved default configuration to dedicated ViewProvider for the user_settings_update_view
  src/bundle/Resources/config/services/user_settings.yml
  src/bundle/Resources/config/views.yml
Labels: Bug

#974 EZP-30400: Inject TranslationService into NotificationService
  src/bundle/Controller/ContentController.php
  src/bundle/Controller/ContentTypeController.php
  src/bundle/Controller/ContentTypeGroupController.php
  src/bundle/Controller/LanguageController.php
  src/bundle/Controller/LinkManagerController.php
  src/bundle/Controller/LocationController.php
  src/bundle/Controller/ObjectStateController.php
  src/bundle/Controller/ObjectStateGroupController.php
  src/bundle/Controller/PolicyController.php
  src/bundle/Controller/RoleAssignmentController.php
  src/bundle/Controller/RoleController.php
  src/bundle/Controller/SectionController.php
  src/bundle/Controller/TranslationController.php
  src/bundle/Controller/TrashController.php
  src/bundle/Controller/User/UserDeleteController.php
  src/bundle/Controller/VersionController.php
  src/bundle/DependencyInjection/EzPlatformAdminUiExtension.php
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/config/services/translation.yml
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/translations/linkmanager.en.xliff
  src/lib/EventListener/AdminExceptionListener.php
  src/lib/Form/SubmitHandler.php
  src/lib/Notification/FlashBagNotificationHandler.php
  src/lib/Notification/TranslatableNotificationHandler.php
  src/lib/Notification/TranslatableNotificationHandlerInterface.php
  src/lib/RepositoryForms/Form/Processor/ContentEditNotificationFormProcessor.php
  src/lib/RepositoryForms/Form/Processor/PreviewFormProcessor.php
  src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php
  src/lib/Translation/Extractor/NotificationTranslationExtractor.php
Labels: Improvement, QA approved, Ready for MERGE, Ready for review

#995 EZP-30400: Fixed typo in Content Type Behat tests
  features/ContentType.feature
Labels: Bug, Ready for MERGE, Ready for review

#988 EZP-30499 Implement minimal test coverage for Trash
  features/Trash.feature
  src/lib/Behat/BusinessContext/ContentViewContext.php
  src/lib/Behat/BusinessContext/DashboardContext.php
  src/lib/Behat/BusinessContext/ObjectStatesContext.php
  src/lib/Behat/BusinessContext/TrashContext.php
  src/lib/Behat/PageElement/AdminList.php
  src/lib/Behat/PageElement/Fields/ContentRelationSingle.php
  src/lib/Behat/PageElement/Tables/LinkedListTable.php
  src/lib/Behat/PageElement/Tables/SubItemsTable.php
  src/lib/Behat/PageElement/Tables/Table.php
  src/lib/Behat/PageElement/Tables/TrashTable.php
  src/lib/Behat/PageObject/TrashPage.php
Labels: Ready for MERGE

#956 EZP-30397: Unify JavaScript event names
  src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
  src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
  src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
Labels: Improvement, QA approved, Ready for review

#985 EZP-30509: Location visibility check breaks limitation of Content/Read
  src/bundle/Controller/ContentViewController.php
Labels: Bug, QA approved

#992 EZP-30315 [Travis] Standarize and clean up travis configurations across the repositories
  .travis.yml
  behat_suites.yml
  features/ContentTypeFields.feature
Labels: Ready for review

#984 Injected Site Access List directly into EzSystems\EzPlatformAdminUi\UI\Config\Provider\Languages
  src/bundle/Resources/config/services/siteaccess.yml
  src/bundle/Resources/config/services/ui_config/common.yml
  src/lib/Siteaccess/NonAdminSiteaccessResolver.php
  src/lib/Siteaccess/SiteaccessResolver.php
  src/lib/UI/Config/Provider/Languages.php
Labels: Bug, QA approved

#965 EZP 30456: Remove deprecated views
  src/bundle/Resources/views/content/tab/translations/modal_add_translation.html.twig
  src/bundle/Resources/views/content/tab/translations/tab.html.twig
  src/bundle/Resources/views/content/tab/translations/translation_add_form_fields.html.twig
Labels: Improvement, Ready for review

#998 EZEE-2782 [Behat] Problems with form preview and with notification close
  src/lib/Behat/Helper/UtilityContext.php
Labels: Ready for review

#987 EZP-30470: Filtered Content Types and Languages in ContentCreate widget based on user permissions
  composer.json
  src/bundle/Resources/config/services/forms.yml
  src/lib/Form/Type/ChoiceList/Loader/ContentCreateContentTypeChoiceLoader.php
  src/lib/Form/Type/ChoiceList/Loader/ContentCreateLanguageChoiceLoader.php
  src/lib/Form/Type/ChoiceList/Loader/PermissionAwareContentTypeChoiceLoader.php
  src/lib/Form/Type/ChoiceList/Loader/PermissionAwareLanguageChoiceLoader.php
  src/lib/Form/Type/Content/Draft/ContentCreateType.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Permission/LookupLimitationsTransformer.php
  src/lib/Permission/PermissionChecker.php
  src/lib/Permission/PermissionCheckerInterface.php
  src/lib/Tests/Permission/LookupLimitationsTransformerTest.php
Labels: Bug, QA approved

#989 EZP-28034: Refactored to use EzPlatformRestBundle
  composer.json
  features/SystemInfo.feature
  src/bundle/Controller/BulkOperation/BulkOperationController.php
  src/bundle/Controller/Content/ContentTreeController.php
  src/bundle/Controller/UniversalDiscoveryController.php
  src/lib/REST/Input/Parser/BulkOperation.php
  src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequest.php
  src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequestNode.php
  src/lib/REST/Input/Parser/Operation.php
  src/lib/REST/Output/ValueObjectVisitor/BulkOperationResponse.php
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/Node.php
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/Root.php
  src/lib/REST/Value/BulkOperation.php
  src/lib/REST/Value/BulkOperationResponse.php
  src/lib/REST/Value/ContentTree/LoadSubtreeRequest.php
  src/lib/REST/Value/ContentTree/LoadSubtreeRequestNode.php
  src/lib/REST/Value/ContentTree/Node.php
  src/lib/REST/Value/ContentTree/Root.php
  src/lib/REST/Value/Operation.php
  src/lib/REST/Value/OperationResponse.php
  src/lib/Tests/Util/FieldDefinitionGroupsUtilTest.php
  src/lib/UI/Config/Provider/SortFieldMappings.php
  src/lib/UI/Config/Provider/SortOrderMappings.php
  src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php
  src/lib/UI/Module/Subitems/ValueObjectVisitor/SubitemsList.php
  src/lib/UI/Module/Subitems/ValueObjectVisitor/SubitemsRow.php
  src/lib/UI/Module/Subitems/Values/ContentTypeRemoteIdList.php
  src/lib/UI/Module/Subitems/Values/SubitemsList.php
  src/lib/UI/Module/Subitems/Values/SubitemsRow.php
Labels: Feature, QA approved, Ready for MERGE

#1005 EZP-29694: Changed publishing to publish last modified translation
  src/lib/RepositoryForms/Form/Processor/Content/ContentOnTheFlyProcessor.php
Labels: Improvement

#997 EZP-30494: Default Time field value is not saved
  src/bundle/Resources/public/js/scripts/fieldType/eztime.js
Labels: Bug, QA approved, Ready for MERGE
