Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2019-06, with the labels that each got.

#1000 Applied fixes for tests after suggestions from Infection framework
  src/bundle/ParamConverter/ContentParamConverter.php
  src/bundle/ParamConverter/PolicyParamConverter.php
  src/bundle/Tests/ParamConverter/ContentParamConverterTest.php
  src/bundle/Tests/ParamConverter/ContentTypeDraftParamConverterTest.php
  src/bundle/Tests/ParamConverter/ContentTypeGroupParamConverterTest.php
  src/bundle/Tests/ParamConverter/ContentTypeParamConverterTest.php
  src/bundle/Tests/ParamConverter/LanguageParamConverterTest.php
  src/bundle/Tests/ParamConverter/PolicyParamConverterTest.php
  src/bundle/Tests/ParamConverter/RoleAssignmentParamConverterTest.php
  src/bundle/Tests/ParamConverter/RoleParamConverterTest.php
  src/bundle/Tests/ParamConverter/SectionParamConverterTest.php
  src/bundle/Tests/ParamConverter/VersionInfoParamConverterTest.php
Labels: Improvement

#1006 EZP-30617 [Behat] Problem with select item in multiselect UDW
  features/ContentType.feature
  features/ContentTypeFields.feature
  src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
Labels: Ready for MERGE

#999 EZP-30553: User settings pagination limit should be different for admin_group and other siteaccesses
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
Labels: Bug, QA approved

#1007 EZP-30588: Make possible to translate custom tag choice attributes
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-customtag-update.js
  src/lib/Tests/UI/Config/Mapper/FieldType/RichText/CustomTagTest.php
  src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag.php
  src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag/ChoiceAttributeMapper.php
Labels: Bug, QA approved

#1010 Fixes paths in search templates
  src/bundle/Resources/views/themes/admin/ui/search/index.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/list.html.twig
Labels: Bug, Ready for review

#1011 fixes a typo in a template path
  src/bundle/Resources/views/themes/admin/ui/search/list.html.twig
Labels: Bug, Ready for MERGE

#1013 EZP-30654: User settings/change password/Forgot password doesn't work
  src/bundle/Resources/config/ezplatform_default_settings.yaml
Labels: Bug, Ready for review

#1016 EZP-30660: Cannot change password
  src/lib/Notification/TranslatableNotificationHandler.php
  src/lib/Notification/TranslatableNotificationHandlerInterface.php
Labels: Bug, QA approved

#1012 EZP-30642 display app logs
  src/lib/Behat/Helper/Hooks.php
Labels: Ready for review

#1018 EZP-30666: fixed paths to images of error page
  src/bundle/Resources/views/themes/admin/ui/error_page/403.html.twig
  src/bundle/Resources/views/themes/admin/ui/error_page/404.html.twig
  src/bundle/Resources/views/themes/admin/ui/error_page/unknown.html.twig
Labels: Bug, QA approved

#1017 EZP-30648: Values of checkboxes are not displayed properly in Content Type view
  src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
Labels: Bug, QA approved

#1015 EZP-30665: Custom styles dropdown becomes unusable when contains many…
  src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
Labels: Ready for MERGE

#1023 EZP-30670: Replaced deprecated Symfony Kernel parameters
  src/bundle/Resources/translations/systeminfo.en.xliff
  src/bundle/Resources/views/themes/admin/system_info/symfony_kernel.html.twig
Labels: Improvement, QA approved

#1021 EZP-30686: Added errors logging in the form submission handler
  src/lib/Form/SubmitHandler.php
Labels: DX, Improvement, QA approved

#1008 EZP-30627: Unified twig helpers naming
  src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
  src/bundle/Resources/views/themes/admin/content/draft/list.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/url/custom_urls_table.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/url/system_urls_table.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
  src/bundle/Resources/views/themes/admin/content_type/create.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
  src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/themes/admin/content_type/index.html.twig
  src/bundle/Resources/views/themes/admin/limitation/udw_limitation_value.html.twig
  src/bundle/Resources/views/themes/admin/system_info/info.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/themes/admin/ui/error_page/404.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/ezimageasset.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/top_navigation.html.twig
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
  src/bundle/Templating/Twig/ComponentExtension.php
  src/bundle/Templating/Twig/PathStringExtension.php
  src/bundle/Templating/Twig/TabExtension.php
  src/bundle/Templating/Twig/UiConfigExtension.php
Labels: Improvement, Ready for review

#1027 EZP-30653: User is unable to add translation to the item
  src/lib/View/Builder/ContentTranslateViewBuilder.php
Labels: Bug, Ready for review

#1026 EZP-30699: Made dynamic settings loaded too early to be lazy-loaded
  src/bundle/DependencyInjection/Compiler/TabPass.php
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/config/services/menu.yml
  src/bundle/Resources/config/services/tabs.yml
  src/bundle/Resources/config/services/ui_config/common.yml
  src/bundle/Resources/config/services/universal_discovery_widget.yml
  src/lib/UniversalDiscovery/ConfigResolver.php
Labels: Bug, QA approved

#1024 EZP-30695: Remove hardcoded subtree paths in Admin UI
  src/bundle/DependencyInjection/Configuration/Parser/SubtreePath.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/dashboard.yml
  src/bundle/Resources/config/services/query_types.yaml
  src/lib/QueryType/ContentSubtreeQueryType.php
  src/lib/QueryType/MediaSubtreeQueryType.php
  src/lib/QueryType/SubtreeQueryType.php
  src/lib/Tab/Dashboard/EveryoneContentTab.php
  src/lib/Tab/Dashboard/EveryoneMediaTab.php
  src/lib/Tab/Dashboard/MyContentTab.php
  src/lib/Tab/Dashboard/MyMediaTab.php
  src/lib/Tab/Dashboard/SubtreeQuery.php
Labels: Improvement, QA approved, Ready for review

#1028 EZEE-2793: Lazy-loaded PermissionResolver for auto-wiring
  src/bundle/Resources/config/services/service_aliases.yml
Labels: Bug, QA approved
