Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-08, with the labels that each got.

#1444 EZP-31788: Remove duplicate icon from svg file
  src/bundle/Resources/public/img/ez-icons.svg
Labels: QA approved

#1443 EZP-31777: Resolved Locations in Content relations and search module
  src/bundle/Resources/views/admin/search/search_table_row.html.twig
  src/bundle/Resources/views/content/tab/relations/table_relations.html.twig
  src/bundle/Resources/views/content/tab/relations/table_relations_reverse.html.twig
  src/lib/Search/AbstractPagerContentToDataMapper.php
  src/lib/Search/PagerSearchContentToDataMapper.php
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
  src/lib/UI/Value/Content/Relation.php
  src/lib/UI/Value/ValueFactory.php
Labels: Improvement, QA approved

#1445 [Behat] Fixed tests running on PostgreSQL
  features/standard/ContentCreation.feature
  features/standard/ContentTypeFields.feature
  features/standard/SearchContent.feature
  features/standard/Trash.feature
  src/lib/Behat/PageObject/RolePage.php
Labels: Ready for MERGE

#1446 EZP-31777: Added resolved 'locationId' to '_ez_content_view' path in Search module
  src/bundle/Resources/views/themes/admin/ui/search/list_item.html.twig
Labels: Bug, QA approved

#1447 [Behat] Extracted Scenario emptying Trash
  features/standard/CleanTrash.feature
  features/standard/Trash.feature
  src/lib/Behat/BusinessContext/TrashContext.php
Labels: Ready for review

#1451 [Behat] Fixed incorrect TrashContext merge
  src/lib/Behat/BusinessContext/TrashContext.php
Labels: Ready for MERGE

#1453 [Behat] Adapted Behat tests for PostgreSQL
  src/lib/Behat/PageElement/Fields/Keywords.php
Labels: Ready for MERGE

#1452 EZP-31805: Moved default template configuration from twig file to yaml
  src/bundle/Resources/config/admin_ui_forms.yml
  src/bundle/Resources/views/content/content_view_fields.html.twig
Labels: QA approved

#1458 EZP-31776: Resolved Contents' Locations in Dashboard
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/all_content.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/all_media.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_content.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_media.html.twig
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
Labels: Bug, QA approved
