Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-12, with the labels that each got.

#1656 [Composer] Bumped BazingaJsTranslationBundle to ^4.0
  composer.json
Labels: Feature, Improvement, Work in progress

#1652 [Behat] EZP-32136 User creation
  features/standard/UserCreation.feature
  src/lib/Behat/BusinessContext/ContentUpdateContext.php
  src/lib/Behat/BusinessContext/ContentViewContext.php
  src/lib/Behat/PageElement/ContentField.php
  src/lib/Behat/PageElement/ContentUpdateForm.php
  src/lib/Behat/PageElement/Fields/UserAccount.php
  src/lib/Behat/PageObject/ContentItemPage.php
  src/lib/Behat/PageObject/Page.php
  src/lib/Behat/PageObject/PlatformPageObjectFactory.php
  src/lib/Behat/PageObject/UserCreationPage.php
Labels: Ready for review

#1655 EZEE-3350: Added support for saving additional image data from adminUI
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
Labels: QA approved, Ready for MERGE

#1660 [Behat] Adjusted title in UserCreationPage
  src/lib/Behat/PageObject/UserCreationPage.php
Labels: Ready for review

#1662 EZP-32212: Changed class to correct recognition ezmatrix fieldType
  src/lib/Behat/PageElement/ContentField.php
Labels: QA approved, Ready for review

#1657 EZP-32197: added z-index to prevent overlapping with other elements
  src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
Labels: QA approved

#1664 EZP-32210 objects multiple locations labels
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
Labels: Bug, QA approved

#1663 EZP-32216: As a Maintainer, I want to use chartjs and js-md5
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Labels: QA approved

#1666 EZP-32173: Fixed UDW 'allowed_content_types' configuration
  src/lib/Tests/UniversalDiscovery/Event/Subscriber/RichTextEmbedAllowedContentTypesTest.php
  src/lib/UniversalDiscovery/Event/Subscriber/RichTextEmbedAllowedContentTypes.php
Labels: Bug, QA approved

#1668 EZEE-3399: Remove icon hover state on disabled buttons
  src/bundle/Resources/public/scss/_icons.scss
Labels: Bug

#1674 EZP-32193: Map location validation error message typo
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
  src/bundle/Resources/translations/fieldtypes_edit.en.xliff
Labels: QA approved

#1671 EZP-32226: Logo in error page is misaligned
  src/bundle/Resources/public/scss/_error-page.scss
Labels: QA approved

#1673 EZP-32225: Dropdown is not properly styled for content type with field ezselection
  src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
Labels: QA approved

#1676 EC-277: Components notification message is not aligned to the left
  src/bundle/Resources/views/themes/admin/ui/component/preview_unavailable.html.twig
Labels: QA approved

#1677 EC-288: Uncaught typeerror cannot read property focus of undefined
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
Labels: QA approved

#1678 EC-288: Uncaught TypeError: Cannot read property focus of undefined
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
Labels: QA approved

#1672 EZEE-3397: Added fieldDefId & contentId to image editor button
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
Labels: QA approved

#1675 EZP-32223: Certain Back Office languages can break pager labels
  src/bundle/Resources/public/scss/_pagination.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
Labels: QA approved

#1679 EZP-32248: Retain content tree state
  src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
  src/bundle/ui-dev/src/modules/content-tree/content.tree.module.js
Labels: QA approved

#1683 EZP-32252: Wrong documentation link in login screen
  src/bundle/Resources/views/themes/admin/account/base.html.twig
Labels: Bug

#1680 EZEE-3419: Fixed providing empty object instead of empty array when no data set
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
Labels: QA approved

#1684 EZP-32253: Wrong links hover on login screen
  src/bundle/Resources/public/scss/_links.scss
  src/bundle/Resources/views/themes/admin/account/base.html.twig
Labels: Bug

#1682 EZP-32117: [UI][UX] Content Field validation error is not auto-scrolled to when it occurs on a non-focused tab
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
Labels: QA approved

#1685 Updated translation files
  src/bundle/Resources/translations/content_create.en.xliff
  src/bundle/Resources/translations/content_edit.en.xliff
  src/bundle/Resources/translations/dashboard.en.xliff
  src/bundle/Resources/translations/ezplatform_content_forms_content.en.xliff
  src/bundle/Resources/translations/ezplatform_content_forms_policies.en.xliff
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/language.en.xliff
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/translations/role.en.xliff
  src/bundle/Resources/translations/search.en.xliff
  src/bundle/Resources/translations/section.en.xliff
  src/bundle/Resources/translations/user_create.en.xliff
  src/bundle/Resources/translations/user_edit.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
Labels: Bug

#1686 Simplify login form view customization
  src/bundle/Resources/views/themes/admin/account/login/index.html.twig
Labels: DX, Improvement, QA approved

#1681 EZP-32243: Exposed repository object counts in database tab
  features/standard/SystemInfo.feature
Labels: QA approved

#1687 EZEE-3422: Prepared LICENSE and COPYRIGHT files for 3.3 release
  COPYRIGHT
  LICENSE
  LICENSE-bul
  README.md
Labels: Ready for review
