Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-10, with the labels that each got.

#1548 EZP-31955: Removed padding on 'user account' input row
  src/bundle/Resources/public/scss/fieldType/edit/_ezuser.scss
Labels: QA approved

#1547 EC-255: Add buttons and dropdown is not properly styled
  src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
Labels: QA approved

#1553 EZP-31953: Fixed missing and wrongly located translations
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig
Labels: QA approved

#1551 EZP-31983: Catched exception thrown by empty tab group
  src/lib/Tab/Event/Subscriber/ConditionalTabSubscriber.php
Labels: QA approved

#1488 EZP-31875: Added request matcher to recognize REST requests executed in AdminUI context
  src/bundle/Resources/config/services/rest.yaml
  src/lib/REST/Security/NonAdminRESTRequestMatcher.php
  src/lib/Tests/REST/Security/NonAdminRESTRequestMatcherTest.php
Labels: Ready for QA, Ready for review

#1568 EZP-32003: Fix cancel editing redirect for root location
  features/standard/ContentDraft.feature
  src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig
Labels: QA approved

#1580 EZP-32012: Search page has not properly aligned elements
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
Labels: Bug, QA approved

#1569 EZP-32002: Move system information UI to be a part of ez-support-tools
  composer.json
  src/bundle/Controller/SystemInfoController.php
  src/bundle/DependencyInjection/Compiler/SystemInfoTabGroupPass.php
  src/bundle/EzPlatformAdminUiBundle.php
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/services/dashboard.yaml
  src/bundle/Resources/config/services/service_aliases.yaml
  src/bundle/Resources/config/services/tabs.yaml
  src/bundle/Resources/config/services/tabs/systeminfo.yaml
  src/bundle/Resources/translations/systeminfo.en.xliff
  src/bundle/Resources/views/themes/admin/system_info/composer.html.twig
  src/bundle/Resources/views/themes/admin/system_info/database.html.twig
  src/bundle/Resources/views/themes/admin/system_info/hardware.html.twig
  src/bundle/Resources/views/themes/admin/system_info/info.html.twig
  src/bundle/Resources/views/themes/admin/system_info/php.html.twig
  src/bundle/Resources/views/themes/admin/system_info/symfony_kernel.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
  src/bundle/Resources/views/themes/admin/ui/tab/system_info.html.twig
  src/bundle/Tests/DependencyInjection/Compiler/SystemInfoTabGroupPassTest.php
  src/lib/Component/Dashboard/EzInfoTwigComponent.php
  src/lib/EventListener/SystemInfoTabGroupListener.php
  src/lib/Tab/SystemInfo/SystemInfoTab.php
  src/lib/Tab/SystemInfo/TabFactory.php
  src/lib/Tests/EventListener/SystemInfoTabGroupListenerTest.php
Labels: Improvement, Ready for review

#1584 EZP-31094: Fixed unnecessary ":" in Content Type translations
  src/bundle/Resources/translations/content_type.en.xliff
  src/lib/Form/Type/ContentType/ContentTypeUpdateType.php
Labels: Ready for review

#1588 EZP-32030: Fixed CotF blank screen after publishing
  src/bundle/Controller/ContentOnTheFlyController.php
Labels: QA approved

#1589 EZP-32032: Wrong color icons for Create/Delete buttons on Roles view
  src/bundle/Resources/views/themes/admin/user/role/list.html.twig
Labels: Bug, QA approved, Ready for review

#1590 EZP-32033: Wrong caret icon size on Content Type Edit view
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
Labels: Bug, QA approved, Ready for review

#1591 EZP-32034: Draft list view has a wrong padding for container and table
  src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig
Labels: Bug, Ready for review

#1595 EZP-32036: UDW icons got a wrong size for expanding and collapsing panel
  src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/top-menu/top.menu.js
Labels: Bug, Ready for review

#1594 EZP-32019: Switching Player settings in ezmedia field causes console error
  src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
Labels: Bug

#1601 EZP-32047: Errors in forms should use danger color not primary
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezrichtext.scss
  src/bundle/Resources/public/scss/mixins/_inputs.scss
Labels: Bug, QA approved

#1596 EZP-32038: Move System information tab to ez-support-tools
  src/lib/Menu/MainMenuBuilder.php
Labels: Improvement

#1613 EZP-32054: Search view is inconsistent with other main views
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/index.html.twig
  src/lib/Behat/PageObject/SearchPage.php
Labels: Bug, Ready for review

#1610 EC-276: Create new Product catalog content form contains unnecessary information icon in header
  src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig
Labels: QA approved

#1614 EZP-32056: Wrong margin for Search button in the URL management list
  src/bundle/Resources/views/themes/admin/link_manager/list.html.twig
Labels: Bug, Ready for review

#1617 [Behat] Changed root content name to Ibexa
  src/lib/Behat/Environment/PlatformEnvironmentConstants.php
Labels: Ready for review

#1618 EZP-32061: [File] Incorrect label for download button / buttons are too close to each other
  src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/translations/ezplatform_content_forms_content.en.xliff
  src/bundle/Resources/translations/ezplatform_content_forms_policies.en.xliff
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezbinaryfile.html.twig
Labels: QA approved

#1626 [Behat] Added verification of existence and closing of the notificati…
  features/standard/Roles.feature
Labels: Ready for review

#1628 EZP-32070: Fixed Content Edit and Publish policy with grouped choices
  src/bundle/Resources/views/themes/admin/limitation/base_limitation_values.html.twig
Labels: QA approved

#1643 EZP-31039: Remove unnecessary sorting params when updating Location priority
  src/bundle/ui-dev/src/modules/sub-items/services/sub.items.service.js
Labels: Bug, QA approved

#1644 EZP-32105: Deprecated obsolete pagination search limit configuration setting
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
Labels: Ready for review

#1642 EZP-31968: Added spinner to UDW
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
  src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js
Labels: QA approved

#1629 EZEE-3324: Form Builder: missing design for checkbox field in the Form preview
  composer.json
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved

#1641 EC-286: set max width for ez-custom-dropdown options container
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
Labels: QA approved
