Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-07, with the labels that each got.

#1418 EZP-31650: Temporarily disable Trash test cases
  .travis.yml
  behat_suites.yml
  features/standard/Trash.feature
Labels: Ready for review

#1416 EZP-31714: Fix translation 'Any Content Type'
  src/bundle/Resources/translations/messages.en.xliff
Labels: QA approved

#1415 EZP-31692: Hide tooltip after show/hide details of content
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
  src/bundle/Resources/translations/content_edit.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
Labels: QA approved

#1414 EZP-31695: Add mising tooltips for close modal (send to trash)
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/content/modal/location_trash.html.twig
Labels: QA approved

#1417 EZP-31703: Added missing tooltip 'Close' for modal 'Remove from trash'
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/ui/modal/bulk_delete_confirmation.html.twig
Labels: QA approved

#1422 EZP-31696: removed focus after content tree expanded
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
Labels: QA approved

#1420 EZP-31697: Added remove tooltip when removed node is diffrenty than .…
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
Labels: QA approved

#1419 EZEE-3195: Fixed error message position
  src/bundle/Resources/public/scss/_warning-icon.scss
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
Labels: QA approved

#1409 EZP-31693: Used custom SearchType for admin SA
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/forms.yaml
  src/bundle/Resources/config/services/views.yaml
  src/bundle/Resources/config/views.yaml
  src/lib/EventListener/SearchViewFilterParametersListener.php
  src/lib/Form/Type/Search/SearchType.php
  src/lib/View/Filter/AdminSearchViewFilter.php
Labels: QA approved

#1423 [Behat] Adjusted Trash tests
  features/standard/Trash.feature
  src/lib/Behat/PageObject/TrashPage.php
Labels: Ready for MERGE

#1410 EZP-31710: Search in frontend can now be filtered by multiple users
  src/lib/Form/Type/Search/SearchType.php
Labels: QA approved

#1421 EZP-31719: Verbatim HTML in end of life information on Dashboard
  src/bundle/Resources/translations/dashboard.en.xliff
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
Labels: Bug, QA approved

#1425 EZP-30686: Improved form submission error handling by logging errors
  src/lib/Form/SubmitHandler.php
Labels: Improvement

#1435 EZP-31743: Multi-input single field validation doesn't show proper error
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/fieldType/base/multi-input-field.js
  src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
Labels: QA approved

#1366 EZP-31418: Consistent content tree animation
  src/bundle/Resources/public/scss/_content-tree.scss
Labels: QA approved

#1432 EZP-31742: UDW error for users with restricted content types
  src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php
Labels: QA approved

#1376 EZP-31576: When in COTF make UDW & consecutive COTF views take the full view
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.edit.scss
  src/bundle/ui-dev/src/modules/universal-discovery/content.create.tab.module.js
  src/bundle/ui-dev/src/modules/universal-discovery/content.edit.tab.module.js
Labels: QA approved

#1350 EZP-31557: Fixed ezdate editing within different timezones
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
  src/bundle/Resources/views/fieldtypes/edit/ezdate.html.twig
Labels: Bug, Ready for QA

#1439 EZP-31584: Changed main Location to first available Location in Relations
  src/lib/UI/Value/ValueFactory.php
Labels: Bug, QA approved

#1440 [BEHAT] added tags to avoid using TC which are faulty in eZCommerce
  features/standard/Authentication.feature
  features/standard/ContentTypeFields.feature
Labels: Ready for review
