Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-02, with the labels that each got.

#1220 [Behat] Changed selecting multiple items to be more bullet-proof
  src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
Labels: Ready for MERGE

#1218 EZP-31347: Added functionality to show dropdown above select field
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
Labels: QA approved

#1208 EZP-31311: Add missing fieldtype tests
  behat_suites.yml
  features/standard/ContentTypeFields.feature
  src/lib/Behat/PageElement/ContentField.php
  src/lib/Behat/PageElement/Fields/EzFieldElement.php
  src/lib/Behat/PageElement/Fields/ImageAsset.php
  src/lib/Behat/PageElement/Fields/MapLocation.php
  src/lib/Behat/PageElement/Fields/Matrix.php
  src/lib/Behat/PageElement/Fields/TextLine.php
  src/lib/Behat/PageElement/Fields/URL.php
  src/lib/Behat/PageElement/PlatformElementFactory.php
  src/lib/Behat/TestFiles/imageasset1.png.zip
  src/lib/Behat/TestFiles/imageasset2.png.zip
Labels: Ready for review

#1222 [Behat] Fixed UDW issue when the newly selected item has no children
  src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
Labels: Ready for MERGE

#1221 EZP-31349: Triggered content tree animation only by clicking by mouse
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
  src/bundle/Resources/public/scss/_content-tree.scss
Labels: Bug, QA approved

#1215 EZP-30009: Added missing translations on Admin -> Roles
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/views/admin/policy/list.html.twig
Labels: Bug, QA approved

#1224 [Behat] Fixed invalid selectors for fieldtypes
  src/lib/Behat/PageElement/Fields/MapLocation.php
  src/lib/Behat/PageElement/Fields/Matrix.php
  src/lib/Behat/PageElement/Fields/URL.php
Labels: Ready for review

#1191 EZP-30575: Fixed parsing date format in formatICU
  src/bundle/Resources/public/js/scripts/admin.format.date.js
Labels: QA approved

#1217 EZP-31137: Fixed styles dropdown when custom ones are in use for RTE
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-styleslistitem.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-custom-style.js
Labels: Bug, QA approved

#1177 EZP-30761: added ellipsize to strings
  src/bundle/Resources/public/scss/_breadcrumb.scss
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_field-group.scss
  src/bundle/Resources/public/scss/_header.scss
  src/bundle/Resources/public/scss/_notifications-modal.scss
  src/bundle/Resources/public/scss/_page-title.scss
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/views/admin/bookmark/list.html.twig
  src/bundle/Resources/views/admin/content_draft/draft_list.html.twig
  src/bundle/Resources/views/admin/content_draft/list.html.twig
  src/bundle/Resources/views/admin/content_type/list.html.twig
  src/bundle/Resources/views/admin/search/search_table_row.html.twig
  src/bundle/Resources/views/admin/trash/list.html.twig
  src/bundle/Resources/views/content/content_edit/content_edit.html.twig
  src/bundle/Resources/views/dashboard/tab/all_content.html.twig
  src/bundle/Resources/views/dashboard/tab/all_media.html.twig
  src/bundle/Resources/views/dashboard/tab/my_content.html.twig
  src/bundle/Resources/views/dashboard/tab/my_draft_list.html.twig
  src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/dashboard/tab/my_media.html.twig
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
  src/bundle/Resources/views/parts/breadcrumbs.html.twig
  src/bundle/Resources/views/parts/page_title.html.twig
  src/bundle/Resources/views/parts/table_header.html.twig
Labels: QA approved

#1229 EZEE-2975: In Page Builder dropdown widgets are too low after being expanded
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
  src/bundle/Resources/public/scss/_extra-actions.scss
Labels: QA approved

#1230 EZP-31367: Do not use translated node name for Location ID 1 in Content Tree
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Bug, QA approved, Ready for review

#1181 EZP-31223: harmonize headers and exit buttons
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/public/scss/_main-row.scss
  src/bundle/Resources/public/scss/_preview.scss
  src/bundle/Resources/translations/content_create.en.xliff
  src/bundle/Resources/translations/content_edit.en.xliff
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
Labels: Improvement, QA approved

#1231 [Behat] Adjusted selector for new header design in Edit mode
  src/lib/Behat/PageObject/ContentUpdateItemPage.php
Labels: Ready for MERGE

#1234 Revert "EZEE-2975: In Page Builder dropdown widgets are too low after being expanded"
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
  src/bundle/Resources/public/scss/_extra-actions.scss
Labels: Bug, QA approved

#1235 EZP-31381: Fixed z-index overlay covers when deleting items
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_main-row.scss
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/user/create.html.twig
  src/bundle/Resources/views/themes/admin/user/edit.html.twig
Labels: QA approved

#1227 EZP-31366: [Behat] Added checking visibility of ContentTypePicker
  src/lib/Behat/PageElement/ContentTypePicker.php
  src/lib/Behat/PageObject/ContentItemPage.php
Labels: Ready for review

#1239 EZP-31384: Broken Content on the fly create template style
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
Labels: Bug, QA approved

#1237 EZP-31310: Fixed VersionDraftConflict for content having multiple locations
  src/bundle/Controller/Content/VersionDraftConflictController.php
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js
  src/bundle/Resources/views/content/tab/versions/table.html.twig
Labels: Bug, QA approved, Ready for review

#1243 EZEE-2933: Changed structure html to correct for alloyEditor
  src/bundle/Resources/views/form_fields.html.twig
Labels: Bug, QA approved

#1232 EZP-31380: Disable manage rows/cells buttons for table and row toolbars
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base-table.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table-cell.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table-header.js
Labels: QA approved

#1233 EZP-31382: As a Developer, I want to have access to userId in JS scripts
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
  src/bundle/Resources/public/js/scripts/helpers/user.helper.js
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Labels: QA approved

#1228 EZP-31311: Add queryfieldtype tests
  features/standard/ContentTypeFields.feature
  src/lib/Behat/BusinessContext/ContentUpdateContext.php
  src/lib/Behat/BusinessContext/ContentViewContext.php
  src/lib/Behat/PageElement/ContentField.php
  src/lib/Behat/PageElement/ContentUpdateForm.php
  src/lib/Behat/PageElement/Fields/ContentQuery.php
  src/lib/Behat/PageElement/Fields/NonEditableField.php
  src/lib/Behat/PageElement/PlatformElementFactory.php
Labels: Ready for review

#1245 EZP-31371: Copying a web page link w/o protocol in a Word paragraph leads to a 404 error
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved, Ready for MERGE

#1250 [Behat] Added verification of notification when adding Image Asset
  src/lib/Behat/PageElement/Fields/ImageAsset.php
Labels: Ready for MERGE

#1247 [Behat] Refatored Map Location test to give OpenStreetMap time to respond
  features/standard/ContentTypeFields.feature
  src/lib/Behat/PageElement/Fields/MapLocation.php
Labels: Ready for MERGE

#1249 EZP-31310: Fixed VersionDraftConflict for content having multiple locations
  src/bundle/Controller/Content/VersionDraftConflictController.php
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js
  src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Bug

#1176 EZP-31236: Added tooltips as new UI component
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/core/custom.tooltip.js
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
  src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js
  src/bundle/Resources/public/scss/core/_custom.tooltip.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/translations/ezplatform_content_forms_content.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
  src/bundle/Resources/views/themes/admin/link_manager/list.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezmedia.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/list_item.html.twig
  src/lib/Behat/PageElement/AdminList.php
  src/lib/Behat/PageElement/Tables/LinkedListTable.php
  src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeGroupCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeGroupEditRightSidebarBuilder.php
  src/lib/Menu/Admin/Language/LanguageCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Language/LanguageEditRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateGroupCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateGroupEditRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/RoleCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/RoleEditRightSidebarBuilder.php
  src/lib/Menu/ContentCreateRightSidebarBuilder.php
  src/lib/Menu/ContentEditRightSidebarBuilder.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Menu/ContentTypeRightSidebarBuilder.php
  src/lib/Menu/LeftSidebarBuilder.php
  src/lib/Menu/SectionCreateRightSidebarBuilder.php
  src/lib/Menu/SectionEditRightSidebarBuilder.php
  src/lib/Menu/TrashRightSidebarBuilder.php
  src/lib/Menu/URLEditRightSidebarBuilder.php
  src/lib/Menu/UserPasswordChangeRightSidebarBuilder.php
  src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
Labels: QA approved

#1257 EZP-31404: Validation error message is not aligned with new create form style
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
Labels: QA approved

#1252 EZP-30482: No limitation to image content type when embedding image in RTE
  src/bundle/Resources/config/universal_discovery_widget.yml
Labels: Bug, QA approved

#1246 EZP-31394: Fixed wrong button and behavior for edit action in version table
  src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
Labels: QA approved

#1253 EZP-31386 Added icon: caret-expanded
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/caret-expanded.svg
Labels: Ready for QA

#1242 EZP-29950: Changed styles of creator on the search tab
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
Labels: QA approved

#1256 EZP-31356: Fixed styles dropdown selection on Firefox and Safari
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-dropdown.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-styleslist.js
Labels: Bug, QA approved

#1248 EZP-31395: Fixed permission check for rev. relation list in Relations tab
  src/lib/Tab/LocationView/RelationsTab.php
Labels: Bug, QA approved

#1223 EZP-31299: Added 'search in specific language' feature
  src/bundle/Controller/SearchController.php
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/dashboard.yml
  src/bundle/Resources/config/services/forms.yml
  src/bundle/Resources/config/services/search.yml
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.search.js
  src/bundle/Resources/public/js/scripts/button.translation.edit.js
  src/bundle/Resources/public/scss/_translation-selector.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/translations/edit_translation_button.en.xliff
  src/bundle/Resources/translations/search.en.xliff
  src/bundle/Resources/views/admin/search/list.html.twig
  src/bundle/Resources/views/admin/search/search.html.twig
  src/bundle/Resources/views/admin/search/search_form.html.twig
  src/bundle/Resources/views/admin/search/search_table_row.html.twig
  src/bundle/Resources/views/dashboard/macros.html.twig
  src/bundle/Resources/views/parts/edit_translation_button.html.twig
  src/lib/Form/Data/Search/SearchData.php
  src/lib/Form/Type/ChoiceList/Loader/ConfiguredLanguagesChoiceLoader.php
  src/lib/Form/Type/ChoiceList/Loader/LanguageChoiceLoader.php
  src/lib/Form/Type/Language/AbstractLanguageChoiceType.php
  src/lib/Form/Type/Language/ConfiguredLanguagesChoiceType.php
  src/lib/Form/Type/Language/LanguageChoiceType.php
  src/lib/Form/Type/Search/SearchType.php
  src/lib/Search/AbstractPagerContentToDataMapper.php
  src/lib/Search/PagerSearchContentToDataMapper.php
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
Labels: QA approved
