Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-09, with the labels that each got.

#1466 EZP-31823: Cannot reuse subitems in other pages than content structure
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/ui-dev/src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.component.js
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
Labels: QA approved

#1471 EZP-31828: Fixed password expiration info in 'ezuser' fieldtype
  src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
Labels: Bug, QA approved

#1477 [Behat] Added check that session is started before browser logs are accessed
  src/lib/Behat/Helper/TestLogProvider.php
Labels: Ready for review

#1469 [BEHAT] added support for parameters in ContentTypeFields.feature
  features/standard/ContentTypeFields.feature
Labels: Ready for review

#1478 [Behat] Added filtering of Content Types in Content Type Picker
  src/lib/Behat/PageElement/ContentTypePicker.php
Labels: Ready for review

#1479 [Behat] Added sorting subitems by Modified date before navigating
  src/lib/Behat/PageElement/SubItemsList.php
  src/lib/Behat/PageElement/Tables/SubItemsTable.php
  src/lib/Behat/PageObject/ContentItemPage.php
Labels: Ready for review

#1480 [Behat] Added checks to make sure Content Type filtering can be interacted with
  src/lib/Behat/PageElement/ContentTypePicker.php
Labels: Ready for review

#1481 [Behat] Adapted tests to subitems grid view which cannot be sorted
  src/lib/Behat/PageElement/SubItemsList.php
  src/lib/Behat/PageElement/Tables/SubItemsTable.php
  src/lib/Behat/PageElement/Tables/SubitemsGridList.php
  src/lib/Behat/PageObject/ContentItemPage.php
Labels: Ready for review

#1122 EZP-31086: Redirect based on router, not url alias
  src/bundle/Resources/config/services/form_processors.yml
  src/lib/RepositoryForms/Form/Processor/Content/SystemUrlRedirectProcessor.php
Labels: QA approved

#1486 EZP-31852: Fixed selectedLocations prop in UDW
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved

#1482 [Behat] Added reloading of the page when Content Type is not present in picker
  src/lib/Behat/PageElement/ContentTypePicker.php
  src/lib/Behat/PageObject/ContentItemPage.php
Labels: Ready for MERGE

#1496 EZP-31913: Back button is not properly styled in sub-items pagination
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/_pagination.scss
  src/bundle/ui-dev/src/modules/common/pagination/pagination.js
Labels: QA approved

#1494 EZP-31906: Date fields automatically set to current date in Edit mode
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezdate.html.twig
Labels: QA approved

#1509 EZP-31883: [File] Download button has wrong colour and is not properly formatted
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
Labels: QA approved

#1510 EZP-31923: [Trash] Restore's and Delete buttons are displayed too close to each other
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig
  src/bundle/Resources/views/themes/admin/content_type/list.html.twig
  src/bundle/Resources/views/themes/admin/language/index.html.twig
  src/bundle/Resources/views/themes/admin/language/list.html.twig
  src/bundle/Resources/views/themes/admin/object_state/list.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/list.html.twig
  src/bundle/Resources/views/themes/admin/section/assigned_content.html.twig
  src/bundle/Resources/views/themes/admin/section/list.html.twig
  src/bundle/Resources/views/themes/admin/section/view.html.twig
  src/bundle/Resources/views/themes/admin/url_wildcard/list.html.twig
  src/bundle/Resources/views/themes/admin/user/policy/list.html.twig
  src/bundle/Resources/views/themes/admin/user/role/list.html.twig
  src/bundle/Resources/views/themes/admin/user/role_assignment/list.html.twig
Labels: QA approved

#1511 EZP-31867: styled filter in sub items
  src/bundle/Resources/public/scss/mixins/_general.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.columns.toggler.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.scss
  src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.columns.toggler.list.element.js
Labels: Ready for review

#1528 EZP-31935: Fixed TypeError error occuring while Section filter in Search is used
  src/lib/View/Filter/AdminSearchViewFilter.php
Labels: Bug, QA approved

#1441 EZP-31783: Fixed embedding Content with read permissions
  src/lib/UniversalDiscovery/Event/Subscriber/RichTextEmbedAllowedContentTypes.php
Labels: QA approved

#1437 EZP-31767: Use version contributor name on dashboard
  src/lib/Pagination/Mapper/AbstractPagerContentToDataMapper.php
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
Labels: QA approved

#1507 EZEE-3215: changed selector container for tooltip to closest
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
Labels: Bug, QA approved

#1539 EZP-31783: Fixed RichTextEmbedAllowedContentTypes subscriber implementation
  src/lib/Tests/UniversalDiscovery/Event/Subscriber/RichTextEmbedAllowedContentTypesTest.php
  src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
  src/lib/UniversalDiscovery/Event/Subscriber/RichTextEmbedAllowedContentTypes.php
Labels: Bug, QA approved

#1506 EZP-31814: Self owner limitation in a security role breaks the UDW
  src/lib/Permission/PermissionChecker.php
Labels: QA approved

#1512 EZP-31462: Added particular message when reset password reason in migration
  composer.json
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/account/forgot_password/index.html.twig
Labels: QA approved

#1462 EZP-31782: PermissionChecker caches policy limitations incorrectly
  src/lib/Permission/PermissionChecker.php
Labels: QA approved

#1476 EZP-31784: Draft autosave feature for Content Edit
  features/standard/ContentCreation.feature
  src/bundle/Controller/ContentController.php
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/autosave.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/config/services/user_settings.yaml
  src/bundle/Resources/public/img/ez-icons.svg
  src/bundle/Resources/public/img/icons/autosave.svg
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/translations/content_edit.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/user_settings.en.xliff
  src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig
  src/lib/Behat/BusinessContext/NavigationContext.php
  src/lib/Behat/PageObject/ContentItemPage.php
  src/lib/Behat/PageObject/ContentUpdateItemPage.php
  src/lib/Event/AutosaveEvents.php
  src/lib/Event/ContentProxyCreateEvent.php
  src/lib/EventListener/ContentProxyCreateDraftListener.php
  src/lib/Form/Processor/Content/AutosaveProcessor.php
  src/lib/Form/Processor/PreviewFormProcessor.php
  src/lib/Tests/Form/Processor/PreviewFormProcessorTest.php
  src/lib/UI/Config/Provider/Autosave.php
  src/lib/UserSetting/Autosave.php
  src/lib/UserSetting/AutosaveInterval.php
Labels: QA approved
