Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-11, with the labels that each got.

#1646 Revert "[Composer] Set metarepo branch for tests and requirements for master branch"
  composer.json
Labels: Ready for review

#1647 [Behat] Adapted tests for the new System Information tab
  features/standard/SystemInfo.feature
  src/lib/Behat/PageObject/SystemInfoPage.php
Labels: Ready for review

#1649 Limited subtree results to 0 in IsWithinCopySubtreeLimit::isSatisfiedBy
  src/lib/Specification/Location/IsWithinCopySubtreeLimit.php
Labels: Improvement, QA approved

#1583 EZP-32157: Added option to choose SA when creating custom alias
  src/bundle/Resources/public/js/scripts/admin.location.add.custom_url.js
  src/bundle/Resources/translations/content_url.en.xliff
  src/bundle/Resources/views/content/tab/url/modal_add_custom_url.html.twig
  src/lib/Form/Data/Content/CustomUrl/CustomUrlAddData.php
  src/lib/Form/EventListener/BuildPathFromRootListener.php
  src/lib/Form/Type/ChoiceList/Loader/SiteAccessChoiceLoader.php
  src/lib/Form/Type/Content/CustomUrl/CustomUrlAddType.php
  src/lib/Siteaccess/AdminSiteaccessPreviewVoter.php
  src/lib/Tests/Form/Data/Content/CustomUrl/CustomUrlAddDataTest.php
Labels: Feature, QA approved

#1653 EZP-32164: Fixed icon paths
  src/bundle/Resources/config/default_parameters.yaml
Labels: Bug

#1654 EZP-32170: Fixed policy limitation custom dropdown
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
  src/bundle/Resources/views/themes/admin/ui/component/custom_dropdown.html.twig
Labels: QA approved

#1650 EZEE-3355: Create extension point in ezimage and ezimageasset fieldtype
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
Labels: QA approved
