Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-04, with the labels that each got.

#1321 EZP-30940: Cannot remove table from richtext field
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-tableremove.js
Labels: Bug, QA approved

#1327 EZP-31120: Image is not replaced in RTE/OE when publishing directly
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-imageupdate.js
Labels: Bug, QA approved

#1328 EZP-31051: Password expired screen incorrectly informs that email has been sent
  src/bundle/Resources/translations/messages.en.xliff
Labels: Bug, Ready for QA

#1330 EZP-30543: Removed Dynamic Settings functionality from kernel
  src/bundle/Controller/BookmarkController.php
  src/bundle/Controller/ContentController.php
  src/bundle/Controller/ContentDraftController.php
  src/bundle/Controller/ContentOnTheFlyController.php
  src/bundle/Controller/ContentTypeController.php
  src/bundle/Controller/ContentTypeGroupController.php
  src/bundle/Controller/LanguageController.php
  src/bundle/Controller/NotificationController.php
  src/bundle/Controller/ObjectStateController.php
  src/bundle/Controller/ObjectStateGroupController.php
  src/bundle/Controller/PolicyController.php
  src/bundle/Controller/RoleAssignmentController.php
  src/bundle/Controller/RoleController.php
  src/bundle/Controller/SearchController.php
  src/bundle/Controller/SectionController.php
  src/bundle/Controller/TrashController.php
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/config/services/dashboard.yaml
  src/bundle/Resources/config/services/events.yaml
  src/bundle/Resources/config/services/menu.yaml
  src/bundle/Resources/config/services/modules/content_tree.yaml
  src/bundle/Resources/config/services/tabs/locationview.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/config/services/universal_discovery_widget.yaml
  src/bundle/Resources/config/services/validators.yaml
  src/bundle/Resources/config/services/views.yaml
  src/bundle/Tests/Templating/Twig/FieldEditRenderingExtensionTest.php
  src/bundle/Tests/Templating/Twig/LimitationValueRenderingExtensionTest.php
  src/lib/EventListener/ViewTemplatesListener.php
  src/lib/Limitation/Templating/LimitationBlockRenderer.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Tab/Dashboard/MyDraftsTab.php
  src/lib/Tab/LocationView/ContentTab.php
  src/lib/Tab/LocationView/PoliciesTab.php
  src/lib/Tab/LocationView/RolesTab.php
  src/lib/Tests/Validator/Constraint/LocationIsWithinCopySubtreeLimitValidatorTest.php
  src/lib/UI/Config/Provider/ScopeParameterBasedValue.php
  src/lib/UI/Dataset/DatasetFactory.php
  src/lib/UI/Module/ContentTree/NodeFactory.php
  src/lib/UniversalDiscovery/Event/Subscriber/UserSelectionAllowedContentTypes.php
  src/lib/Validator/Constraints/LocationIsWithinCopySubtreeLimitValidator.php
Labels: Improvement, Ready for review

#1240 EZP-31195: Set From in twig to empty string
  src/bundle/Resources/views/Security/mail/forgot_user_password.html.twig
Labels: Bug, QA approved

#1337 EZP-31548: Sidebar widget sometimes is overlapped by header
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
Labels: QA approved

#1334 EZP-31398: Field type element overlaps with ez-edit-header__content-type-name
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_main-row.scss
Labels: QA approved

#1340 EZP-31545: Filtered empty idString
  src/bundle/Resources/public/js/scripts/admin.limitation.pick.js
Labels: QA approved

#1271 [Behat] Refactored displaying of application/browser logs
  src/lib/Behat/Helper/Hooks.php
  src/lib/Behat/Helper/TestLogProvider.php
Labels: Ready for review

#1342 EZP-31555: Changed max-height and added overflow to better fit content
  src/bundle/Resources/public/scss/_extra-actions.scss
Labels: QA approved

#1344 EZEE-3093: Changed z-index for tooltips
  src/bundle/Resources/public/scss/core/_custom.tooltip.scss
Labels: Bug, QA approved

#1338 EZP-31539: Link Validation error in Richtext Editor
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved, Ready for MERGE

#1339 Added translations for advanced user permissions in Site Factory
  src/bundle/Resources/translations/forms.en.xliff
Labels: QA approved, Ready for review

#1307 EZP-31459: [UDW] Allowed Content Types are not respected in object relation field
  src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationAllowedContentTypes.php
Labels: Bug, QA approved

#1349 EZP-31578: Fixed phpdoc_var_without_name code style issue
  src/bundle/Controller/LanguageController.php
  src/bundle/Controller/NotificationController.php
  src/lib/Behat/PageObject/LanguagePage.php
  src/lib/Behat/PageObject/ObjectStatePage.php
  src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php
Labels: Ready for MERGE

#1345 EZP-31449: Adapted TranslatablePropertyTransformer to properly handle nulls
  src/lib/Form/DataTransformer/TranslatablePropertyTransformer.php
  src/lib/Tests/Form/DataTransformer/TranslatablePropertyTransformerTest.php
Labels: Bug, QA approved

#1346 EZP-29475: Changes for UDW title
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embed.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embedinline.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embedupdate.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-image.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-imageupdate.js
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
  src/bundle/Resources/translations/alloy_editor.en.xliff
  src/bundle/Resources/translations/universal_discovery_widget.en.xliff
  src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
Labels: QA approved

#1335 EZP-31547: Autowiring fails for CustomTag service when using 3rd party translator bundle
  src/bundle/Resources/config/services/ui_config/mappers.yml
  src/lib/Tests/UI/Config/Mapper/FieldType/RichText/CustomTagTest.php
  src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag.php
Labels: Bug, Ready for QA

#1347 [Behat] Added possibility to read browser logs multiple times
  src/lib/Behat/Helper/TestLogProvider.php
Labels: Ready for review

#1352 EZP-31581: Added missing translation
  src/bundle/Resources/translations/validators.en.xliff
Labels: Bug, QA approved

#1348 EZP-31017: Marked unused and duplicated classes as deprecated
  src/bundle/Resources/config/services/validators.yaml
  src/lib/Form/Data/User/UserPasswordChangeData.php
  src/lib/Form/Data/User/UserPasswordForgotData.php
  src/lib/Form/Data/User/UserPasswordForgotWithLoginData.php
  src/lib/Form/Data/User/UserPasswordResetData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/User/UserPasswordChangeType.php
  src/lib/Form/Type/User/UserPasswordForgotType.php
  src/lib/Form/Type/User/UserPasswordForgotWithLoginType.php
  src/lib/Form/Type/User/UserPasswordResetType.php
  src/lib/Validator/Constraints/FieldSettingsValidator.php
  src/lib/Validator/Constraints/FieldTypeValidator.php
  src/lib/Validator/Constraints/Password.php
  src/lib/Validator/Constraints/PasswordValidator.php
  src/lib/Validator/Constraints/UserPassword.php
  src/lib/Validator/Constraints/UserPasswordValidator.php
  src/lib/Validator/Constraints/ValidatorConfigurationValidator.php
  src/lib/Validator/ValidationErrorsProcessor.php
Labels: QA approved

#1356 EZP-31017: Fixed failing unit tests
  src/bundle/Tests/Templating/Twig/FieldEditRenderingExtensionTest.php
  src/lib/Tests/Validator/Constraint/PasswordValidatorTest.php
  src/lib/Tests/Validator/Constraint/UserPasswordValidatorTest.php
  src/lib/Validator/Constraints/PasswordValidator.php
  src/lib/Validator/Constraints/UserPasswordValidator.php
Labels: Ready for MERGE

#1358 EZP-31600: TableView throws an error when Creator/Contributor is removed for any of the content items
  src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: Bug, QA approved

#1360 Fixed tests matrix in .travis.yml
  .travis.yml
Labels: Bug
