Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-05, with the labels that each got.

#1362 [Behat] EZP-31604: Removed loading Context classes in test env
  src/bundle/DependencyInjection/EzPlatformAdminUiExtension.php
Labels: Ready for review

#1364 [Travis] Changed notification key after rebranding
  .travis.yml
Labels: Ready for review

#1363 [Behat] Added initial search test
  behat_suites.yml
  features/standard/SearchContent.feature
  src/lib/Behat/BusinessContext/SearchContext.php
  src/lib/Behat/PageObject/Page.php
  src/lib/Behat/PageObject/PlatformPageObjectFactory.php
  src/lib/Behat/PageObject/SearchPage.php
Labels: Ready for review

#1361 EZP-31571: Content tree view in UDW
  src/bundle/Controller/Content/ContentTreeController.php
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/scss/ui/modules/_universal.discovery.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tree.scss
  src/bundle/Resources/translations/universal_discovery_widget.en.xliff
  src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
  src/bundle/ui-dev/src/modules/content-tree/components/list-item/list.item.component.js
  src/bundle/ui-dev/src/modules/content-tree/components/list/list.component.js
  src/bundle/ui-dev/src/modules/content-tree/content.tree.module.js
  src/bundle/ui-dev/src/modules/content-tree/services/content.tree.service.js
  src/bundle/ui-dev/src/modules/sub-items/services/bulk.service.js
  src/bundle/ui-dev/src/modules/universal-discovery/bookmarks.tab.module.js
  src/bundle/ui-dev/src/modules/universal-discovery/browse.tab.module.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/pure-toggle-selection-button/pure.toggle.selection.button.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/toggle-selection-button/toggle.selection.button.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/tree-item-toggle-selection-button/tree.item.toggle.selection.button.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/tree-view/tree.view.js
  src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: QA approved

#1365 EZP-31445: Update design of ez-edit-header__details in Editing view
  src/bundle/Resources/public/scss/_content-edit.scss
Labels: QA approved

#1367 EZP-31399: ez-alert-info in Editing view is not aligned with content card
  src/bundle/Resources/views/themes/admin/ui/component/preview_unavailable.html.twig
Labels: QA approved

#1368 EZP-31446: Update design for badge with icon
  src/bundle/Resources/public/scss/_badges.scss
Labels: QA approved

#1370 EZP-31222: Harmonize sidebar ez-context-menu in Editing views
  src/lib/Menu/ContentEditRightSidebarBuilder.php
Labels: QA approved

#1373 EZP-31577: Remove Selected locations panel from UDW when COTF is triggered
  src/bundle/Resources/config/universal_discovery_widget.yaml
Labels: QA approved

#1374 EZP-31626: Fixed error in AlloyEditor when embed location
  src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
  src/bundle/Resources/translations/alloy_editor.en.xliff
Labels: QA approved

#1355 EZP-31560: [Tests] Fixed namespaces not following PSR-4
  src/bundle/Tests/DependencyInjection/Compiler/ComponentPassTest.php
  src/bundle/Tests/DependencyInjection/Compiler/SystemInfoTabGroupPassTest.php
  src/bundle/Tests/DependencyInjection/Compiler/TabPassTest.php
  src/bundle/Tests/DependencyInjection/Compiler/UiConfigProviderPassTest.php
  src/lib/Tests/Behat/BrowserLogFilterTest.php
  src/lib/Tests/Behat/ExtendedTableNodeTest.php
  src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php
  src/lib/Tests/UI/Config/Mapper/FieldType/RichText/CustomTagTest.php
  src/lib/Tests/Validator/Constraint/UserPasswordTest.php
  src/lib/Tests/Validator/Constraint/UserPasswordValidatorTest.php
Labels: Bug, Ready for review

#1369 EZEE-3071: Moved generate key for SiteAccess to new Class
  src/bundle/Resources/config/services/role_form_mappers.yaml
  src/bundle/Resources/config/services/siteaccess.yaml
  src/lib/Limitation/Mapper/SiteAccessLimitationMapper.php
  src/lib/Siteaccess/SiteAccessKeyGenerator.php
  src/lib/Siteaccess/SiteAccessKeyGeneratorInterface.php
  src/lib/Tests/Limitation/Mapper/SiteAccessLimitationMapperTest.php
Labels: Bug, QA approved

#1382 EZP-31641: Unable to manage links in table cells
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-linkedit.js
Labels: QA approved

#1384 EZEE-3020: Close tooltips when item is deleted
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
Labels: QA approved

#1375 EZP-31419: Widgets animation integrated in a single SASS variable
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/_extra-actions.scss
Labels: Ready for QA

#1381 EZP-31439: Harmonize tooltips
  src/bundle/Resources/translations/content_edit.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/link_manager/list.html.twig
  src/bundle/Resources/views/themes/admin/ui/breadcrumbs.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/all_content.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/all_media.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_content.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_draft_list.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_media.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/top_menu_2nd_level.html.twig
  src/bundle/Resources/views/themes/admin/ui/table_header.html.twig
  src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: QA approved

#1390 EZP-31656: Added missing tooltip for exit buttons
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/user/create.html.twig
  src/bundle/Resources/views/themes/admin/user/edit.html.twig
Labels: QA approved

#1353 EZP-31583: Fixed views for Content without Location
  src/bundle/Resources/views/admin/search/search_table_row.html.twig
  src/bundle/Resources/views/content/relation.html.twig
  src/bundle/Resources/views/content/tab/relations/table_relations.html.twig
  src/bundle/Resources/views/content/tab/relations/table_relations_reverse.html.twig
Labels: Bug, QA approved

#1383 EZP-30925: Added 'LanguageLimitation' functionality to 'Translations' tab
  src/lib/UI/Value/ValueFactory.php
Labels: Improvement, QA approved

#1385 [Behat] Added support for Form fieldtype
  src/lib/Behat/PageElement/Fields/EzFieldElement.php
Labels: Ready for review

#1389 [Behat] Removed clearing the field before filling input
  src/lib/Behat/PageElement/Fields/DefaultFieldElement.php
Labels: Ready for MERGE

#1391 Fixed EZP-31639: media and file fields not loaded correctly in edit mode
  src/bundle/Resources/config/services.yml
  src/lib/EventListener/ContentDownloadRouteReferenceListener.php
  src/lib/Tests/EventListener/ContentDownloadRouteReferenceListenerTest.php
Labels: Bug, QA approved

#1380 EZP-31340: Corrected outdated choiceloaders (introduced Symfony bugfix)
  src/lib/Form/Type/ChoiceList/Loader/BaseChoiceLoader.php
  src/lib/Form/Type/ChoiceList/Loader/ContentCreateContentTypeChoiceLoader.php
  src/lib/Form/Type/ChoiceList/Loader/ContentCreateLanguageChoiceLoader.php
  src/lib/Form/Type/ChoiceList/Loader/ContentTypeChoiceLoader.php
Labels: Bug, QA approved
