Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-03, with the labels that each got.

#1260 EZEE-2971: Added dark icon color
  src/bundle/Resources/public/scss/_icons.scss
Labels: QA approved

#1263 EZP-31416: Remove selection bar on the right from UDW (Browse)
  src/bundle/Resources/config/universal_discovery_widget.yaml
  src/lib/Behat/BusinessContext/ContentViewContext.php
  src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
Labels: QA approved

#1262 EZP-31421: Change class fieldtype-container to toggle-group
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.card.toggle.group.js
  src/bundle/Resources/public/js/scripts/admin.contenttype.fieldtype.js
  src/bundle/Resources/public/scss/_card.scss
  src/bundle/Resources/views/themes/admin/content_type/create.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
  src/lib/Behat/PageElement/AdminUpdateForm.php
Labels: QA approved

#1264 EZP-31430: Can't select existing object for ImageAsset field
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
Labels: QA approved

#1261 EZP-29948: Improved dates select on the search content site
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/translations/content_create.en.xliff
  src/bundle/Resources/translations/search.en.xliff
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
Labels: QA approved

#1266 EZP-31407: Removed title from header
  src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
Labels: QA approved

#1267 EZP-31066: Error when clicking the link in RTE
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base-fixed.js
Labels: Bug, QA approved

#1265 EZP-29947: Added search criteria tags
  src/bundle/Controller/SearchController.php
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/scss/_search-criteria-tags.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
  src/bundle/Resources/views/themes/admin/ui/search_tag.html.twig
Labels: QA approved

#1268 EZP-31438: Added tooltips to site builder
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
  src/bundle/Resources/views/themes/admin/content/modal/draft_conflict.html.twig
Labels: QA approved

#1148 EZP-31118: Introduced strict types for ContentService
  src/lib/Form/DataTransformer/ContentInfoTransformer.php
  src/lib/Form/DataTransformer/VersionInfoTransformer.php
  src/lib/Strategy/NotificationTwigStrategy.php
  src/lib/Tests/Form/DataTransformer/ContentInfoTransformerTest.php
  src/lib/Tests/Form/DataTransformer/VersionInfoTransformerTest.php
  src/lib/View/Filter/ContentTranslateViewFilter.php
Labels: Bug, QA approved

#1272 EZP-31477: Fixed loading Site Accesses on limitation list
  src/bundle/Resources/config/services/role_form_mappers.yaml
  src/lib/Limitation/Mapper/SiteAccessLimitationMapper.php
  src/lib/Tests/Limitation/Mapper/SiteAccessLimitationMapperTest.php
Labels: Improvement, QA approved

#1244 EZEE-2930: Added form_before and form_after to correcctly generate data for Form Builder
  src/bundle/Resources/views/content/content_edit/user_create.html.twig
  src/bundle/Resources/views/content/content_edit/user_edit.html.twig
Labels: Bug, QA approved

#1278 EZEE-3029: Added basic policy for version comparison
  src/bundle/Resources/translations/forms.en.xliff
Labels: Ready for review

#1284 EZP-31491: As a developer, I want to add icon to top menu entry
  src/bundle/Resources/views/themes/admin/ui/menu/top_menu_2nd_level.html.twig
Labels: Ready for QA

#1283 EZEE-3030: Links containing 'ezlocation` or 'ezcontent' keywords break RTE validation on paste
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved

#1275 EZP-31448: Introduced strict types for LocationService
  src/lib/Form/DataTransformer/LocationTransformer.php
  src/lib/Form/EventListener/BuildPathFromRootListener.php
  src/lib/Form/Type/Content/Translation/TranslationAddType.php
Labels: Bug

#1281 EZP-31482: Introduce strict types for FieldType & VO
  src/lib/UI/Value/User/Policy.php
  src/lib/UI/Value/User/Role.php
Labels: Bug

#1289 Adjusted unit tests to recent changes
  src/bundle/Tests/Templating/Twig/LimitationMock.php
  src/lib/Tests/EventListener/SetViewParametersListenerTest.php
  src/lib/Tests/Form/Data/FormMapper/ContentTranslationMapperTest.php
  src/lib/Tests/Form/DataTransformer/LocationsTransformerTest.php
  src/lib/Tests/Validator/Constraint/UserPasswordValidatorTest.php
Labels: Bug

#1276 EZP-31220: As a Developer I'd like eZ Platform packages to be compatible with Symfony 5
  composer.json
  src/bundle/Controller/ContentOnTheFlyController.php
  src/bundle/DependencyInjection/EzPlatformAdminUiExtension.php
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/dashboard.yaml
  src/bundle/Resources/config/services/events.yaml
  src/bundle/Resources/config/services/feature_contexts.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/translations/time_diff.en.xliff
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
  src/bundle/Resources/views/themes/admin/content_type/tab/translations.html.twig
  src/bundle/Resources/views/themes/admin/link_manager/edit.html.twig
  src/bundle/Resources/views/themes/admin/link_manager/list.html.twig
  src/bundle/Resources/views/themes/admin/link_manager/view.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
  src/bundle/Templating/Twig/TimeDiffExtension.php
  src/lib/Behat/BusinessContext/ContentViewContext.php
  src/lib/Behat/BusinessContext/NavigationContext.php
  src/lib/Behat/BusinessContext/UDWContext.php
  src/lib/Component/Dashboard/EzInfoTwigComponent.php
  src/lib/EventListener/AdminExceptionListener.php
  src/lib/EventListener/CredentialsExpirationWarningListener.php
  src/lib/Form/DataTransformer/FieldType/AbstractBinaryBaseTransformer.php
  src/lib/Form/Extension/HelpMultilineMessageExtension.php
  src/lib/Form/TrashLocationOptionProvider/HasAssetRelation.php
  src/lib/Form/TrashLocationOptionProvider/HasChildren.php
  src/lib/Form/TrashLocationOptionProvider/HasReverseRelations.php
  src/lib/Form/TrashLocationOptionProvider/HasUniqueAssetRelation.php
  src/lib/Form/Type/Location/LocationTrashType.php
  src/lib/Menu/MenuItemFactory.php
  src/lib/Menu/Voter/LocationVoter.php
  src/lib/Tab/Dashboard/EveryoneContentTab.php
  src/lib/Tab/Dashboard/EveryoneMediaTab.php
  src/lib/Tab/Dashboard/MyContentTab.php
  src/lib/Tab/Dashboard/MyMediaTab.php
  src/lib/UI/Service/DateTimeFormatter.php
  src/lib/UI/Service/DateTimeFormatterInterface.php
Labels: Ready for MERGE

#1291 Fixed search in case when user doesn't have section/view permission
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
Labels: Bug

#1292 Fixed Location ID type-casting issues in Policy Limitation update
  src/bundle/Templating/Twig/PathStringExtension.php
  src/lib/Form/DataTransformer/UDWBasedValueModelTransformer.php
Labels: Bug

#1293 EZP-31500: Menu entry icon is too big
  src/bundle/Resources/views/themes/admin/ui/menu/top_menu_2nd_level.html.twig
Labels: QA approved

#1295 EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel
  composer.json
  features/standard/SystemInfo.feature
Labels: Improvement, Ready for review

#1294 EZP-31488: Wrong header when editing on the fly
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
Labels: Bug, QA approved

#1296 EZP-31467: Delete draft message is misaligned
  src/bundle/Resources/public/scss/_modals.scss
Labels: QA approved

#1300 EZP-31270: Fixed access to Back Office when user has CT Limitation on content create
  src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php
Labels: QA approved

#1299 EZP-31447: Remove button in search criteria for 'creator' field is not displayed propertly
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
Labels: QA approved

#1308 EZEE-3052: Casted string id from form to int
  src/lib/Form/DataTransformer/UserTransformer.php
Labels: Ready for QA

#1309 EZP-31465: Fixed invalid redirect after User deletion
  src/bundle/Controller/User/UserDeleteController.php
Labels: Bug, QA approved, Ready for review

#1274 EZP-31417: Prevent execute querySelectorAll on null in tooltips helper
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
Labels: QA approved

#1288 EZP-31079: Provided validation for email uniqueness and login pattern
  src/bundle/Resources/translations/content_type.en.xliff
  src/lib/FieldType/Mapper/UserAccountFormMapper.php
Labels: QA approved

#1311 EZP-31490: Used new translation specific content route
  src/bundle/Resources/views/themes/admin/content/tab/content.html.twig
  src/lib/EventListener/RequestAttributesListener.php
Labels: QA approved

#1312 EZP-31458: Fixed calendar date picker render event
  src/bundle/Resources/public/scss/_filters.scss
Labels: Bug, Ready for review

#1310 EZP-31484: Changed z-index 1 to 0 for checkbox
  src/bundle/Resources/public/scss/_mixins.scss
Labels: Bug, Ready for review

#1280 EZEE-2988: added scheduler for hiding content
  src/bundle/Resources/public/js/scripts/admin.picker.js
  src/bundle/Resources/public/scss/_alerts.scss
  src/bundle/Resources/public/scss/_picker.scss
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/lib/Menu/ContentRightSidebarBuilder.php
Labels: Feature

#1305 EZP-31412: Inconsistent date format in the relation field type table
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
Labels: Ready for QA

#1313 EZP-31515: Schedule later widget is hiding after clicking calendar input
  src/bundle/Resources/public/scss/_flatpickr.scss
  src/bundle/Resources/public/scss/ezplatform.scss
Labels: QA approved

#1210 EZEE 2961 Added an additional condition to edit draft button to prevent error when a user is deleted
  src/bundle/Resources/views/content/tab/versions/table.html.twig
Labels: Bug, QA approved

#1306 EZP-31403: Widget header is not visible
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
  src/bundle/Resources/public/scss/_main-row.scss
Labels: QA approved

#1317 EZEE-3067: Confirm button is covered by date picker in schedule hide
  src/bundle/Resources/public/js/scripts/admin.picker.js
Labels: QA approved

#1316 [Behat] Changed to comparing keywords ignoring their order
  src/lib/Behat/PageElement/Fields/Keywords.php
Labels: Ready for review

#1319 EZP-31526: UDW crushes when trying to collapse first row in bookmark tab
  src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js
Labels: QA approved

#1320 EZEE-3066: changed height for modal close button
  src/bundle/Resources/public/scss/ui/modules/common/_popup.scss
Labels: QA approved

#1322 EZP-31532: Update design of edit translation widget in search and dashboard
  src/bundle/Resources/public/js/scripts/button.translation.edit.js
  src/bundle/Resources/public/scss/_translation-selector.scss
  src/bundle/Resources/views/themes/admin/ui/edit_translation_button.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/list_item.html.twig
Labels: QA approved

#1315 EZP-31521: Fixed sorting logic listener for ordered menu items
  src/lib/Menu/Listener/ReorderByOrderNumberListener.php
  src/lib/Tests/Menu/ReorderByOrderNumberListenerTest.php
Labels: QA approved

#1241 EZP-31383: As an Administrator I want to copy roles
  src/bundle/Controller/RoleController.php
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/services/menu.yaml
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/translations/role.en.xliff
  src/bundle/Resources/views/themes/admin/user/role/copy.html.twig
  src/bundle/Resources/views/themes/admin/user/role/list.html.twig
  src/lib/Form/Data/Role/RoleCopyData.php
  src/lib/Form/DataMapper/RoleCopyMapper.php
  src/lib/Form/Type/Role/RoleCopyType.php
  src/lib/Menu/Admin/Role/RoleCopyRightSidebarBuilder.php
  src/lib/Menu/Event/ConfigureMenuEvent.php
Labels: Feature, QA approved

#1325 EZP-29354: Language information in table header is not centered
  src/bundle/Resources/views/admin/language/view.html.twig
Labels: QA approved

#1326 EZP-31408: 'This Location has no Sub-items' msg is displayed above location
  src/bundle/Resources/public/scss/ui/modules/content-tree/_list.scss
  src/bundle/Resources/public/scss/ui/modules/content-tree/_main.scss
  src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
  src/bundle/ui-dev/src/modules/content-tree/components/list/list.component.js
Labels: QA approved
