Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-06, with the labels that each got.

#1255 EZP-31405 - fix embed image link removal
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: QA approved

#1393 [Behat] Changed how the field value is set for DefaultFieldElement
  src/lib/Behat/PageElement/Fields/DefaultFieldElement.php
Labels: Ready for review

#1397 [Behat] Added ContentContext to adminuimodules suite
  behat_suites.yml
Labels: Ready for review

#1394 EZP-31668: Introduced new key for user related pagination configuration
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
Labels: QA approved

#1388 EZP-31575: When in Media section show Sub-Items grid view by default
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
  src/lib/Behat/BusinessContext/NavigationContext.php
  src/lib/Behat/PageElement/PlatformElementFactory.php
  src/lib/Behat/PageElement/SubItemsList.php
  src/lib/Behat/PageElement/Tables/ItemsList.php
  src/lib/Behat/PageElement/Tables/SubitemsGridList.php
  src/lib/Behat/PageElement/Tables/Table.php
  src/lib/Behat/PageObject/ContentItemPage.php
  src/lib/UI/Config/Provider/Locations.php
Labels: Ready for QA

#1401 [Behat] Adjusted language picker selector
  src/lib/Behat/PageElement/LanguagePicker.php
Labels: Ready for review

#1399 [Behat] Moved and consolidated Trash tests into one feature
  features/standard/ContentManagement.feature
  features/standard/Trash.feature
Labels: Ready for review

#1386 EZP-31344: Added border and toggler for preview content
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
  src/bundle/Resources/public/js/scripts/admin.location.tooglecontentpreview.js
  src/bundle/Resources/public/scss/_field-group.scss
  src/bundle/Resources/public/scss/_tabs.scss
  src/bundle/Resources/public/scss/_warning-icon.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/content.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/warning_icon.html.twig
Labels: QA approved

#1403 [Behat] Updated selector for specific field in Content edit
  src/lib/Behat/PageElement/ContentUpdateForm.php
Labels: Ready for review

#1405 EZEE-3167: Added generation of Site Access name for Sites
  src/bundle/Controller/ContentController.php
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/config/services/siteaccess.yaml
  src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
  src/lib/Siteaccess/NonAdminSiteaccessResolver.php
  src/lib/Siteaccess/SiteAccessNameGenerator.php
  src/lib/Siteaccess/SiteAccessNameGeneratorInterface.php
  src/lib/Siteaccess/SiteaccessResolver.php
  src/lib/Siteaccess/SiteaccessResolverInterface.php
Labels: Bug, QA approved

#1407 EZP-31680: Added UDW Search language filter
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss
  src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
  src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
Labels: Improvement, QA approved

#1402 EZP-31583: Fixed views for Content without Location
  src/bundle/Resources/views/themes/admin/content/relation.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/relations/table_relations.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/relations/table_relations_reverse.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/list_item.html.twig
Labels: Bug, QA approved

#1408 EZP-31650: Added search in trash
  features/standard/Trash.feature
  src/bundle/Controller/TrashController.php
  src/bundle/Resources/config/bazinga_js_translation.yaml
  src/bundle/Resources/config/services/forms.yaml
  src/bundle/Resources/config/services/query_types.yaml
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/js/scripts/admin.trash.list.js
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/public/scss/_trash-search-form.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/translations/date_period.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/trash.en.xliff
  src/bundle/Resources/translations/trash_ui.en.xliff
  src/bundle/Resources/views/themes/admin/trash/list.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/lib/Form/Data/Search/TrashSearchData.php
  src/lib/Form/Data/TrashItemData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Factory/TrashFormFactory.php
  src/lib/Form/Type/ChoiceList/Loader/DatePeriodChoiceLoader.php
  src/lib/Form/Type/Content/SortType.php
  src/lib/Form/Type/Search/TrashSearchType.php
  src/lib/Form/Type/Trash/ChoiceList/Loader/SearchContentTypeChoiceLoader.php
  src/lib/QueryType/TrashSearchQueryType.php
Labels: QA approved

#1411 Fixed code style issues in SearchContentTypeChoiceLoader
  src/lib/Form/Type/Trash/ChoiceList/Loader/SearchContentTypeChoiceLoader.php
Labels: Bug
