Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2020-01, with the labels that each got.

#1171 EZEE-2946: Added missing html nodes for characters counter in the RichText twig template
  src/bundle/Resources/views/form_fields.html.twig
Labels: QA approved

#1179 EZP-31245: Editing link in paragraph containing more lines ends up with JS error
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-image-link.js
Labels: Bug, QA approved

#1180 EZP-31266: Changing items order in Relation List doesn't work on Firefox
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
Labels: Bug, QA approved

#1182 EZP-31263: trash button set to inactive after deleting relation items
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
Labels: Bug, QA approved

#1190 EZP-31291: Fix Content Type creation filter on certain words such as "File"
  src/bundle/Resources/public/js/scripts/sidebar/instant.filter.js
Labels: Bug, QA approved

#1186 EZEE-2853: Fixed using preferedded date in scheduler
  src/bundle/Resources/public/js/scripts/admin.picker.js
Labels: QA approved

#1189 EZP-31128: removed blank space under notification box
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
Labels: QA approved

#1188 EZP-29550: Added display inactive trash icon on a empty trash list
  src/bundle/Resources/views/admin/trash/list.html.twig
Labels: Bug, QA approved

#1187 EZP-31241: Changed behaviour for showing not checked value in checkbox
  src/bundle/Resources/views/content/content_view_fields.html.twig
Labels: QA approved

#1183 EZP-29249: Changed texts in relation fields
  src/bundle/Controller/LocationController.php
  src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
  src/bundle/Resources/translations/ezrepoforms_content.en.xliff
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/fieldtypes/edit/ezobjectrelation.html.twig
  src/bundle/Resources/views/fieldtypes/edit/ezobjectrelationlist.html.twig
  src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
Labels: QA approved

#1175 EZP-31250: Set text alignment in tables as top
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/translations/tab.html.twig
Labels: QA approved

#1200 EZEE-2956: Auto confirm is not enabled in UDW for Embed block
  src/bundle/Resources/config/universal_discovery_widget.yaml
Labels: Bug, QA approved

#1192 EZEE-2914: Custom inline style does not update textarea after click on
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-styleslistitem.js
  webpack.config.js
Labels: Bug, QA approved

#1172 EZP-31148: Harmonize Badges by adding them as new UI component
  src/bundle/Resources/public/scss/_badges.scss
  src/bundle/Resources/public/scss/ezplatform.scss
Labels: QA approved

#1185 EZP-31277: added server timezone offset support for ezdate widget
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
  src/bundle/Resources/views/fieldtypes/edit/ezdate.html.twig
Labels: Bug, QA approved

#1194 EZP-31295: Unable to use default empty custom CSS class in the OE
  src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-attributes-update.js
Labels: QA approved

#1151 EZP-31321: Dropped injecting zero-width space into ezembed(inline) elements
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-custom-tag.js
  src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-embed.js
Labels: Improvement, QA approved

#1203 EZP-30339: Added animation-fill-mode: forwards to animation of add/remove boo…
  src/bundle/Resources/public/scss/_add-to-bookmarks.scss
  src/bundle/Resources/public/scss/_animations.scss
Labels: QA approved

#1201 EZEE-2950: Removed drag-mock injection
  src/lib/Behat/Helper/UtilityContext.php
  src/lib/Behat/lib/drag-mock.js
Labels: Ready for MERGE

#1206 EZP-30860: Added blockqoute formatting for field preview
  src/bundle/Resources/public/scss/_general.scss
Labels: QA approved

#1193 EZP-31186: Change widgets layout
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_extra-actions.scss
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/_instant-filter.scss
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig
  src/bundle/Resources/views/themes/admin/content/widget/content_edit.html.twig
  src/bundle/Resources/views/themes/admin/content/widget/user_edit.html.twig
  src/bundle/Resources/views/themes/admin/content_type/widget/content_type_edit.html.twig
Labels: QA approved

#1204 EZP-29955: Added outline: none; for [X] button in notifications popup
  src/bundle/Resources/public/scss/_notifications-modal.scss
Labels: Bug, QA approved

#1202 EZP-30403: Formated date on search content site using ez.helpers.timezone
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
Labels: QA approved, Ready for QA

#1209 EZP-31322: Fixed padding for tabs
  src/bundle/Resources/views/themes/admin/ui/tab/location_view.html.twig
Labels: Improvement, QA approved

#1207 EZP-30850: Changed float to margin for custom tag
  src/bundle/Resources/public/scss/_custom-tag.scss
Labels: QA approved

#1205 EZP-31182: As an Editor I want to access Version compare from the versions table
  src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
Labels: QA approved, Ready for MERGE

#1199 EZP-31261: Rebuild endpoints to use proper root location per configuration
  src/bundle/Controller/UniversalDiscoveryController.php
  src/bundle/Resources/config/services/query_types.yaml
  src/lib/QueryType/LocationPathQueryType.php
Labels: QA approved

#1211 EZP-31297: Narrowed user preferences values to the available list
  src/lib/Form/Type/ChoiceList/Loader/BaseChoiceLoader.php
Labels: Bug, QA approved, Ready for QA

#1212 EZP-31339: Dropped default config enforcement for ContentTree parser
  src/bundle/DependencyInjection/Configuration/Parser/Module/ContentTree.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
Labels: Bug, QA approved

#1196 EZP-30908: Changed date format for datetime input when we create article
  src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
  src/bundle/Resources/public/scss/_mixins.scss
  src/lib/Behat/PageElement/Fields/DateAndTime.php
Labels: QA approved

#1214 EZP-31314: Added transition to animation open/close for content tree
  src/bundle/Resources/public/scss/_content-tree.scss
Labels: Improvement, QA approved, Ready for QA

#1216 Changed back to previous typehint in constructor
  src/lib/Behat/PageElement/Fields/DateAndTime.php
Labels: Ready for review
