Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-04, with the labels that each got.

#1733 EZP-32395: Fixed location visibility due to kept BC
  src/bundle/Resources/views/content/locationview.html.twig
Labels: Bug, Ready for MERGE

#1734 EZEE-3496: Remove buttons disappear from set data inputs
  src/bundle/Resources/public/scss/_picker.scss
Labels: QA approved

#1735 IBX-159: Added pagination in locations tab
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
  src/lib/Tab/LocationView/LocationsTab.php
  src/lib/UI/Value/Content/Location/Mapper.php
Labels: QA approved

#1729 [EZP-32397] Removed logic from ezdate.html.twig
  src/bundle/Resources/views/fieldtypes/edit/ezdate.html.twig
Labels: Bug, QA approved

#1736 addedd ezsettings.default.content_tree_module.contextual_tree_root_lo cation_ids parameter to ezplatform_default_settings.yaml and deleted unused ezplatform_default_settings.yml file
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/bundle/Resources/config/ezplatform_default_settings.yml
Labels: Ready for review

#1737 IBX-183: Fixed accessing Tabs with spaces and special characters
  src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
Labels: Bug, QA approved

#1741 IBX-251: Replaced eZ\Publish\API\Repository\ContentService::loadReverseRelations usages
  src/bundle/Controller/ContentViewController.php
  src/lib/Specification/Content/ContentHaveUniqueRelation.php
Labels: Bug, QA approved

#1745 EZP-32400: Fixed displaying anchors for tables
  src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
Labels: Bug, QA approved

#1742 IBX-247: UDW - cannot select item
  src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.leaf.js
Labels: Bug, QA approved, Ready for MERGE

#1746 Boosted performance of NodeFactory
  src/bundle/Resources/config/services/modules/content_tree.yaml
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Ready for QA
