Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-09, with the labels that each got.

#1882 [Behat] Fixed Richtext button positions after widget redesign
  src/lib/Behat/Component/Fields/RichText.php
Labels: Ready for review

#1890 [Behat] Corrected error message for missing user notification
  src/lib/Behat/Component/UserNotificationPopup.php
Labels: Ready for review

#1845 IBX-862: Fixed translation action originating from non-main Location
  src/bundle/Controller/TranslationController.php
  src/bundle/Resources/config/routing.yml
Labels: Bug, QA approved

#1880 IBX-808: As an Editor, I want to be able to reset starting location for ezobjectrelation FieldType
  src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js
  src/bundle/Resources/translations/ezrepoforms_content_type.en.xliff
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
Labels: Improvement, QA approved

#1886 IBX-902: Fixed field groups in content on the fly edit
  composer.json
  src/bundle/Controller/ContentOnTheFlyController.php
Labels: QA approved

#1894 IBX-862: Fixed translation action originating from non-main Location
  src/bundle/Controller/ContentEditController.php
  src/bundle/Controller/TranslationController.php
  src/bundle/Resources/config/routing.yaml
  src/lib/Event/ContentProxyTranslateEvent.php
  src/lib/EventListener/ContentProxyCreateDraftListener.php
  src/lib/Tests/EventListener/ContentProxyCreateDraftListenerTest.php
Labels: Bug, Ready for MERGE, QA approved

#1895 IBX-951: Second-stage of the main menu not clickable when in trash or…
  src/lib/Menu/MainMenuBuilder.php
Labels: QA approved

#1885 IBX-952: Added chosen Location to Translation Choice form
  src/bundle/Controller/ContentViewController.php
  src/lib/Form/Type/ChoiceList/Loader/ContentEditTranslationChoiceLoader.php
  src/lib/Form/Type/Content/Translation/TranslationAddType.php
Labels: Bug, Ready for MERGE

#1899 IBX-1011: Fixing hide all tooltip after click in side menu
  src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
Labels: QA approved

#1896 IBX-955: clicked buttons links
  src/bundle/Resources/public/scss/_general.scss
Labels: QA approved

#1900 IBX-954: Fixed missing Close button redirection to cancel action
  src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
Labels: QA approved

#1904 IBX-1044: Add ibexa-icon 8px & 12px variants
  src/bundle/Resources/public/scss/_icons.scss
Labels: Ready for review, Doc needed

#1911 IBX-964: Added offset to timestamp
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
Labels: Bug, Ready for MERGE, QA approved

#1903 IBX-940: Dropdown in tab is partly hidden
  src/bundle/Resources/public/js/scripts/core/dropdown.js
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/Resources/views/themes/admin/ui/component/dropdown.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/dropdown_item.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/dropdown_selected_item.html.twig
  src/lib/Behat/Component/Fields/Country.php
  src/lib/Behat/Page/RoleUpdatePage.php
Labels: Ready for MERGE, QA approved

#1836 IBX-823: Enable/Disable validation form before send workflow review
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
Labels: Improvement, Ready for MERGE, QA approved

#1928 [Behat] Disabled ezmaplocation tests
  features/standard/ContentTypeFields.feature
Labels: Ready for review

#1889 [CI] Added job for wrong target branch detection
  .github/workflows/pr_check.yaml
Labels: Ready for review

#1924 Fixed issues in test PHP namespace
  composer.json
  phpunit.xml
  tests/lib/REST/Input/ContentType/FieldDefinitionCreateTest.php
  tests/lib/REST/Input/ContentType/FieldDefinitionDeleteTest.php
  tests/lib/REST/Input/ContentType/FieldDefinitionReorderTest.php
Labels: Ready for review

#1931 IBX-792: Fixed class using new namespace registered via resource
  src/bundle/Resources/config/services/forms.yaml
Labels: Ready for review

#1923 IBX-895: As an Editor, I want to see SubItems redesigned
  src/bundle/Resources/public/js/scripts/admin.table.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/public/scss/ui/modules/_multi.file.upload.scss
  src/bundle/Resources/public/scss/ui/modules/_sub.items.list.scss
  src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_main.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_action.btn.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_grid.view.item.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_grid.view.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_language.selector.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_no.items.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.columns.toggler.list.element.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.columns.toggler.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_view.switcher.button.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_view.switcher.scss
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/translations/content_create.en.xliff
  src/bundle/Resources/translations/content_edit.en.xliff
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/translations/ezplatform_content_forms_content.en.xliff
  src/bundle/Resources/translations/ezplatform_content_forms_policies.en.xliff
  src/bundle/Resources/translations/ezplatform_url_wildcard.en.xliff
  src/bundle/Resources/translations/fieldtypes_edit.en.xliff
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/language.en.xliff
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/multi_file_upload.en.xliff
  src/bundle/Resources/translations/notifications.en.xliff
  src/bundle/Resources/translations/object_state.en.xliff
  src/bundle/Resources/translations/role.en.xliff
  src/bundle/Resources/translations/search.en.xliff
  src/bundle/Resources/translations/section.en.xliff
  src/bundle/Resources/translations/sub_items.en.xliff
  src/bundle/Resources/translations/user_create.en.xliff
  src/bundle/Resources/translations/user_edit.en.xliff
  src/bundle/Resources/translations/user_settings.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
  src/bundle/Resources/views/themes/admin/content_type/field_definitions_empty_group.html.twig
  src/bundle/ui-dev/src/modules/common/tooltip-popup/tooltip.popup.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/drop-area/drop.area.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/css/multi.file.upload.module.css
  src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
  src/bundle/ui-dev/src/modules/sub-items/components/action-btn/action.btn.js
  src/bundle/ui-dev/src/modules/sub-items/components/grid-view/grid.view.item.component.js
  src/bundle/ui-dev/src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.columns.toggler.js
  src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.columns.toggler.list.element.js
  src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.component.js
  src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.item.component.js
  src/bundle/ui-dev/src/modules/sub-items/components/view-switcher/view.switcher.button.component.js
  src/bundle/ui-dev/src/modules/sub-items/components/view-switcher/view.switcher.component.js
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
  src/lib/Behat/Component/SubItemsList.php
Labels: Improvement, Ready for review

#1934 [Behat] Removed logic based on exceptions in Table searching
  src/lib/Behat/Component/Table/Table.php
Labels: Ready for review

#1901 IBX-1013: Fixed top header and disabled animation for scrolling side menu
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
  src/bundle/Resources/public/js/scripts/button.translation.edit.js
  src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
  src/bundle/Resources/public/scss/_extra-actions.scss
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/_main-container.scss
  src/bundle/Resources/public/scss/_main-header.scss
  src/bundle/Resources/public/scss/_main-menu.scss
  src/lib/Behat/Component/SubItemsList.php
Labels: QA approved
