Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-07, with the labels that each got.

#1787 IBX-664: changed desc for pagination.viewing trans
  src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
Labels: Bug, QA approved

#1791 IBX-695: Added ignore to trans id 'interval.format.%s'
  src/bundle/Templating/Twig/FormatIntervalExtension.php
Labels: Bug, Ready for review

#1783 IBX-579: Behat coverage for user with CT limitation adding location
  features/personas/AddLocation.feature
  src/lib/Behat/BusinessContext/ContentViewContext.php
  src/lib/Behat/PageElement/ContentTypePicker.php
  src/lib/Behat/PageObject/ContentItemPage.php
Labels: Ready for review

#1788 IBX-691: As a Developer, I want to have reusable popup menu component
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js
  src/bundle/Resources/public/js/scripts/core/adaptive.items.js
  src/bundle/Resources/public/js/scripts/core/popup.menu.js
  src/bundle/Resources/public/scss/_popup-menu.scss
  src/bundle/Resources/public/scss/_tabs.scss
  src/bundle/Resources/views/themes/admin/ui/component/popup_menu/popup_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_header.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_tab.html.twig
Labels: Improvement

#1785 IBX-587: There are some inconsistencies in buttons: ez-btn--primary and ez-btn--base-dark
  src/bundle/Resources/public/scss/_buttons.scss
Labels: Bug, QA approved

#1795 IBX-725: CredentialsExpiredListener makes it impossible to render a content from using CLI
  src/lib/EventListener/CredentialsExpiredListener.php
Labels: Bug, QA approved

#1797 IBX-737: Disabled buttons in Context Menu should be purple instead of grey
  src/bundle/Resources/public/scss/_buttons.scss
Labels: Bug, Ready for QA

#1804 [Behat] Adapted tests to the redesign
  src/lib/Behat/Page/ContentViewPage.php
  src/lib/Behat/Page/DashboardPage.php
  src/lib/Behat/Page/ObjectStateGroupPage.php
  src/lib/Behat/Page/SectionPage.php
Labels: Ready for review

#1807 Fixed reference to tab_pane.html.twig
  src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
Labels: Bug

#1811 [Behat] Fixed tab switching in Content View
  src/lib/Behat/Page/ContentViewPage.php
Labels: Ready for review

#1802 [Behat] Changed ContentDraft tests to use article Content Type
  features/standard/ContentDraft.feature
Labels: Ready for review

#1805 IBX-759: Fixed wrong class taken to calculate toolbar's width
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
Labels: Bug, QA approved

#1809 [Behat] Use standard mode for setup phase
  .travis.yml
Labels: Ready for review

#1812 IBX-264: [Behat] Fixed entering values in AdminUI forms
  src/lib/Behat/Page/AdminUpdateItemPage.php
Labels: Ready for review

#1814 IBX-264: [Behat] Make sure date picker is loaded before interacting with it.
  src/lib/Behat/Component/Fields/Date.php
  src/lib/Behat/Component/Fields/DateAndTime.php
  src/lib/Behat/Component/Fields/Time.php
Labels: Ready for review

#1799 IBX-580: Added deleted location limitation role access scenario
  behat_suites.yml
  features/standard/Roles.feature
Labels: Ready for review

#1803 [Behat] Fixed PHPUnit 9 deprecations and class usage casing
  src/lib/Behat/BrowserContext/NotificationContext.php
  src/lib/Behat/Component/ContentItemAdminPreview.php
  src/lib/Behat/Component/Fields/Authors.php
  src/lib/Behat/Component/Fields/Checkbox.php
  src/lib/Behat/Component/Fields/ContentQuery.php
  src/lib/Behat/Component/Fields/ContentRelationMultiple.php
  src/lib/Behat/Component/Fields/ContentRelationSingle.php
  src/lib/Behat/Component/Fields/Date.php
  src/lib/Behat/Component/Fields/DateAndTime.php
  src/lib/Behat/Component/Fields/FieldTypeComponent.php
  src/lib/Behat/Component/Fields/File.php
  src/lib/Behat/Component/Fields/Image.php
  src/lib/Behat/Component/Fields/ImageAsset.php
  src/lib/Behat/Component/Fields/Keywords.php
  src/lib/Behat/Component/Fields/MapLocation.php
  src/lib/Behat/Component/Fields/Matrix.php
  src/lib/Behat/Component/Fields/Media.php
  src/lib/Behat/Component/Fields/NonEditableField.php
  src/lib/Behat/Component/Fields/RichText.php
  src/lib/Behat/Component/Fields/Selection.php
  src/lib/Behat/Component/Fields/Time.php
  src/lib/Behat/Component/Fields/URL.php
  src/lib/Behat/Component/Fields/User.php
  src/lib/Behat/Page/ContentViewPage.php
Labels: Ready for review

#1813 [Behat] Adjusted tab CSS selector on the Dashboard
  src/lib/Behat/Page/DashboardPage.php
Labels: Ready for review

#1815 Temporary fix content position by added right margin, needed for tests
  src/bundle/Resources/public/scss/_general.scss
Labels: Ready for review

#1820 [Behat] Changed flatpickr locator to a more specific one
  src/lib/Behat/Component/DateAndTimePopup.php
Labels: Ready for review

#1822 [Behat] Fixed inline date picker interactions
  src/lib/Behat/Component/DateAndTimePopup.php
  src/lib/Behat/Component/Fields/Date.php
  src/lib/Behat/Component/Fields/DateAndTime.php
  src/lib/Behat/Component/Fields/Time.php
Labels: Ready for review

#1832 [Behat] Adjusted selectors to redesign
  src/lib/Behat/Page/ContentTypeUpdatePage.php
Labels: Ready for review

#1830 IBX-375: Fixed setting 2nd menu level active
  src/bundle/Resources/views/parts/menu/top_menu_2nd_level.html.twig
Labels: Bug, QA approved
