Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-06, with the labels that each got.

#1766 [Behat] Fixed imports in v3 merge-up
  src/lib/Behat/BusinessContext/UserPreferencesContext.php
  src/lib/Behat/PageObject/ChangePasswordPage.php
Labels: Ready for review

#1769 IBX-457: Fix update button in Change my password
  src/lib/EventListener/UserPasswordChangeRightSidebarListener.php
Labels: Bug, QA approved

#1775 [Composer] Bumped ezplatform-kernel require to ~1.2.8@dev
  composer.json
Labels: Ready for review

#1776 IBX-523: Create content menu causes console error
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
Labels: QA approved

#1779 IBX-445: selected first enabled language for create content #291
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
Labels: Bug, QA approved, Ready for review

#1778 EZP-32387: Fixed text block toolbar alignment
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
Labels: Bug, QA approved

#1772 IBX-426: Created additional UDW config for adding Location to Content
  src/bundle/Resources/config/universal_discovery_widget.yaml
  src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
  src/lib/UniversalDiscovery/Event/Subscriber/AddLocation.php
Labels: Bug, QA approved

#1768 IBX-455: Added selected content from bookmarks to the top of list content items
  src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
Labels: Improvement, QA approved

#1781 IBX-461: Fixed roles with deleted limitations
  src/lib/Form/DataTransformer/UDWBasedValueModelTransformer.php
  src/lib/Limitation/Templating/LimitationBlockRenderer.php
  src/lib/Tests/Form/DataTransformer/UDWBasedValueViewTransformerTest.php
Labels: Bug, QA approved

#1773 Added Twig templates for table and tabs
  src/bundle/Resources/views/themes/admin/ui/component/macros.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tab_pane.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tabs.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
Labels: Doc needed

#1782 IBX-154: Allowed to define if the alternative text for image field is required (2.5)
  src/bundle/Controller/AssetController.php
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
  src/bundle/Resources/public/scss/fieldType/edit/_ezimage.scss
  src/bundle/Resources/views/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/fieldtypes/edit/ezimage.html.twig
Labels: QA approved

#1784 IBX-648: Added styles for backported landing page FT settings
  src/bundle/Resources/public/scss/_custom.scss
Labels: QA approved

#1786 IBX-662: Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null at setContainerHeight
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
Labels: QA approved

#1780 IBX-497: As an Editor, I want to see redesigned tabs
  src/bundle/Controller/ContentController.php
  src/bundle/Controller/ObjectStateController.php
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
  src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js
  src/bundle/Resources/public/js/scripts/admin.location.tab.js
  src/bundle/Resources/public/js/scripts/admin.location.visibility.js
  src/bundle/Resources/public/js/scripts/core/adaptive.items.js
  src/bundle/Resources/public/scss/_header.scss
  src/bundle/Resources/public/scss/_popup-menu.scss
  src/bundle/Resources/public/scss/_tabs.scss
  src/bundle/Resources/public/scss/_warning-icon.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/popup_menu/popup_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/popup_menu/popup_menu_item.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tab_corner.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tab_pane.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tabs.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_header.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_link.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_tab.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_draft_list.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_drafts.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
  src/bundle/Resources/views/themes/admin/ui/tab/content_type.html.twig
  src/bundle/Resources/views/themes/admin/ui/tab/default.html.twig
  src/bundle/Resources/views/themes/admin/ui/tab/location_view.html.twig
  src/bundle/Resources/views/themes/admin/ui/tab/url_management.html.twig
  src/bundle/Resources/views/themes/admin/url_wildcard/update.html.twig
  src/bundle/Resources/views/themes/admin/user/role/index.html.twig
  src/lib/Behat/PageElement/NavLinkTabs.php
  src/lib/Behat/PageObject/DashboardPage.php
  src/lib/Tab/ContentType/TranslationsTab.php
  src/lib/Tab/ContentType/ViewTab.php
  src/lib/Tab/LocationView/DetailsTab.php
  src/lib/Tab/LocationView/LocationsTab.php
  src/lib/Tab/LocationView/PoliciesTab.php
  src/lib/Tab/LocationView/RelationsTab.php
  src/lib/Tab/LocationView/RolesTab.php
  src/lib/Tab/LocationView/TranslationsTab.php
  src/lib/Tab/LocationView/UrlsTab.php
  src/lib/Tab/LocationView/VersionsTab.php
  src/lib/Tab/URLManagement/LinkManagerTab.php
  src/lib/Tab/URLManagement/URLWildcardsTab.php
Labels: Feature, Improvement, Work in progress
