Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-12, with the labels that each got.

#2019 IBX-1604: Fixed deprecation warning thrown by PHP8
  src/lib/Security/Authentication/RedirectToDashboardAuthenticationSuccessHandler.php
Labels: Bug, QA approved

#2015 IBX-1514: Refactored 'read' UDW config resolvers
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
  src/lib/Tests/UniversalDiscovery/Event/Subscriber/ContentCreateTest.php
  src/lib/Tests/UniversalDiscovery/Event/Subscriber/ReadAllowedContentTypesTest.php
  src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
  src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php
  src/lib/UniversalDiscovery/Event/Subscriber/ReadAllowedContentTypes.php
Labels: Bug, Ready for MERGE, QA approved

#1985 [Behat] IBX-978 Verify product page on frontend
  src/lib/Behat/BrowserContext/ContentUpdateContext.php
  src/lib/Behat/Component/Fields/ImageAsset.php
  src/lib/Behat/Page/ContentUpdateItemPage.php
  src/lib/Behat/Page/UserUpdatePage.php
Labels: Ready for review

#2020 [Behat] Fixed typo in ContentType feature
  features/standard/ContentType.feature
Labels: Ready for review
