Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-03, with the labels that each got.

#1716 Revert "EZEE-3479: As a developer I want to have reusable componenet for charts"
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/core/base.chart.js
  src/bundle/Resources/public/js/scripts/core/line.chart.js
  src/bundle/Resources/public/js/scripts/core/pie.chart.js
  src/bundle/Resources/public/scss/core/_chart.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/views/themes/admin/ui/chart.html.twig
  src/bundle/Resources/views/themes/admin/ui/chart/legend_checkbox.html.twig
Labels: QA approved

#1717 EZEE-3486: Added AllowedContentTypes to default config as it was overridden by default empty value
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
  src/lib/UniversalDiscovery/Event/Subscriber/ImageAssetAllowedContentTypes.php
Labels: QA approved

#1722 [Behat] Added sorting subitems by Modified date
  src/lib/Behat/BusinessContext/ContentViewContext.php
Labels: Ready for review

#1721 EZP-31632: Floating table toolbar
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base-fixed.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base-table.js
  src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
Labels: Improvement, QA approved

#1727 Fixed EzSystems\EzPlatformAdminUi\UI\Action\FormUiActionMapperInterface alias definition
  src/bundle/Resources/config/services/form_ui_action_mappers.yaml
Labels: Bug

#1726 EZP-32396: Content tree doesn't expand to current location
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
Labels: QA approved

#1725 EZP-32395: Sort out Locations tab info on visibility
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
Labels: Bug, QA approved
