Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-05, with the labels that each got.

#1744 EZP-31602: Moving to trash confirmation modal is not updated after sub-items bulk move
  src/bundle/Resources/public/js/scripts/admin.trash.js
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/views/content/locationview.html.twig
  src/bundle/Resources/views/content/modal_location_trash.html.twig
Labels: Bug, Ready for QA

#1752 IBX-300: removed add offset timezone to date, after changed date field to using timezone with timestamp
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
Labels: Bug, QA approved

#1754 EZP-31602: merge up 2.5 -> 3.0
  src/bundle/Resources/public/js/scripts/admin.trash.js
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content/modal/location_trash.html.twig
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
Labels: Ready for QA

#1753 IBX-241: Subitems - priority buttons hidden behind most-right column
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss
Labels: Bug, QA approved

#1739 IBX-22: Added danger font color
  src/bundle/Resources/public/scss/_custom.scss
Labels: QA approved

#1747 IBX-151: Decoupled userBundle
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/menu.yaml
  src/bundle/Resources/config/services/user.yaml
  src/lib/EventListener/UserMenuListener.php
  src/lib/EventListener/UserPasswordChangeRightSidebarListener.php
  src/lib/Form/Data/User/UserPasswordChangeData.php
  src/lib/Form/Data/User/UserPasswordForgotData.php
  src/lib/Form/Data/User/UserPasswordForgotWithLoginData.php
  src/lib/Form/Data/User/UserPasswordResetData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/SubmitHandler.php
  src/lib/Form/Type/User/UserPasswordChangeType.php
  src/lib/Form/Type/User/UserPasswordForgotType.php
  src/lib/Form/Type/User/UserPasswordForgotWithLoginType.php
  src/lib/Form/Type/User/UserPasswordResetType.php
  src/lib/Notification/TranslatableNotificationHandler.php
  src/lib/Tests/Validator/Constraint/PasswordTest.php
  src/lib/Tests/Validator/Constraint/PasswordValidatorTest.php
  src/lib/Tests/Validator/Constraint/UserPasswordTest.php
  src/lib/Tests/Validator/Constraint/UserPasswordValidatorTest.php
  src/lib/Validator/Constraints/Password.php
  src/lib/Validator/Constraints/PasswordValidator.php
  src/lib/Validator/Constraints/UserPassword.php
  src/lib/Validator/Constraints/UserPasswordValidator.php
Labels: Ready for MERGE

#1750 IBX-340: Prevented multiple count operations when attempting to paginate URL tab
  src/lib/Pagination/Pagerfanta/URLSearchAdapter.php
Labels: QA approved

#1749 IBX-267: As a Maintainer, I want to have defined color palette and typography
  src/bundle/Resources/public/scss/_custom.scss
Labels: Ready for review

#1756 IBX-354: Used fullsized thumbnails if svg is provided
  src/bundle/ui-dev/src/modules/sub-items/components/grid-view/grid.view.item.component.js
  src/bundle/ui-dev/src/modules/sub-items/services/sub.items.service.js
Labels: QA approved

#1759 EZP-32333: Hidden duplicated 'change password' menu item
  src/lib/Menu/UserMenuBuilder.php
Labels: Bug, QA approved

#1710 RSYS-3261: Improved charts section different data structure
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/core/base.chart.js
  src/bundle/Resources/public/js/scripts/core/line.chart.js
  src/bundle/Resources/public/js/scripts/core/pie.chart.js
  src/bundle/Resources/public/scss/core/_chart.scss
  src/bundle/Resources/views/themes/admin/ui/chart.html.twig
Labels: QA approved

#1761 IBX-418: Skipped content name retrieve for the top node
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Bug, QA approved

#1758 IBX-385: Fixed error handling when composer files are corrupted
  src/bundle/Resources/config/default_parameters.yml
  src/bundle/Resources/translations/systeminfo.en.xliff
  src/bundle/Resources/views/admin/systeminfo/invalid.html.twig
Labels: Improvement, QA approved

#1763 IBX-186: The top button of side menus gets hidden at the bottom of the page
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
  src/bundle/Resources/public/scss/_extra-actions.scss
  src/bundle/Resources/public/scss/_general.scss
Labels: QA approved

#1764 [Behat] IBX-405: Behat coverage for changing user password
  behat_suites.yml
  features/personas/ChangePassword.feature
  src/lib/Behat/BusinessContext/NavigationContext.php
  src/lib/Behat/BusinessContext/UserPreferencesContext.php
  src/lib/Behat/PageObject/ChangePasswordPage.php
  src/lib/Behat/PageObject/PlatformPageObjectFactory.php
Labels: Ready for review

#1765 IBX-186: The top button of side menus gets hidden at the bottom of the page (mergeup fix)
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
Labels: QA approved
