Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-11, with the labels that each got.

#1984 [CI] Added job for wrong target branch detection
  .github/workflows/pr-check.yaml
  .github/workflows/pr_check.yaml
Labels: Ready for review

#1996 IBX-1356: Backported fix for TranslationChoiceLoader
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/views/dashboard/tab/all_content.html.twig
  src/bundle/Resources/views/dashboard/tab/all_media.html.twig
  src/bundle/Resources/views/dashboard/tab/my_content.html.twig
  src/bundle/Resources/views/dashboard/tab/my_media.html.twig
  src/lib/Form/Type/ChoiceList/Loader/ContentEditTranslationChoiceLoader.php
  src/lib/Form/Type/Content/Translation/TranslationAddType.php
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
Labels: Bug, QA approved

#2000 [Behat] Stability fixes
  src/lib/Behat/BrowserContext/ContentTypeContext.php
  src/lib/Behat/Component/IbexaDropdown.php
  src/lib/Behat/Page/ContentTypeUpdatePage.php
Labels: Ready for review

#1998 IBX-1116: Redesign Calendar: move react dropdown to common components
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/flag.svg
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_dropdown.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.scss
  src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/filters/filters.js
Labels: Improvement, Ready for review

#1935 Fixed content always being translated using a base translation
  src/bundle/Resources/config/routing.yaml
  src/lib/EventListener/ContentProxyCreateDraftListener.php
  src/lib/Form/Type/Content/Translation/TranslationAddType.php
  src/lib/Form/Type/ContentType/Translation/TranslationAddType.php
Labels: Bug, QA approved

#2012 IBX-1465: Prioritize current site access when choosing language
  src/lib/UI/Config/Provider/Languages.php
Labels: Bug, Ready for MERGE, QA approved

#2016 EZEE-3213: Added verification if the user has section/view permission
  src/bundle/Controller/TrashController.php
  src/bundle/Resources/views/themes/admin/trash/list.html.twig
Labels: Bug, QA approved

#2018 IBX-1465: Prioritize current site access when choosing language
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
  src/lib/UI/Config/Provider/Languages.php
Labels: Bug, Ready for MERGE, QA approved
