Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-01, with the labels that each got.

#1688 EZP-32180: Some of the selection list elements are not visible
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
Labels: QA approved

#1691 EZP-32279: Dropdown is not properly styled, adjusted for content type…
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
Labels: Bug, QA approved

#1689 EZP-32166: Base translation dropdown single selection issue
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
  src/bundle/Resources/public/scss/_add-translation.scss
  src/bundle/Resources/public/scss/core/_custom.dropdown.scss
Labels: QA approved

#1692 EZP-32285: Cropped image needs to be improved in UDW thumbnail view
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.item.scss
Labels: Bug, QA approved

#1693 EZP-32287: Wrong size of a Save tile on the URL management edit page
  src/bundle/Resources/views/themes/admin/link_manager/edit.html.twig
Labels: Ready for QA

#1695 EZP-32179: Add footer to platform when user is logged in
  src/bundle/Resources/public/img/ibexa-wordmark.svg
  src/bundle/Resources/public/scss/_footer.scss
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/_main-row.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/account/bookmarks/list.html.twig
  src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
  src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
  src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/index.html.twig
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
  src/bundle/Resources/views/themes/admin/content_type/index.html.twig
  src/bundle/Resources/views/themes/admin/language/index.html.twig
  src/bundle/Resources/views/themes/admin/language/list.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/list.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/view.html.twig
  src/bundle/Resources/views/themes/admin/section/list.html.twig
  src/bundle/Resources/views/themes/admin/section/view.html.twig
  src/bundle/Resources/views/themes/admin/trash/list.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig
  src/bundle/Resources/views/themes/admin/ui/footer.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/index.html.twig
  src/bundle/Resources/views/themes/admin/url_management/url_management.html.twig
  src/bundle/Resources/views/themes/admin/user/policy/edit.html.twig
  src/bundle/Resources/views/themes/admin/user/role/index.html.twig
  src/bundle/Resources/views/themes/admin/user/role/list.html.twig
Labels: QA approved
