Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-02, with the labels that each got.

#1698 EZEE-3455: [Image upload] no validation message for files bigger than 2mb
  src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
  src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
  src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
Labels: QA approved

#1702 EZEE-3455: [Image upload] no validation message for files bigger than 2mb
  src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
  src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
  src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
Labels: QA approved

#1696 EZEE-3459: Cannot use image editor in product content type
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
Labels: Bug, QA approved

#1703 EZP-32321: Added deleteTranslations target to fix 'content/remove' permission check
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/UI/Value/ValueFactory.php
Labels: Bug, QA approved, Ready for review

#1700 EZEE-3375: 'Multiple' PB block's attribute is not rendering properly
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/mixins/_inputs.scss
Labels: QA approved

#1706 EZEE-3465: Made SiteaccessPreviewVoter repository aware
  src/lib/Siteaccess/AbstractSiteaccessPreviewVoter.php
  src/lib/Tests/Siteaccess/AdminSiteaccessPreviewVoterTest.php
Labels: Bug, QA approved

#1699 EZP-32308: Passed mandatory Location into LocationLimitation
  src/bundle/Controller/ContentViewController.php
  src/lib/Form/Type/ChoiceList/Loader/ContentEditTranslationChoiceLoader.php
  src/lib/Form/Type/Content/Translation/TranslationAddType.php
  src/lib/Tab/LocationView/TranslationsTab.php
Labels: QA approved

#1705 EZEE-3479: As a developer I want to have reusable componenet for charts
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/core/base.chart.js
  src/bundle/Resources/public/js/scripts/core/line.chart.js
  src/bundle/Resources/public/js/scripts/core/pie.chart.js
  src/bundle/Resources/public/scss/core/_chart.scss
  src/bundle/Resources/public/scss/ezplatform.scss
  src/bundle/Resources/views/themes/admin/ui/chart.html.twig
  src/bundle/Resources/views/themes/admin/ui/chart/legend_checkbox.html.twig
Labels: QA approved

#1707 EZP-32294: Location removal removes all children silently and unreversable
  src/bundle/Controller/LocationController.php
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/views/content/tab/locations/tab.html.twig
Labels: Bug, QA approved

#1711 EZP-32338: List url aliases for all available translations
  src/lib/Tab/LocationView/UrlsTab.php
Labels: Bug, QA approved

#1709 EZP-32311: Dropdown bottom options become inaccessible inside modals
  src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
Labels: Bug, QA approved

#1667 [Travis] Switched to using Flex for testing
  .travis.yml
  .travis/prepare_ezplatform.sh
  composer.json
Labels: Ready for review
