Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2021-08, with the labels that each got.

#1829 IBX-93: [Behat] Fixed calculating Richtext button positions
  src/lib/Behat/Component/Fields/RichText.php
Labels: Ready for review

#1796 IBX-612: As an Editor, I want to see redesigned input field in all states
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/warning-triangle.svg
  src/bundle/Resources/public/js/scripts/admin.input.text.js
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/public/scss/_labels.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/mixins/_font.scss
  src/bundle/Resources/views/themes/admin/account/change_password/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/account/change_password/index.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/content_header.html.twig
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/create.html.twig
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/edit.html.twig
  src/bundle/Resources/views/themes/admin/content_type/create.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
  src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/themes/admin/language/create.html.twig
  src/bundle/Resources/views/themes/admin/language/edit.html.twig
  src/bundle/Resources/views/themes/admin/link_manager/edit.html.twig
  src/bundle/Resources/views/themes/admin/object_state/add.html.twig
  src/bundle/Resources/views/themes/admin/object_state/edit.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/add.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/edit.html.twig
  src/bundle/Resources/views/themes/admin/section/create.html.twig
  src/bundle/Resources/views/themes/admin/section/update.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
  src/bundle/Resources/views/themes/admin/url_wildcard/update.html.twig
  src/bundle/Resources/views/themes/admin/user/role/add.html.twig
  src/bundle/Resources/views/themes/admin/user/role/copy.html.twig
  src/bundle/Resources/views/themes/admin/user/role/edit.html.twig
  src/bundle/ui-dev/src/modules/universal-discovery/components/filters/filters.js
  src/lib/Behat/Page/RoleUpdatePage.php
Labels: Feature, Improvement

#1838 [Behat] Corrected selector for main container in Admin update pages
  src/lib/Behat/Page/AdminUpdateItemPage.php
  src/lib/Behat/Page/ContentTypeUpdatePage.php
  src/lib/Behat/Page/RoleUpdatePage.php
Labels: Ready for review

#1801 IBX-614: As an Editor, I want to see redesigned text area in all states
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Improvement

#1792 IBX-704: Added aggregation support to NodeFactory
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/services/modules/content_tree.yaml
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Improvement, Ready for review, QA approved

#1841 IBX-93: [Behat] Switched to JS script for invoking CKEditor toolbar
  src/lib/Behat/Component/Fields/RichText.php
Labels: Ready for review

#1840 IBX-836: [Behat] Changed menu buttons to click directly on label
  src/lib/Behat/Component/ContentActionsMenu.php
Labels: Ready for review

#1855 IBX-884: It's not possible to set block reveal and hide date
  src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
Labels: QA approved

#1866 IBX-901: As an Editor, I want to see redesigned alerts
  src/bundle/Resources/public/scss/_alerts.scss
  src/bundle/Resources/public/scss/_icons.scss
  src/bundle/Resources/views/themes/admin/account/settings/update_datetime_format.html.twig
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content/relation_unauthorized.html.twig
  src/bundle/Resources/views/themes/admin/content_type/part/nontranslatable_fields_disabled.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/preview_unavailable.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
  src/bundle/Resources/views/themes/admin/url_wildcard/list.html.twig
Labels: Improvement, Ready for review, Doc needed

#1867 IBX-916: Changed selector for ezselection validator
  src/bundle/Resources/public/js/scripts/fieldType/ezselection.js
Labels: QA approved

#1869 Fixed wrong enclosing tag in location_view.html.twig
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
Labels: Bug

#1871 IBX-923: Fixed issue with disabling deletion of Content Type Groups
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig
Labels: Bug, QA approved
