Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2022-01, with the labels that each got.

#2025 IBX-1799: Added new UDW configuration for Subtree filter
  src/bundle/Resources/config/universal_discovery_widget.yaml
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
  src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
Labels: Bug, Ready for MERGE, QA approved

#2024 [CI] Removed composer-package-version argument
  .github/workflows/browser-tests.yaml
Labels: Ready for review

#2027 IBX-1886: Dart Sass compatibility added
  src/bundle/Resources/public/scss/functions/_calculate.rem.scss
  src/bundle/Resources/public/scss/polyfill/_div.import.scss
  src/bundle/Resources/public/scss/polyfill/_div.scss
Labels: Ready for review, QA approved

#2023 IBX-1552 As a QA I want spike test coverage for deep links
  features/standard/Authentication.feature
Labels: Ready for review

#2022 [Behat] Added language selection coverage
  src/lib/Behat/BrowserContext/ContentUpdateContext.php
  src/lib/Behat/BrowserContext/ContentViewContext.php
  src/lib/Behat/Component/ContentTypePicker.php
  src/lib/Behat/Page/ContentUpdateItemPage.php
  src/lib/Behat/Page/ContentViewPage.php
Labels: Ready for review

#2030 IBX-1999: Added pagination to URL Wildcard tab in URL Management
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/bundle/Resources/views/themes/admin/url_wildcard/list.html.twig
  src/lib/Pagination/Pagerfanta/URLWildcardAdapter.php
  src/lib/Tab/URLManagement/URLWildcardsTab.php
  src/lib/Tests/Pagination/Pagerfanta/URLWildcardAdapterTest.php
Labels: Improvement, QA approved
