Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2022-02, with the labels that each got.

#2033 IBX-1090: Fixed calculations and displaying of ezdate FT, as it should always be represented in UTC
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
Labels: QA approved

#2036 IBX-2331: UDW submit button shows up in inconsistent way
  src/bundle/ui-dev/src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-table/content.table.item.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.leaf.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/tree-view/tree.view.js
Labels: Bug, Ready for MERGE, QA approved

#2035 IBX-2333: Fixed allowed Content Types for relations in UDW
  src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
  src/lib/UniversalDiscovery/Event/Subscriber/ReadAllowedContentTypes.php
Labels: Bug, QA approved
