Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2022-05, with the labels that each got.

#2044 [Behat] Split ContentTypeFields feature file
  features/standard/ContentTypeFields.feature
  features/standard/fields/contentQuery.feature
  features/standard/fields/date.feature
  features/standard/fields/map.feature
  features/standard/fields/media.feature
  features/standard/fields/other.feature
  features/standard/fields/relations.feature
  features/standard/fields/text.feature
Labels: Ready for review

#2045 IBX-2880: Changed CredentialsExpiredListener to expect PasswordExpiredException
  src/lib/EventListener/CredentialsExpiredListener.php
Labels: Bug, Ready for MERGE, QA approved

#2042 IBX-2000: Added search into URL Wildcard tab
  src/bundle/Resources/config/services/forms.yaml
  src/bundle/Resources/translations/ezplatform_url_wildcard.en.xliff
  src/bundle/Resources/views/themes/admin/url_wildcard/list.html.twig
  src/lib/Form/Data/URLWildcard/URLWildcardListData.php
  src/lib/Form/Type/URLWildcard/URLWildcardListType.php
  src/lib/Pagination/Pagerfanta/URLWildcardAdapter.php
  src/lib/Tab/URLManagement/URLWildcardsTab.php
  src/lib/Tests/Pagination/Pagerfanta/URLWildcardAdapterTest.php
Labels: Improvement, QA approved

#2047 IBX-857: Added call invalidateSize on each map when tab clicked and if tab contains any map
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
Labels: Bug, Ready for MERGE, QA approved

#2040 [Behat] IBX-2321-behat-coverage-for-autosave
  behat_suites.yml
  features/standard/Autosave.feature
  src/bundle/Resources/config/services/test/pages.yaml
  src/lib/Behat/BrowserContext/ContentUpdateContext.php
  src/lib/Behat/BrowserContext/NavigationContext.php
  src/lib/Behat/BrowserContext/UserPreferencesContext.php
  src/lib/Behat/Page/ContentUpdateItemPage.php
  src/lib/Behat/Page/UserSettingsPage.php
Labels: Ready for review

#2046 IBX-2081: Added ez-sticky-container div to context-menu div
  src/bundle/Resources/views/themes/admin/url_wildcard/update.html.twig
Labels: Bug, QA approved
