Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2022-12, with the labels that each got.

#2074 IBX-1648: Added redirect when the trash form has any error
  src/bundle/Controller/LocationController.php
Labels: Ready for MERGE, QA approved

#2080 IBX-4130: Optimized subitems fetching in UDW
  src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
Labels: Improvement, Ready for MERGE, QA approved

#2075 IBX-4125: Optimized Dashboard tabs
  src/bundle/Resources/config/services/dashboard.yaml
  src/bundle/Resources/config/services/query_types.yaml
  src/lib/QueryType/ContentLocationSubtreeQueryType.php
  src/lib/QueryType/LocationSubtreeQueryType.php
  src/lib/QueryType/MediaLocationSubtreeQueryType.php
  src/lib/Tab/Dashboard/AbstractContentTab.php
  src/lib/Tab/Dashboard/AbstractMediaTab.php
  src/lib/Tab/Dashboard/EveryoneContentTab.php
  src/lib/Tab/Dashboard/EveryoneMediaTab.php
  src/lib/Tab/Dashboard/MyContentTab.php
  src/lib/Tab/Dashboard/MyMediaTab.php
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
  src/lib/Tab/Dashboard/PagerLocationToDataMapper.php
Labels: Improvement, Ready for MERGE, QA approved

#2082 IBX-3814: Added checks if the field to upload is type ezimage to add alternative text
  src/bundle/Resources/translations/multi_file_upload.en.xliff
  src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
Labels: Bug, Ready for MERGE, QA approved
