Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2022-08, with the labels that each got.

#2061 IBX-2559: Added new style to ez-extra-actions__content class to allow scrolling language list
  src/bundle/Resources/public/scss/_extra-actions.scss
Labels: Bug, Ready for MERGE, QA approved

#2062 IBX-3652: Selecting a bookmark after selecting an item in the Browser tab can be confusing
  src/bundle/ui-dev/src/modules/universal-discovery/bookmarks.tab.module.js
Labels: Bug, Ready for MERGE, QA approved

#2059 IBX-2964: Flatpickr widget localization
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/encore/ez.js.config.js
  src/bundle/Resources/public/js/scripts/widgets/flatpickr.js
  src/lib/UI/Config/Provider/BackOfficeLanguage.php
Labels: Improvement, Ready for MERGE, QA approved

#2060 IBX-3588: Allowed multiline notifications
  src/bundle/Resources/public/scss/_notifications.scss
Labels: Improvement, QA approved

#2058 IBX-3320: Unified content versions edit buttons logic
  src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
Labels: Bug, QA approved

#2065 IBX-3681 - Added selectedLanguage update on location change in UDW
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
Labels: Bug, QA approved
