Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2023-05, with the labels that each got.

#2101 IBX-4566: Increased timeout for menu navigation
  src/lib/Behat/Component/UpperMenu.php
Labels: Ready for review

#2099 IBX-5640: Added available translations to dashboard data
  src/lib/Tab/Dashboard/PagerLocationToDataMapper.php
Labels: Ready for review, QA approved

#2100 IBX-1786: [Content type translations] Notification for edited content type in incorrectly displayed
  src/bundle/Resources/views/themes/admin/content_type/part/nontranslatable_fields_disabled.html.twig
Labels: Ready for MERGE, QA approved

#2097 IBX-5472: Missing translation for search.date.range
  src/bundle/Resources/translations/ezplatform_content_forms_policies.en.xliff
  src/bundle/Resources/translations/fieldtypes_preview.en.xliff
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/search.en.xliff
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Ready for MERGE, QA approved

#2103 IBX-5758: [Trash] Custom range and its from date - to input does not contains properly formatted input style
  src/bundle/Resources/public/scss/_trash-search-form.scss
Labels: Ready for MERGE, QA approved
