Repository ezsystems/ezplatform-admin-ui, pull requests merged in 2023-02, with the labels that each got.

#2086 [Behat] Changed assertions removed in PHPUnit 10
  src/lib/Behat/Component/Fields/ContentRelationMultiple.php
  src/lib/Behat/Component/Fields/ContentRelationSingle.php
Labels: Ready for review

#2028 IBX-1948: Log exceptions from admin-ui
  src/bundle/Resources/config/services/events.yaml
  src/lib/EventListener/AdminExceptionListener.php
Labels: QA approved

#2090 [Composer] Disabled all plugins by default
  composer.json
Labels: Ready for review

#2088 IBX-4125: Updated error level in `PagerContentToDataMapper` constructor
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
Labels: Bug, Ready for MERGE

#2085 IBX-4477: Improved copy subtree limit check performance
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Specification/Location/IsWithinCopySubtreeLimit.php
  src/lib/Tests/Validator/Constraint/LocationIsWithinCopySubtreeLimitValidatorTest.php
Labels: Bug, QA approved

#2093 IBX-5143: Fixed autosave default value
  src/lib/UserSetting/Autosave.php
Labels: Bug, Ready for MERGE, Ready for review, QA approved
